begin;select plan(29);
select has_table('public'::name,'tkid_relay_flows'::name);select has_table('public'::name,'tkid_relay_continuities'::name);
select is((select column_default from information_schema.columns where table_schema='public' and table_name='tkid_relay_flows' and column_name='status'),$$'draft'::text$$,'flows default draft');
select is((select column_default from information_schema.columns where table_schema='public' and table_name='tkid_relay_flows' and column_name='continuity_ttl_seconds'),'5400','TTL defaults 90 minutes');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='tkid_relay_continuities' and column_name='initiation_digest'),'initiation digest exists');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='tkid_relay_continuities' and column_name='cookie_digest'),'cookie digest exists');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='tkid_relay_continuities' and column_name='journey_id'),'Journey reference exists');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='tkid_relay_continuities' and column_name='return_count'),'return count exists');
select has_table('public'::name,'tkid_relay_events'::name);
select has_function('public','erase_tkid_relay_continuity',array['uuid','uuid','timestamp with time zone']);
select has_function('public','erase_tkid_relay_on_journey_tombstone',array[]::text[]);
select has_trigger('public'::name,'tkid_journeys'::name,'tkid_relay_journey_erasure'::name);
select is((select relrowsecurity from pg_class where oid='public.tkid_relay_flows'::regclass),true,'flows enable RLS');
select is((select relrowsecurity from pg_class where oid='public.tkid_relay_continuities'::regclass),true,'continuities enable RLS');
select is((select has_table_privilege('anon','public.tkid_relay_flows','select')),false,'anon cannot read flows');
select is((select has_table_privilege('authenticated','public.tkid_relay_continuities','insert')),false,'browser cannot create continuity');
select is((select has_table_privilege('anon','public.tkid_relay_events','select')),false,'browser cannot read relay Evidence');
select is((select has_table_privilege('service_role','public.tkid_relay_flows','select')),true,'service reads flows');
select is((select has_table_privilege('service_role','public.tkid_relay_continuities','insert')),true,'service creates continuity');
select ok(exists(select 1 from pg_constraint where conname='tkid_relay_flows_organization_id_source_id_fkey'),'source tenant FK');
select ok(exists(select 1 from pg_constraint where conname='tkid_relay_flows_organization_id_source_origin_id_fkey'),'source origin tenant FK');
select ok(exists(select 1 from pg_constraint where conname='tkid_relay_flows_organization_id_return_origin_id_fkey'),'return origin tenant FK');
select ok(exists(select 1 from pg_indexes where indexname='tkid_relay_one_open_browser_flow_uidx'),'same-flow concurrency fails closed');
select ok(exists(select 1 from pg_indexes where indexname='tkid_relay_cookie_lookup_idx'),'opaque cookie lookup indexed');
select throws_ok($$insert into public.tkid_relay_flows(id,account_id,organization_id,business_context_id,source_id,flow_key,name,source_origin_id,checkout_destination,checkout_host,return_origin_id) values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),'x',gen_random_uuid(),'valid-flow','x',gen_random_uuid(),'https://evil.example','evil.example',gen_random_uuid())$$,'23503',null,'tenant constraints fail closed before arbitrary flow');
select ok(position('email' in obj_description('public.tkid_relay_continuities'::regclass))=0,'continuity contract has no email');
select ok(position('raw IP' in obj_description('public.tkid_relay_continuities'::regclass))>0,'raw IP excluded explicitly');
select is((select count(*)::integer from public.tkid_relay_flows where status='enabled'),0,'no relay flow enabled');
select is((select count(*)::integer from public.commerce_repository_activation),0,'no Workspace activation');
select * from finish();rollback;
