import { createHash } from "node:crypto";
export type FindingType="observation"|"correlation"|"negative_finding"|"hypothesis";
export const normalizeReason=(raw:string)=>{const v=raw.trim().toLowerCase();if(["fraud","fraudulent"].includes(v)||v.includes("card absent")||v.includes("authorization"))return"fraud_or_unauthorized";if(v==="product_not_received"||v.includes("not received"))return"not_received";if(v==="credit_not_processed"||v.includes("credit not processed"))return"credit_not_processed";if(v==="general")return"general";return"other";};
export const timingBucket=(minutes:number)=>minutes<15?"<15m":minutes<30?"15-30m":minutes<60?"30-60m":minutes<120?"1-2h":minutes<360?"2-6h":minutes<1440?"6-24h":">24h";
export function percentile(values:number[],p:number){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),position=(sorted.length-1)*p,low=Math.floor(position),high=Math.ceil(position);return sorted[low]+(sorted[high]-sorted[low])*(position-low);}
export function distributionDelta(affected:Record<string,number>,control:Record<string,number>){const aTotal=Object.values(affected).reduce((a,b)=>a+b,0),cTotal=Object.values(control).reduce((a,b)=>a+b,0);return Object.fromEntries(Array.from(new Set([...Object.keys(affected),...Object.keys(control)])).sort().map(k=>[k,{affected:aTotal?affected[k]/aTotal:0,control:cTotal?control[k]/cTotal:0,delta:(aTotal?affected[k]/aTotal:0)-(cTotal?control[k]/cTotal:0)}]));}
export const matureAt=(transactionDate:string,maturityDays:number)=>new Date(new Date(transactionDate).valueOf()+maturityDays*86_400_000).toISOString();
export function stableInvestigationId(input:unknown){return createHash("sha256").update(JSON.stringify(input)).digest("hex");}
export function buildPartialJourney(input:{clickAt:string|null;conversionAt:string;orders:{at:string;product:string;amount:number}[];refundAt?:string|null;disputeAt?:string|null}){return{steps:[...(input.clickAt?[{source:"everflow",event:"click",at:input.clickAt}]:[]),{source:"everflow",event:"conversion",at:input.conversionAt},...input.orders.sort((a,b)=>a.at.localeCompare(b.at)).map(o=>({source:"commas",event:"charge",at:o.at,product:o.product,amount:o.amount})),...(input.refundAt?[{source:"commas",event:"refund",at:input.refundAt}]:[]),...(input.disputeAt?[{source:"resolution_center",event:"dispute",at:input.disputeAt}]:[])],evidenceGaps:["landing_page_sequence","page_dwell_time","vsl_watch_percentage","cta_interactions","checkout_field_progression","upsell_impression_or_rejection","return_visits","client_errors","cross_domain_session_continuity"]};}
