import type { SafeInvestigationDetail, SafeInvestigationInspection } from "./presentation";
import { inspectionKey } from "./presentation";

type Input = Omit<SafeInvestigationDetail,"inspections">;
const notes=(...values:Array<string|undefined>)=>values.filter((value):value is string=>Boolean(value));

export function buildInvestigationInspections(investigation:Input):SafeInvestigationInspection[]{
  const p=investigation.presentation, base={sources:p.provenance.sources,algorithmVersion:investigation.versions.algorithm};
  const result:SafeInvestigationInspection[]=[];
  for(const metric of p.evidenceQuality) result.push({type:"evidence-quality",key:inspectionKey(metric.label),label:"Evidence quality",title:metric.label,context:"Coverage and denominator definition for this immutable analysis version.",rows:[{label:"Value",value:metric.value,tone:"brand"},{label:"Numerator / denominator",value:metric.detail||"Not applicable"},{label:"Analysis period",value:p.period}],notes:notes(metric.warning,"Orders outside source coverage are not classified as failed attribution.",`Methodology: ${p.provenance.journeyRule}`),...base});
  for(const finding of p.findings) result.push({type:"finding",key:finding.id,label:finding.kind.replaceAll("_"," "),title:finding.title,context:finding.statement,rows:[{label:"Metric",value:finding.metric||"Qualitative finding",tone:finding.kind==="negative_finding"?"success":finding.kind==="hypothesis"?"warning":finding.kind==="correlation"?"correlation":"brand"},{label:"Affected sample",value:finding.sample||"Evidence subset"},{label:"Control",value:finding.control||"Not applicable"},{label:"Evidence quality",value:finding.quality},{label:"Attribution provenance",value:finding.provenance.replaceAll("_"," ")}],notes:["This finding presents persisted analytical output and does not recompute or modify the Investigation."],sources:p.provenance.sources,algorithmVersion:finding.algorithmVersion,relatedInvestigation:finding.id.includes("oto2")?related(investigation):undefined});
  for(const step of p.journey) result.push({type:"journey",key:inspectionKey(step.label),label:"Journey step",title:step.label,context:step.detail,rows:[{label:"Evidence state",value:step.state,tone:step.state==="observed"?"success":step.state==="propagated"?"correlation":"neutral"},{label:"Source",value:journeySource(step.label)},{label:"Journey rule",value:p.provenance.journeyRule}],notes:step.state==="missing"?["TraceKit does not fabricate this historical event.","Prospective first-party Journey instrumentation is required to close this gap."]:["Observed and propagated Evidence remain explicitly distinguishable."],...base});
  for(const status of p.outcome.statuses) result.push({type:"dispute",key:inspectionKey(status.label),label:investigation.parent?"Cohort outcome":"Dispute aggregate",title:status.label,context:investigation.parent?"A mutually exclusive outcome in the linked Main + OTO2 Journey cohort.":"Aggregate historical dispute status; individual customer and dispute records are excluded.",rows:[{label:investigation.parent?"Journeys":"Count",value:status.count.toLocaleString()},{label:"Share",value:status.percent,tone:"brand"},{label:"Analysis period",value:p.period},{label:"Evidence coverage",value:p.evidenceQuality.find(m=>m.label.includes("dispute reconciliation"))?.value||"Cohort-specific"}],notes:notes(investigation.parent&&/main only/i.test(status.label)?"Insufficient sample for inference.":undefined,"No individual customer or dispute identifiers are exposed.","No dispute response or servicing action is available from this inspection."),...base});
  for(const item of p.concentration){
    const isProduct=/OTO2|Push Button/i.test(item.subject), type=isProduct?"product":"cohort" as const;
    result.push({type,key:inspectionKey(item.subject),label:isProduct?"Product detail":"Cohort detail",title:item.subject,context:item.interpretation,rows:[{label:"Primary signal",value:item.signal,tone:"brand"},{label:"Sample",value:item.sample},{label:"Evidence period",value:p.period},{label:"Attribution",value:isProduct&&/OTO2/i.test(item.subject)?"213 / 1,727 eligible OTO2 Orders":"See persisted cohort provenance"}],notes:notes(item.warning,isProduct?"Product risk does not establish affiliate causation.":"Cohort characteristics require a comparable control."),...base,relatedInvestigation:/OTO2/i.test(item.subject)?related(investigation):undefined});
  }
  if(p.multiCharge.length) result.push({type:"finding",key:"multi-charge",label:"Correlation",title:"Nearby charge count",context:"Dispute incidence rises with nearby charge count in the linked historical cohort.",rows:p.multiCharge.map(item=>({label:item.charges,value:item.rate,tone:"correlation" as const})),notes:["Product mix, affiliate mix, customer intent, funnel selection, and offer structure may confound this relationship.","This is not a causal claim."],...base});
  if(p.comparison.length) result.push({type:"cohort",key:investigation.parent?"oto2-only-v-neither":"nandi-v-other-pear",label:"Cohort vs control",title:investigation.parent?"Affected vs primary control":"Nandi vs other Pear",context:investigation.parent?"Selective OTO2 disputes compared with the cleanest available Main + OTO2 control.":"Nandi acquisition traffic compared with other comparable Pear Media traffic.",rows:[],cohortDefinitions:investigation.parent?[{label:"Affected",sample:"12 Journeys",definition:"Buyers who purchased Main + OTO2 and disputed only the OTO2 charge."},{label:"Control",sample:"156 Journeys",definition:"Comparable Main + OTO2 buyers where neither charge was disputed."}]:[{label:"Affected",sample:"1,244 Journey-linked Orders",definition:"Pear Media acquisition Journeys with sub1=nandi."},{label:"Control",sample:"2,382 attributed Orders",definition:"Other comparable Pear Media traffic in the same Evidence period."}],comparisonSummary:{label:investigation.parent?"No clear differentiator":"What this tells us",statement:comparisonSummary(investigation),tone:"success"},comparisons:p.comparison.map(row=>({metric:comparisonLabel(row.metric),definition:comparisonDefinition(row.metric),affected:displayValue(row.subject),control:displayValue(row.control),difference:numericDifference(row.delta),differenceExplanation:differenceExplanation(row.delta),interpretation:plainFinding(row.finding),limitation:comparisonLimitation(row.metric,row.delta)})),notes:["Affected and control values are presented together; positive differences mean affected is higher and negative differences mean affected is lower."],...base});
  if(investigation.parent){
    const cohorts=[{key:"affected",title:"OTO2-only disputed",value:"12",note:"Affected cohort; small sample warning required."},{key:"control",title:"Neither disputed",value:"156",note:"Primary comparable control."},{key:"both-disputed",title:"Both disputed",value:"40",note:"Secondary descriptive cohort."},{key:"main-only",title:"Main-only disputed",value:"2",note:"Insufficient sample for inference."}];
    for(const c of cohorts) result.push({type:"cohort",key:c.key,label:"Cohort detail",title:c.title,context:c.note,rows:[{label:"Journeys",value:c.value,tone:c.key==="affected"?"warning":"brand"},{label:"Parent Evidence",value:`${investigation.parent.title} · Version ${investigation.parent.version}`},{label:"Cohort period",value:p.period}],notes:[c.note,"No individual customer or Order identifiers are exposed."],...base});
  }
  result.push({type:"freshness",key:"investigation-freshness",label:"Investigation freshness",title:investigation.freshnessStatus.replaceAll("_"," "),context:"Freshness is separate from the immutable analytical status.",rows:[{label:"Analysis cutoff",value:p.provenance.analyzedAt},{label:"Latest relevant state",value:investigation.freshnessStatus.replaceAll("_"," "),tone:investigation.freshnessStatus==="current"?"success":"warning"},{label:"Last successful version",value:`Version ${investigation.version}`}],notes:[investigation.freshnessStatus==="current"?"No newer relevant Evidence currently intersects this Investigation's persisted dependencies.":"The existing version remains valid at its cutoff; refresh would create a new immutable version.","Opening this inspection does not queue a refresh."],...base});
  result.push({type:"evidence-quality",key:"historical-evidence-ceiling",label:"Evidence gap",title:"Historical Evidence ceiling",context:"Historical Commas and Everflow sources cannot resolve browser-level offer experience or consent questions.",rows:[{label:"Missing dimensions",value:String(p.evidenceGaps.length)},{label:"Historical status",value:"Ceiling reached",tone:"warning"}],notes:p.evidenceGaps,...base});
  return result;
}

function related(investigation:Input){const branch=investigation.branches.find(item=>/OTO2 Selective/i.test(item.title));return branch?{id:branch.id,title:branch.title,status:branch.status,context:`Branched from Accufy Version ${investigation.version}`} : undefined;}
function journeySource(label:string){if(/Everflow|Acquisition|Conversion/i.test(label))return "Everflow historical Evidence";if(/charge|OTO|Refund/i.test(label))return "Commas Transaction Evidence";if(/dispute/i.test(label))return "Resolution Center historical Evidence";return "Unavailable historically";}
function comparisonLabel(value:string){return ({"Main → OTO2 median":"Time from Main charge to OTO2","Three-charge Journey":"Three-charge Journey","Dominant sequence":"Most common Product sequence","Median total amount":"Median total charged","Any refund":"Any Refund","Any prior Order":"Buyer had a prior Order"} as Record<string,string>)[value]||value;}
function comparisonDefinition(value:string){return value.includes("median")||value==="Median total amount"?"Median for each cohort":value==="Dominant sequence"?"Share following Main → OTO1-gold → OTO2":undefined;}
function displayValue(value:string){return value.replace(/(\d+(?:\.\d+)?)m$/,"$1 min");}
function numericDifference(value:string){if(value==="Fragile"||value==="Small"||value==="Not material")return undefined;return value.replace(/pp$/,"percentage points").replace(/(\d+(?:\.\d+)?)m$/,"$1 min");}
function differenceExplanation(value:string){if(value==="Fragile"||value==="Small"||value==="Not material")return undefined;return value.startsWith("−")?"Affected is lower than control.":value.startsWith("+")?"Affected is higher than control.":undefined;}
function comparisonLimitation(metric:string,delta:string){if(metric==="Any refund")return "Too few Refunds to distinguish the cohorts reliably.";if(metric==="Any prior Order")return "Prior purchase history does not meaningfully distinguish the cohorts.";if(delta==="Fragile"||delta==="Small")return "The observed counts are insufficient for a reliable numeric difference.";return undefined;}
function plainFinding(value:string){return value.replace("No material speed difference.","No material difference in how quickly buyers reached the OTO2 charge.").replace("Amount distributions overlap; affected is not higher.","Amount distributions overlap; affected buyers do not spend more.");}
function comparisonSummary(investigation:Input){if(investigation.parent)return investigation.presentation.findings.find(item=>item.id==="journey-negative")?.statement||"Observable Journey structure does not clearly distinguish affected and control cohorts.";return investigation.presentation.findings.find(item=>item.id==="nandi-control")?.statement||"Current Evidence does not support a material cohort difference.";}
