"use client";

import { ArrowRight, CheckCircle2, ChevronDown, ExternalLink, Sparkles, X } from "lucide-react";
import Link from "next/link";
import * as React from "react";
import type { MissionItem } from "@/lib/concepts/mission-control-mock";

function Section({ title, children, open = true }: { title: string; children: React.ReactNode; open?: boolean }) {
  return <details open={open} className="border-b border-slate-200"><summary className="flex cursor-pointer list-none items-center justify-between px-5 py-3 text-[10px] font-semibold uppercase tracking-[.12em] text-slate-500">{title}<ChevronDown className="h-4 w-4" /></summary><div className="px-5 pb-5">{children}</div></details>;
}

export function MissionControlDrawer({ item, onClose }: { item: MissionItem; onClose: () => void }) {
  return <aside className="fixed inset-0 z-50 flex flex-col bg-white shadow-2xl xl:static xl:h-full xl:w-[400px] xl:shrink-0 xl:border-l xl:shadow-none" aria-label="Decision context drawer"><header className="flex h-16 shrink-0 items-center justify-between border-b px-5"><div><div className="text-[9px] font-semibold uppercase tracking-[.14em] text-slate-400">Decision Context</div><h2 className="mt-1 text-sm font-semibold">{item.business} · {item.title}</h2></div><button type="button" onClick={onClose} className="rounded-md border p-2" aria-label="Close drawer"><X className="h-4 w-4" /></button></header><div className="min-h-0 flex-1 overflow-y-auto"><Section title="Should I go somewhere?"><div className="rounded-xl border bg-slate-50 p-4"><div className="text-sm font-semibold">{item.question}</div><p className="mt-2 text-xs leading-5 text-slate-600">{item.explanation}</p></div></Section>{item.intelligence ? <Section title="TraceKit Intelligence"><div className="rounded-xl border border-violet-200 bg-violet-50/60 p-4"><div className="flex items-center gap-2 text-xs font-semibold"><Sparkles className="h-4 w-4" />Proactive observation</div><dl className="mt-3 space-y-3 text-xs"><div><dt className="text-[9px] uppercase text-slate-400">Fact</dt><dd className="mt-1">{item.intelligence.comparison}</dd></div><div><dt className="text-[9px] uppercase text-slate-400">Recommendation</dt><dd className="mt-1">{item.intelligence.recommendation}</dd></div><div><dt className="text-[9px] uppercase text-slate-400">Evidence strength</dt><dd className="mt-1 font-semibold">{item.intelligence.confidence}</dd></div></dl></div></Section> : null}<Section title="Supporting Evidence"><ul className="space-y-2">{item.evidence.map(evidence => <li key={evidence} className="flex items-start gap-2 rounded-lg border p-3 text-xs"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0" />{evidence}<ExternalLink className="ml-auto h-3.5 w-3.5 text-slate-400" /></li>)}</ul></Section><Section title="Explain"><p className="text-xs leading-5 text-slate-600">This summary helps decide whether to continue. Full explanation and investigation remain in the destination Workspace.</p></Section></div><footer className="border-t p-4"><Link href={item.route} className="flex w-full items-center justify-center gap-2 rounded-lg bg-slate-950 px-4 py-3 text-xs font-semibold text-white">{item.action} Workspace<ArrowRight className="h-4 w-4" /></Link></footer></aside>;
}
