import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { EVERFLOW_REPORT_HEADERS,parseEverflowHistoricalReport,type EverflowHistoricalEvent } from "../../api/src/connectors/everflow/historical-report";
import { SupabaseCommerceEvidenceStore } from "../lib/commerce/supabase-evidence-store-core";
type Row=Record<string,unknown>;
const FILE=process.env.EVERFLOW_REPORT_PATH!,VERSION="everflow-historical-v1",CHUNK=8*1024*1024;
if(!FILE)throw new Error("EVERFLOW_REPORT_PATH must reference the approved local report.");
const uuid=(ns:string,v:string)=>{const a=createHash("sha256").update(`${ns}\0${v}`).digest("hex").slice(0,32).split("");a[12]="5";a[16]=((parseInt(a[16],16)&3)|8).toString(16);const s=a.join("");return`${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`;};
function cfg(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Everflow import persistence unavailable.");return{url,key};}
async function db(path:string,init:RequestInit={}){const{url,key}=cfg();const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation",...init.headers}});const text=await response.text();if(!response.ok){let code="persistence_error";try{const parsed=JSON.parse(text)as{code?:string};code=parsed.code||code;}catch{}throw new Error(`Everflow import persistence failed (${response.status}, ${code}).`);}if(!text)return[]as Row[];const value=JSON.parse(text)as unknown;return(Array.isArray(value)?value:[value])as Row[];}
const eventRow=(e:EverflowHistoricalEvent,input:{id:string;accountId:string;organizationId:string;connectionId:string})=>({id:uuid("everflow-event",e.sourceIdentity),account_id:input.accountId,organization_id:input.organizationId,connection_id:input.connectionId,import_id:input.id,source_row:e.sourceRow,source_identity:e.sourceIdentity,conversion_id:e.conversionId,transaction_id:e.transactionId,email_normalized:e.emailNormalized,conversion_at:e.conversionAt,click_at:e.clickAt,delta_hours:e.deltaHours,affiliate_id:e.affiliateId,affiliate_name:e.affiliateName,sub1:e.sub1,sub2:e.sub2,sub3:e.sub3,sub4:e.sub4,sub5:e.sub5,offer_id:e.offerId,offer_name:e.offerName,event_name:e.eventName,revenue:e.revenue,sale_amount:e.saleAmount,session_ip_hash:e.sessionIpHash,conversion_ip_hash:e.conversionIpHash,isp:e.isp,country:e.country,region:e.region,city:e.city,device:e.device,browser:e.browser,platform:e.platform,os_version:e.osVersion,user_agent:e.userAgent,campaign_id:e.campaignId,campaign_name:e.campaignName,creative_id:e.creativeId,creative:e.creative,source_id:e.sourceId,status:e.status,attribution_method:e.attributionMethod});
async function main(){if(!process.argv.includes("--confirm-protected-import"))throw new Error("Everflow import requires explicit confirmation.");const bytes=new Uint8Array(await readFile(FILE));const reportHash=createHash("sha256").update(bytes).digest("hex");const connections=await db("commerce_provider_connections?provider=eq.commas&status=eq.connected&select=id,organization_id,account_id&limit=2");if(connections.length!==1)throw new Error("Everflow import requires the single verified Commerce scope.");const connectionId=String(connections[0].id),organizationId=String(connections[0].organization_id),accountId=String(connections[0].account_id),importId=uuid("everflow-import",reportHash);const accounts=await db(`commerce_provider_accounts?connection_id=eq.${connectionId}&organization_id=eq.${organizationId}&status=eq.active&select=id&limit=2`);if(accounts.length!==1)throw new Error("Everflow import requires one scoped Provider Account.");const providerAccountId=String(accounts[0].id);const priorRuns=await db(`commerce_sync_runs?connection_id=eq.${connectionId}&sync_type=eq.everflow_historical&mode=eq.historical_backfill&select=id&limit=1`);let runId=priorRuns[0]?.id?String(priorRuns[0].id):null;if(!runId){const created=await db("commerce_sync_runs",{method:"POST",body:JSON.stringify({organization_id:organizationId,connection_id:connectionId,provider_account_id:providerAccountId,sync_type:"everflow_historical",mode:"historical_backfill",metadata:{source:"protected_report"}})});runId=String(created[0].id);}const store=new SupabaseCommerceEvidenceStore();const evidenceIds:string[]=[];
 for(let offset=0,index=0;offset<bytes.length;offset+=CHUNK,index++){const payload=bytes.slice(offset,Math.min(offset+CHUNK,bytes.length));const hash=createHash("sha256").update(payload).digest("hex");const prior=await db(`commerce_evidence_records?organization_id=eq.${organizationId}&source_object_type=eq.everflow_report_chunk&payload_hash=eq.${hash}&deleted_at=is.null&select=id,storage_reference&limit=1`);let id=prior[0]?.id?String(prior[0].id):null;if(id){if(!await store.verifyHash({organizationId,storageReference:String(prior[0].storage_reference),payloadHash:hash}))throw new Error("Existing Everflow Evidence failed hash verification.");}else{const stored=await store.putImmutable({organizationId,connectionId,providerAccountId,sourceObjectType:"everflow_report_chunk",payload,contentType:"text/csv"});const created=await db("commerce_evidence_records",{method:"POST",body:JSON.stringify({organization_id:organizationId,connection_id:connectionId,provider_account_id:providerAccountId,sync_run_id:runId,source_object_type:"everflow_report_chunk",source_object_id:`${reportHash}:chunk:${index}`,payload_hash:stored.payloadHash,storage_backend:"object_storage",storage_reference:stored.storageReference,content_type:stored.contentType,byte_size:stored.byteSize,observed_at:new Date().toISOString(),normalizer_version:VERSION,mapping_version:VERSION,pii_classification:"restricted",retention_policy:"commerce-provider-raw-v1",metadata:{immutable:true,chunk_number:index}})});id=String(created[0].id);}evidenceIds.push(id);}
 await db("everflow_historical_imports?on_conflict=organization_id,report_hash",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({id:importId,account_id:accountId,organization_id:organizationId,connection_id:connectionId,report_hash:reportHash,source_label:"Everflow conversion report 2026-04-01 through 2026-08-07",period_start:"2026-04-01T00:00:00Z",period_end:"2026-08-08T00:20:53Z",row_count:69569,rejected_count:0,schema_columns:EVERFLOW_REPORT_HEADERS,normalizer_version:VERSION,metadata:{chunk_count:evidenceIds.length}})});
 for(let i=0;i<evidenceIds.length;i++)await db("everflow_import_evidence?on_conflict=import_id,chunk_number",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({import_id:importId,organization_id:organizationId,evidence_id:evidenceIds[i],chunk_number:i})});
 let batch:Row[]=[];const flush=async()=>{if(!batch.length)return;await db("everflow_conversion_events?on_conflict=import_id,source_identity",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(batch)});batch=[];};const summary=await parseEverflowHistoricalReport({filePath:FILE,reportHash,onEvent:async(e)=>{batch.push(eventRow(e,{id:importId,accountId,organizationId,connectionId}));if(batch.length>=250)await flush();}});await flush();if(summary.rows!==69569||summary.rejected!==0)throw new Error("Everflow import count differs from validated source.");const reconciliation=await db("rpc/reconcile_everflow_orders_v1",{method:"POST",body:JSON.stringify({p_organization_id:organizationId,p_connection_id:connectionId})});console.log(JSON.stringify({event:"everflow_import_completed",rows:summary.rows,rejected:summary.rejected,evidenceChunks:evidenceIds.length,reconciliation:reconciliation[0]}));}
void main();
