import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { parseResolutionCenterWorkbook, type HistoricalDisputeRow } from "../../api/src/connectors/commas/resolution-center-import";
import { SupabaseCommerceEvidenceStore } from "../lib/commerce/supabase-evidence-store-core";

type Row=Record<string,unknown>;
const WORKBOOK=process.env.COMMAS_DISPUTE_WORKBOOK_PATH;
const EXPECTED_ROWS=11_096;
const uuid=(namespace:string,value:string)=>{const h=createHash("sha256").update(`${namespace}\0${value}`).digest("hex").slice(0,32).split("");h[12]="5";h[16]=((parseInt(h[16],16)&3)|8).toString(16);const s=h.join("");return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`;};
function config(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Historical import persistence unavailable.");return{url,key};}
async function db(path:string,init:RequestInit={}){const{url,key}=config();const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation",...init.headers}});const text=await response.text();if(!response.ok)throw new Error(`Historical import persistence failed (${response.status}).`);if(!text)return[] as Row[];const value=JSON.parse(text) as unknown;return(Array.isArray(value)?value:[value]) as Row[];}

async function main(){
  if(!process.argv.includes("--confirm-historical-import"))throw new Error("Historical import requires explicit confirmation.");
  if(!WORKBOOK)throw new Error("COMMAS_DISPUTE_WORKBOOK_PATH must reference the approved local workbook.");
  const connections=await db("commerce_provider_connections?provider=eq.commas&status=eq.connected&select=id,organization_id,account_id&limit=2");if(connections.length!==1)throw new Error("Historical import requires one connected Commas Connection.");
  const connectionId=String(connections[0].id),organizationId=String(connections[0].organization_id),accountId=String(connections[0].account_id);
  const accounts=await db(`commerce_provider_accounts?connection_id=eq.${connectionId}&organization_id=eq.${organizationId}&status=eq.active&select=id&limit=2`);if(accounts.length!==1)throw new Error("Historical import requires one Provider Account.");const providerAccountId=String(accounts[0].id);
  const payload=new Uint8Array(await readFile(WORKBOOK));const store=new SupabaseCommerceEvidenceStore();const payloadHash=createHash("sha256").update(payload).digest("hex");const priorEvidence=await db(`commerce_evidence_records?organization_id=eq.${organizationId}&source_object_type=eq.historical_dispute_workbook&payload_hash=eq.${payloadHash}&deleted_at=is.null&select=id,storage_reference,content_type,byte_size&limit=1`);let evidenceId=priorEvidence[0]?.id as string|undefined;
  const stored=priorEvidence[0]?{storageReference:String(priorEvidence[0].storage_reference),payloadHash,contentType:String(priorEvidence[0].content_type),byteSize:Number(priorEvidence[0].byte_size)}:await store.putImmutable({organizationId,connectionId,providerAccountId,sourceObjectType:"historical_dispute_workbook",payload,contentType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});if(!await store.verifyHash({organizationId,storageReference:stored.storageReference,payloadHash:stored.payloadHash}))throw new Error("Workbook Evidence verification failed.");
  let run:Row;const existingRun=await db(`commerce_sync_runs?connection_id=eq.${connectionId}&sync_type=eq.historical_disputes&mode=eq.historical_backfill&select=*&order=created_at.desc&limit=1`);if(existingRun[0])run=existingRun[0];else [run]=await db("commerce_sync_runs",{method:"POST",body:JSON.stringify({organization_id:organizationId,connection_id:connectionId,provider_account_id:providerAccountId,sync_type:"historical_disputes",mode:"historical_backfill",metadata:{source:"resolution_center_export"}})});const runId=String(run.id);
  if(!evidenceId){const created=await db("commerce_evidence_records",{method:"POST",body:JSON.stringify({organization_id:organizationId,connection_id:connectionId,provider_account_id:providerAccountId,sync_run_id:runId,source_object_type:"historical_dispute_workbook",source_object_id:`workbook:${stored.payloadHash}`,payload_hash:stored.payloadHash,storage_backend:"object_storage",storage_reference:stored.storageReference,content_type:stored.contentType,byte_size:stored.byteSize,observed_at:new Date().toISOString(),normalizer_version:"resolution-center-v1",mapping_version:"historical-v1",pii_classification:"restricted",retention_policy:"commerce-provider-raw-v1",metadata:{immutable:true}})});evidenceId=String(created[0].id);}
  const rows:HistoricalDisputeRow[]=[];const summary=await parseResolutionCenterWorkbook({filePath:WORKBOOK,onAccepted:(row)=>{rows.push(row);}});if(summary.accepted!==EXPECTED_ROWS||summary.rejected!==0||summary.workbookHash!==stored.payloadHash)throw new Error("Historical workbook validation did not match the approved evidence.");
  const importId=uuid("commas-dispute-import",summary.workbookHash);await db("commerce_historical_dispute_imports?on_conflict=connection_id,provider_account_id,workbook_hash",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({id:importId,account_id:accountId,organization_id:organizationId,connection_id:connectionId,provider_account_id:providerAccountId,sync_run_id:runId,evidence_id:evidenceId,import_identity:`resolution-center:${summary.workbookHash}`,workbook_hash:summary.workbookHash,source_filename:"resolution_center_disputes.xlsx",accepted_rows:summary.accepted,rejected_rows:summary.rejected,metadata:{schema_version:"resolution-center-v1"}})});
  for(let offset=0;offset<rows.length;offset+=250){const batch=rows.slice(offset,offset+250).map((row)=>({id:uuid("commas-historical-dispute",row.sourceId),account_id:accountId,organization_id:organizationId,connection_id:connectionId,provider_account_id:providerAccountId,import_id:importId,evidence_id:evidenceId,source_row_identity:row.sourceId,source_row_number:row.rowNumber,state:row.state,status:row.status,transaction_date:row.transactionDate.slice(0,10),dispute_date:row.disputeDate.slice(0,10),closed_date:row.closedDate?.slice(0,10)??null,customer_email_normalized:row.normalizedEmail,product_evidence:row.product,amount:row.amount,dispute_fee:row.fee,payment_method:row.paymentMethod,reason:row.reason}));await db("commerce_historical_disputes?on_conflict=import_id,source_row_identity",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(batch)});}
  const result=await db("rpc/reconcile_commerce_historical_disputes_v1",{method:"POST",body:JSON.stringify({p_organization_id:organizationId,p_connection_id:connectionId})});
  await db(`commerce_sync_runs?id=eq.${runId}`,{method:"PATCH",body:JSON.stringify({status:"completed",started_at:run.started_at??new Date().toISOString(),completed_at:new Date().toISOString(),records_seen:summary.accepted,records_created:summary.accepted,metadata:{source:"resolution_center_export",algorithm_version:"historical-v1"}})});
  console.log(JSON.stringify({event:"historical_disputes_completed",runId,accepted:summary.accepted,rejected:summary.rejected,reconciliation:result[0]}));
}
void main();
