import { ACCUFY_INVESTIGATION_ID, ACCUFY_PRESENTATION, ACCUFY_RUN_ID, ACCUFY_VERSION_ID, ACCUFY_WARNINGS } from "../lib/investigations/accufy-reference";
import { assertClientSafePresentation } from "../lib/investigations/presentation";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "");
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) throw new Error("Local Supabase service configuration is required.");
const headers = { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json", Prefer: "return=representation" };
async function rest(path: string, init: RequestInit = {}) { const response = await fetch(`${url}/rest/v1/${path}`, { ...init, headers: { ...headers, ...init.headers } }); if (!response.ok) throw new Error(`Materialization failed (${response.status}).`); if (response.status === 204) return []; return response.json() as Promise<Array<Record<string, unknown>>>; }
async function main() {
assertClientSafePresentation(ACCUFY_PRESENTATION);
const organizations = await rest("tracekit_organizations?name=eq.Bullseye%20Health&limit=1");
if (!organizations[0]) throw new Error("Approved local Organization is unavailable.");
const organizationId = String(organizations[0].id), accountId = String(organizations[0].owning_account_id);
const connections = await rest(`commerce_provider_connections?organization_id=eq.${organizationId}&provider=eq.commas&order=created_at.asc&limit=1`);
if (!connections[0]) throw new Error("Verified Commas Connection is unavailable.");
const connectionId = String(connections[0].id);
await rest("tracekit_investigations?on_conflict=id", { method: "POST", headers: { Prefer: "resolution=merge-duplicates,return=representation" }, body: JSON.stringify({ id: ACCUFY_INVESTIGATION_ID, account_id: accountId, organization_id: organizationId, connection_id: connectionId, title: "Accufy Chargeback Investigation", question: ACCUFY_PRESENTATION.question, status: "completed_with_warnings", trigger_type: "chargeback_anomaly", period_start: "2025-09-20T21:00:34Z", period_end: "2026-08-08T04:47:51Z", maturity_days: 28, analysis_version: "accufy-investigation-v3", metadata: { materialization: "evidence_window_audited_reference_v3", causal_claim: false } }) });
await rest("tracekit_investigation_runs?on_conflict=id", { method: "POST", headers: { Prefer: "resolution=ignore-duplicates,return=representation" }, body: JSON.stringify({ id: ACCUFY_RUN_ID, account_id: accountId, organization_id: organizationId, investigation_id: ACCUFY_INVESTIGATION_ID, status: "completed_with_warnings", idempotency_key: "accufy-evidence-window-audit-v3", algorithm_version: "accufy-investigation-v3", commerce_reconciliation_version: "commerce-shadow-v1", journey_linkage_version: "everflow-commerce-v2", dispute_reconciliation_version: "historical-dispute-reconciliation-v1", reason_normalization_version: "dispute-reasons-v1", cohort_definition_version: "accufy-cohorts-v3-evidence-window", source_snapshot: { commerce_orders: 74493, commerce_period_start: "2025-09-20T21:00:34Z", commerce_period_end: "2026-08-08T04:47:51Z", attribution_eligible_orders: 50103, attribution_window_start: "2026-04-01T04:04:16Z", attribution_window_end: "2026-08-07T21:30:53Z", attributed_eligible_orders: 40228, disputes: 11096, everflow_events: 69569, everflow_journeys: 37829, evidence_summary: "Protected provider Evidence and historical imports; no raw Evidence in presentation" }, evidence_cutoff_at: "2026-08-08T05:11:32.490435Z", started_at: "2026-08-08T21:00:00Z", completed_at: "2026-08-08T21:00:00Z", records_evaluated: 155158, findings_produced: ACCUFY_PRESENTATION.findings.length, warnings: ACCUFY_WARNINGS }) });
await rest("tracekit_investigation_versions?on_conflict=run_id", { method: "POST", headers: { Prefer: "resolution=ignore-duplicates,return=representation" }, body: JSON.stringify({ id: ACCUFY_VERSION_ID, account_id: accountId, organization_id: organizationId, investigation_id: ACCUFY_INVESTIGATION_ID, run_id: ACCUFY_RUN_ID, version_number: 3, status: "completed_with_warnings", period_start: "2025-09-20T21:00:34Z", period_end: "2026-08-08T04:47:51Z", primary_signal: "OTO2-platinum — 24.73% historical dispute rate", evidence_quality: "medium", presentation: ACCUFY_PRESENTATION, published_at: "2026-08-08T21:00:00Z" }) });
await rest("tracekit_audit_events", { method: "POST", body: JSON.stringify({ actor_user_id: null, account_id: accountId, organization_id: organizationId, action: "investigation.run_completed", target_type: "tracekit_investigation_run", target_id: ACCUFY_RUN_ID, result: "success", correlation_id: "accufy-evidence-window-audit-v3", metadata: { algorithm_version: "accufy-investigation-v3", status: "completed_with_warnings", background_actor: "materialization_worker", methodology_change: "attribution_evidence_window_denominator" } }) });
console.log(JSON.stringify({ investigationId: ACCUFY_INVESTIGATION_ID, runId: ACCUFY_RUN_ID, status: "completed_with_warnings", version: 3 }));
}
main().catch((error)=>{console.error(error instanceof Error ? error.message : "Investigation materialization failed.");process.exitCode=1;});
