import { ACCUFY_INVESTIGATION_ID } from "../lib/investigations/accufy-reference";
import { assertClientSafePresentation } from "../lib/investigations/presentation";
import { OTO2_CHILD_INVESTIGATION_ID, OTO2_CHILD_PRESENTATION, OTO2_CHILD_RUN_ID, OTO2_CHILD_VERSION_ID, OTO2_CHILD_WARNINGS, OTO2_PARENT_VERSION_ID } from "../lib/investigations/oto2-selective-reference";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");
const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!key)throw new Error("Local Supabase service configuration is required.");
const headers={apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation"};
async function rest(path:string,init:RequestInit={}){const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{...headers,...init.headers}});if(!response.ok)throw new Error(`Child materialization failed (${response.status}).`);if(response.status===204)return [];return response.json() as Promise<Array<Record<string,unknown>>>;}

async function main(){
  assertClientSafePresentation(OTO2_CHILD_PRESENTATION);
  const parents=await rest(`tracekit_investigations?id=eq.${ACCUFY_INVESTIGATION_ID}&limit=1`);
  if(!parents[0])throw new Error("Approved parent Investigation is unavailable.");
  const organizationId=String(parents[0].organization_id),accountId=String(parents[0].account_id),connectionId=String(parents[0].connection_id);
  const parentVersions=await rest(`tracekit_investigation_versions?id=eq.${OTO2_PARENT_VERSION_ID}&investigation_id=eq.${ACCUFY_INVESTIGATION_ID}&version_number=eq.3&limit=1`);
  if(!parentVersions[0])throw new Error("Approved immutable parent Version 3 is unavailable.");
  const existing=await rest(`tracekit_investigations?id=eq.${OTO2_CHILD_INVESTIGATION_ID}&limit=1`);
  await rest("tracekit_investigations?on_conflict=id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({id:OTO2_CHILD_INVESTIGATION_ID,account_id:accountId,organization_id:organizationId,connection_id:connectionId,title:"OTO2 Selective Dispute Analysis",question:OTO2_CHILD_PRESENTATION.question,status:"completed_with_warnings",trigger_type:"investigation_branch",period_start:"2026-04-01T04:04:16Z",period_end:"2026-08-07T21:30:53Z",maturity_days:28,analysis_version:"oto2-selective-v1",parent_investigation_id:ACCUFY_INVESTIGATION_ID,parent_investigation_version_id:OTO2_PARENT_VERSION_ID,branch_signal:"OTO2-platinum has a 24.73% historical Commerce-level dispute rate.",branch_reason:"Determine what distinguishes selective OTO2 disputes from comparable Main + OTO2 Journeys with neither charge disputed.",metadata:{materialization:"reviewed_oto2_selective_v1",causal_claim:false,historical_evidence_ceiling:true}})});
  await rest("tracekit_investigation_runs?on_conflict=id",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=representation"},body:JSON.stringify({id:OTO2_CHILD_RUN_ID,account_id:accountId,organization_id:organizationId,investigation_id:OTO2_CHILD_INVESTIGATION_ID,status:"completed_with_warnings",idempotency_key:"oto2-selective-reviewed-v1-parent-v3",algorithm_version:"oto2-selective-v1",commerce_reconciliation_version:"commerce-shadow-v1",journey_linkage_version:"everflow-commerce-v2",dispute_reconciliation_version:"historical-dispute-reconciliation-v1",reason_normalization_version:"dispute-reasons-v1",cohort_definition_version:"oto2-selective-cohorts-v1",source_snapshot:{parent_investigation_id:ACCUFY_INVESTIGATION_ID,parent_version:3,linked_journeys:210,affected:12,control:156,both_disputed:40,main_only:2,evidence_summary:"Protected parent and child Evidence references; raw payloads excluded"},evidence_cutoff_at:"2026-08-08T05:11:32.490435Z",started_at:"2026-08-08T22:00:00Z",completed_at:"2026-08-08T22:00:00Z",records_evaluated:210,findings_produced:OTO2_CHILD_PRESENTATION.findings.length,warnings:OTO2_CHILD_WARNINGS})});
  await rest("tracekit_investigation_versions?on_conflict=run_id",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=representation"},body:JSON.stringify({id:OTO2_CHILD_VERSION_ID,account_id:accountId,organization_id:organizationId,investigation_id:OTO2_CHILD_INVESTIGATION_ID,run_id:OTO2_CHILD_RUN_ID,version_number:1,status:"completed_with_warnings",period_start:"2026-04-01T04:04:16Z",period_end:"2026-08-07T21:30:53Z",primary_signal:"Reason mix is the strongest limited differentiator",evidence_quality:"limited",presentation:OTO2_CHILD_PRESENTATION,published_at:"2026-08-08T22:00:00Z"})});
  if(!existing[0])await rest("tracekit_audit_events",{method:"POST",body:JSON.stringify({actor_user_id:null,account_id:accountId,organization_id:organizationId,action:"investigation.child_created",target_type:"tracekit_investigation",target_id:OTO2_CHILD_INVESTIGATION_ID,result:"success",correlation_id:"oto2-selective-reviewed-v1-parent-v3",metadata:{parent_investigation_id:ACCUFY_INVESTIGATION_ID,parent_version:3,child_investigation_id:OTO2_CHILD_INVESTIGATION_ID,algorithm_version:"oto2-selective-v1",background_actor:"materialization_worker"}})});
  console.log(JSON.stringify({investigationId:OTO2_CHILD_INVESTIGATION_ID,parentInvestigationId:ACCUFY_INVESTIGATION_ID,parentVersion:3,version:1,status:"completed_with_warnings",reused:Boolean(existing[0])}));
}
main().catch(error=>{console.error(error instanceof Error?error.message:"Child materialization failed.");process.exitCode=1;});
