import {resolveApplicationSession} from"@/lib/identity/application-session";
import {traceKitCoreAdminSecret} from"@/lib/core/admin-credential";
import {NextResponse} from"next/server";
export const runtime="nodejs";export const dynamic="force-dynamic";
function enabled(){return process.env.TRACEKIT_M13_READ_DIAGNOSTIC==="bounded-v1";}
function base(){return String(process.env.TRACEKIT_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE||"").trim().replace(/\/+$/,"");}
function failure(error:unknown){const e=error as{name?:unknown;cause?:{code?:unknown}}|null,code=String(e?.cause?.code||"").toUpperCase(),name=String(e?.name||"");if(["ENOTFOUND","EAI_AGAIN"].includes(code))return"dns_failed";if(code.startsWith("CERT_")||code.includes("TLS")||code.includes("SSL"))return"tls_failed";if(["ETIMEDOUT","UND_ERR_CONNECT_TIMEOUT","UND_ERR_HEADERS_TIMEOUT"].includes(code)||name==="TimeoutError")return"timeout";return"connection_failed";}
async function probe(origin:string){try{const res=await fetch(origin,{method:"GET",cache:"no-store",signal:AbortSignal.timeout(5000)});return{reachable:true,httpStatus:res.status};}catch(error:unknown){return{reachable:false,diagnostic:failure(error)};}}
async function probeCoreCustomers(origin:string,organizationId:string,secret:string){try{const u=new URL("/v1/customers",origin);u.searchParams.set("workspace_id",organizationId);u.searchParams.set("limit","1");const res=await fetch(u,{method:"GET",cache:"no-store",signal:AbortSignal.timeout(5000),headers:{accept:"application/json","x-tk-secret":secret}});return{reachable:true,httpStatus:res.status};}catch(error:unknown){return{reachable:false,diagnostic:failure(error)};}}
export async function GET(){if(!enabled())return NextResponse.json({ok:false,error:"not_found"},{status:404});const origin=base();if(!origin)return NextResponse.json({ok:false,diagnostic:"base_unavailable"},{status:200});let shape:{parseable:boolean;https?:boolean;canonicalHost?:boolean;hasPort?:boolean;hasPath?:boolean};try{const u=new URL(origin);shape={parseable:true,https:u.protocol==="https:",canonicalHost:u.hostname==="api.trace-kit.io",hasPort:Boolean(u.port),hasPath:u.pathname!=="/"&&u.pathname!==""};}catch{shape={parseable:false};}const[configured,control]=await Promise.all([probe(origin),probe("https://api.trace-kit.io")]);let coreCustomers:{attempted:boolean;reachable?:boolean;httpStatus?:number;diagnostic?:string}={attempted:false};const resolution=await resolveApplicationSession();if(resolution.kind==="authenticated"&&resolution.session.activeOrganization){let secret="";try{secret=traceKitCoreAdminSecret();}catch{coreCustomers={attempted:false,diagnostic:"credential_unavailable"};}if(secret){coreCustomers={attempted:true,...await probeCoreCustomers(origin,resolution.session.activeOrganization.id,secret)};}}return NextResponse.json({ok:true,shape,configured,control,coreCustomers},{status:200});}
