import Link from "next/link";
import { AlertTriangle, ArrowRight, Beaker, CheckCircle2, CircleDot, GitCompare, HelpCircle, Route, ShieldCheck, XCircle } from "lucide-react";
import type { FindingKind, SafeInvestigationDetail, SafeInvestigationSummary } from "@/lib/investigations/presentation";

const statusStyle: Record<string,string> = { completed:"border-emerald-400/25 bg-emerald-400/10 text-emerald-200", completed_with_warnings:"border-amber-400/25 bg-amber-400/10 text-amber-100", running:"border-cyan-400/25 bg-cyan-400/10 text-cyan-100", queued:"border-slate-400/20 bg-white/5 text-slate-300", failed:"border-rose-400/25 bg-rose-400/10 text-rose-200" };
const findingStyle: Record<FindingKind,{label:string;className:string;icon:React.ReactNode}> = {
  observation:{label:"Observation",className:"border-cyan-400/20 bg-cyan-400/[.055]",icon:<CircleDot className="h-4 w-4 text-cyan-300"/>},
  correlation:{label:"Correlation",className:"border-violet-400/20 bg-violet-400/[.055]",icon:<GitCompare className="h-4 w-4 text-violet-300"/>},
  negative_finding:{label:"Negative finding",className:"border-emerald-400/20 bg-emerald-400/[.055]",icon:<CheckCircle2 className="h-4 w-4 text-emerald-300"/>},
  hypothesis:{label:"Hypothesis",className:"border-amber-400/20 bg-amber-400/[.055]",icon:<Beaker className="h-4 w-4 text-amber-300"/>},
};
function Status({value}:{value:string}) { return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.12em] ${statusStyle[value]||statusStyle.queued}`}>{value.replaceAll("_"," ")}</span>; }
function Frame({children}:{children:React.ReactNode}) { return <div className="min-h-full bg-[#080a0f] text-slate-100"><div className="mx-auto max-w-[1380px] px-5 py-9 sm:px-8 lg:px-10">{children}</div></div>; }
function Section({id,title,description,children}:{id?:string;title:string;description?:string;children:React.ReactNode}) { return <section id={id} className="border-t border-white/10 py-10"><div className="grid gap-7 lg:grid-cols-[260px_1fr]"><header><h2 className="text-lg font-semibold tracking-tight">{title}</h2>{description?<p className="mt-2 text-xs leading-5 text-slate-500">{description}</p>:null}</header><div>{children}</div></div></section>; }

export function InvestigationIndex({investigations}:{investigations:SafeInvestigationSummary[]}) {
  return <Frame><header className="border-b border-white/10 pb-8"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-300">Product intelligence</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Investigations</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Evidence-backed analysis of outcomes, the Journeys that produced them, and the controls needed to interpret them.</p></header>{investigations.length?<div className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[.03]"><div className="grid grid-cols-[1.5fr_.75fr_.8fr_.7fr] gap-4 border-b border-white/10 px-5 py-3 text-[10px] uppercase tracking-widest text-slate-500"><span>Investigation</span><span>Status</span><span>Evidence</span><span>Updated</span></div>{investigations.map(item=><Link key={item.id} href={`/investigations/${item.id}`} className="grid grid-cols-[1.5fr_.75fr_.8fr_.7fr] gap-4 px-5 py-5 transition hover:bg-white/[.04]"><div><strong className="text-sm">{item.title}</strong><p className="mt-1 text-xs text-slate-500">{item.organization} · {item.period}</p><p className="mt-3 text-xs text-cyan-200">{item.primarySignal}</p></div><div><Status value={item.status}/></div><div className="text-xs capitalize text-slate-300">{item.evidenceQuality}<p className="mt-1 text-[10px] text-slate-600">Version {item.version}</p></div><div className="flex items-start justify-between text-xs text-slate-500"><span>{formatDate(item.lastUpdated)}</span><ArrowRight className="h-4 w-4"/></div></Link>)}</div>:<div className="mt-8 rounded-2xl border border-dashed border-white/15 p-12 text-center"><h2 className="font-semibold">No Investigations available</h2><p className="mt-2 text-xs text-slate-500">Completed and authorized Investigation versions appear here.</p></div>}</Frame>;
}

export function InvestigationAccessRequired() { return <Frame><div className="flex min-h-[65vh] items-center justify-center"><section className="max-w-lg rounded-2xl border border-white/10 bg-white/[.03] p-8 text-center"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl border border-white/10 bg-white/[.05]"><ShieldCheck className="h-5 w-5 text-slate-300"/></div><p className="mt-5 text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Product intelligence</p><h1 className="mt-3 text-2xl font-semibold">Product/Admin access required</h1><p className="mt-3 text-sm leading-6 text-slate-400">Investigations are available only to authorized TraceKit Product/Admin reviewers. Your current Organization access remains unchanged.</p><Link href="/" className="mt-6 inline-flex rounded-lg border border-white/10 px-4 py-2 text-xs font-semibold text-slate-200 hover:bg-white/5">Return to Mission Control</Link></section></div></Frame>; }

export function InvestigationDetail({investigation}:{investigation:SafeInvestigationDetail}) { const p=investigation.presentation; return <Frame>
  <header className="mt-6 border-b border-white/10 pb-9"><div className="flex flex-wrap items-center gap-3"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-300">Chargeback Investigation</p><Status value={investigation.status}/></div><h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">{p.question}</h1><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span>{investigation.organization}</span><span>{p.period}</span><span>Version {investigation.version}</span><span>Analyzed {formatDate(investigation.lastUpdated)}</span></div></header>
  <section className="py-9"><div className="grid gap-5 lg:grid-cols-[1fr_340px]"><article className="rounded-2xl border border-cyan-400/20 bg-gradient-to-br from-cyan-400/[.08] to-white/[.025] p-6"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">Executive finding</p><p className="mt-4 text-xl font-medium leading-8 tracking-[-.02em]">{p.executiveFinding}</p><p className="mt-5 text-xs text-slate-500">TraceKit identified the strongest current signals. This is not a causal claim.</p></article><aside className="rounded-2xl border border-amber-400/20 bg-amber-400/[.05] p-5"><div className="flex items-center gap-2 text-sm font-semibold text-amber-100"><AlertTriangle className="h-4 w-4"/>Completed with warnings</div><ul className="mt-4 space-y-3 text-xs leading-5 text-slate-400">{investigation.warnings.map(w=><li key={w.code}>{w.message}</li>)}</ul></aside></div></section>
  <Section title="Evidence Quality" description="Coverage differs by source and question; TraceKit does not collapse it into one confidence score."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{p.evidenceQuality.map(m=><div key={m.label} className="rounded-xl border border-white/10 bg-white/[.03] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">{m.label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{m.value}</p>{m.detail?<p className="mt-2 text-xs text-slate-500">{m.detail}</p>:null}{m.warning?<p className="mt-2 text-xs text-amber-200">{m.warning}</p>:null}</div>)}</div></Section>
  <Section title="What happened" description="Historical outcomes and lag, with acquisition-cohort maturity kept explicit."><div className="rounded-xl border border-amber-400/20 bg-amber-400/[.04] p-4 text-xs leading-5 text-amber-100">{p.outcome.maturityWarning}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{p.outcome.metrics.map(m=><Metric key={m.label} label={m.label} value={m.value}/>)}</div><div className="mt-5 grid gap-2 sm:grid-cols-2">{p.outcome.statuses.map(s=><div key={s.label} className="flex items-center justify-between rounded-lg border border-white/10 px-4 py-3 text-sm"><span>{s.label}</span><span className="tabular-nums text-slate-400">{s.count.toLocaleString()} · {s.percent}</span></div>)}</div></Section>
  <Section title="Where it is concentrated" description="Rates, burdens, and sample sizes are shown separately."><div className="space-y-3">{p.concentration.map(c=><article key={c.subject} className="grid gap-3 rounded-xl border border-white/10 bg-white/[.025] p-4 md:grid-cols-[180px_190px_1fr]"><strong>{c.subject}</strong><div><p className="text-sm text-cyan-200">{c.signal}</p><p className="mt-1 text-[10px] text-slate-600">{c.sample}</p></div><div><p className="text-xs leading-5 text-slate-400">{c.interpretation}</p>{c.warning?<p className="mt-2 text-xs text-amber-200">{c.warning}</p>:null}</div></article>)}</div></Section>
  <Section title="Journey" description="Every outcome is examined through the partial Journey that produced it."><div className="overflow-x-auto pb-2"><div className="flex min-w-[950px] items-stretch">{p.journey.map((step,index)=><div key={step.label} className="flex flex-1 items-center"><div className={`h-full min-h-36 flex-1 rounded-xl border p-4 ${step.state==="observed"?"border-emerald-400/25 bg-emerald-400/[.05]":step.state==="propagated"?"border-violet-400/25 bg-violet-400/[.05]":"border-dashed border-slate-500/30 bg-white/[.02]"}`}><span className="text-[9px] font-semibold uppercase tracking-wider text-slate-500">{step.state}</span><h3 className="mt-3 text-sm font-semibold">{step.label}</h3><p className="mt-2 text-[11px] leading-5 text-slate-500">{step.detail}</p></div>{index<p.journey.length-1?<ArrowRight className="mx-2 h-4 w-4 shrink-0 text-slate-700"/>:null}</div>)}</div></div>{p.multiCharge.length?<div className="mt-6 rounded-xl border border-violet-400/20 bg-violet-400/[.04] p-5"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-violet-200"><GitCompare className="h-4 w-4"/>Correlation</div><div className="mt-4 grid grid-cols-3 gap-3">{p.multiCharge.map(item=><Metric key={item.charges} label={item.charges} value={item.rate}/>)}</div><p className="mt-4 text-xs leading-5 text-slate-400">Product mix, affiliate mix, customer intent, funnel selection, or offer structure may confound this relationship. Multiple charges are not presented as a cause.</p></div>:null}</Section>
  <Section title="Cohort vs Control" description="Affected and comparable control cohorts are shown with deltas and Evidence limitations."><div className="overflow-hidden rounded-xl border border-white/10"><div className="grid grid-cols-[1.2fr_.8fr_.8fr_.65fr_1.4fr] gap-3 border-b border-white/10 px-4 py-3 text-[10px] uppercase tracking-wider text-slate-500"><span>Metric</span><span>Affected</span><span>Control</span><span>Delta</span><span>Finding</span></div>{p.comparison.map(row=><div key={row.metric} className="grid grid-cols-[1.2fr_.8fr_.8fr_.65fr_1.4fr] gap-3 border-b border-white/10 px-4 py-4 text-xs last:border-0"><strong>{row.metric}</strong><span>{row.subject}</span><span>{row.control}</span><span className="text-cyan-200">{row.delta}</span><span className="text-slate-400">{row.finding}</span></div>)}</div></Section>
  <Section title="Findings" description="Observations, correlations, negative findings, and hypotheses remain distinct."><div className="grid gap-3 lg:grid-cols-2">{p.findings.map(f=>{const style=findingStyle[f.kind];return <article key={f.id} className={`rounded-xl border p-5 ${style.className}`}><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider">{style.icon}{style.label}</div><h3 className="mt-4 font-semibold">{f.title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{f.statement}</p><dl className="mt-4 grid grid-cols-2 gap-2 text-[10px] text-slate-500"><div>Sample<br/><span className="text-slate-300">{f.sample||"Evidence subset"}</span></div><div>Control<br/><span className="text-slate-300">{f.control||"Not applicable"}</span></div><div>Quality<br/><span className="text-slate-300">{f.quality}</span></div><div>Provenance<br/><span className="text-slate-300">{f.provenance.replaceAll("_"," ")}</span></div></dl></article>})}</div></Section>
  <Section title="Hypotheses weakened or eliminated" description="Negative results remove plausible explanations and narrow the next investigation."><div className="grid gap-3 md:grid-cols-2">{p.weakenedHypotheses.map(h=><div key={h.hypothesis} className="rounded-xl border border-emerald-400/20 bg-emerald-400/[.04] p-4"><div className="flex gap-3"><XCircle className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300"/><div><h3 className="text-sm font-semibold">{h.hypothesis}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{h.evidence}</p></div></div></div>)}</div></Section>
  <Section title="Current hypotheses" description="Remaining explanations require more evidence; no probability or causal certainty is implied.">{p.currentHypotheses.map(h=><article key={h.hypothesis} className="rounded-xl border border-amber-400/20 bg-amber-400/[.04] p-5"><div className="flex items-center gap-2 text-sm font-semibold"><Beaker className="h-4 w-4 text-amber-300"/>{h.hypothesis}</div><div className="mt-5 grid gap-4 md:grid-cols-3"><EvidenceBlock label="Evidence for" text={h.for}/><EvidenceBlock label="Evidence against" text={h.against}/><EvidenceBlock label="Evidence missing" text={h.missing}/></div><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-amber-200">{h.status}</p></article>)}</Section>
  <Section title="Evidence gaps" description="Historical upstream data cannot answer these questions; uncertainty remains visible."><div className="grid gap-2 sm:grid-cols-2">{p.evidenceGaps.map(g=><div key={g} className="flex gap-3 rounded-lg border border-dashed border-white/15 p-3 text-xs text-slate-400"><HelpCircle className="h-4 w-4 shrink-0 text-slate-600"/>{g}</div>)}</div></Section>
  <Section title="Next questions" description="Deterministic next steps derived from unresolved findings, not automated operational decisions."><ol className="space-y-3">{p.nextQuestions.map((q,i)=><li key={q} className="flex gap-4 rounded-xl border border-white/10 bg-white/[.025] p-4"><span className="font-mono text-xs text-cyan-300">{String(i+1).padStart(2,"0")}</span><span className="text-sm">{q}</span></li>)}</ol></Section>
  <Section title="Methodology & provenance" description="Safe aggregate provenance only; no raw Evidence, PII, or storage references."><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-white/10 p-5"><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck className="h-4 w-4"/>Provenance</div><dl className="mt-4 space-y-3 text-xs"><Row label="Sources" value={p.provenance.sources.join(" · ")}/><Row label="Evidence" value={p.provenance.evidenceRecords}/><Row label="Dispute rule" value={p.provenance.disputeRule}/><Row label="Journey rule" value={p.provenance.journeyRule}/><Row label="Algorithm" value={investigation.versions.algorithm}/></dl><div className="mt-4 flex flex-wrap gap-2">{p.provenance.attribution.map(a=><span key={a.label} className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] text-slate-400">{a.label}: {a.count}</span>)}</div></div><details className="rounded-xl border border-white/10 p-5"><summary className="cursor-pointer text-sm font-semibold">How TraceKit reached these findings</summary><ol className="mt-4 space-y-3 text-xs leading-5 text-slate-400">{p.methodology.map((m,i)=><li key={m}><span className="mr-2 text-slate-600">{i+1}.</span>{m}</li>)}</ol></details></div></Section>
  <footer className="border-t border-white/10 py-8 text-xs text-slate-600">Investigation {investigation.id.slice(0,8)} · Run {investigation.runId.slice(0,8)} · No dispute operation was performed.</footer>
  </Frame>; }

function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-xl border border-white/10 bg-white/[.025] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums">{value}</p></div>; }
function EvidenceBlock({label,text}:{label:string;text:string}) { return <div><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-xs leading-5 text-slate-300">{text}</p></div>; }
function Row({label,value}:{label:string;value:string}) { return <div className="flex justify-between gap-4"><dt className="text-slate-500">{label}</dt><dd className="max-w-[70%] text-right text-slate-300">{value}</dd></div>; }
function formatDate(value:string) { return new Intl.DateTimeFormat("en",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(value)); }
