export type EdgeIntelligenceV1Validation={ok:true;value:Record<string,any>}|{ok:false;errors:Array<{path:string;code:string}>};
const opaque=/^(obs|tenant|session|event)_[A-Za-z0-9_-]{8,128}$/;
const iso=(v:unknown)=>typeof v==="string"&&Number.isFinite(Date.parse(v))&&v.includes("T");
const forbidden=new Set(["ip","rawIp","encryptedIp","ciphertext","vaultRef","protectedIpRef","networkObservationKey","networkDigest","r2Key","storageKey","cacheKey","queuePayload","rawProviderResponse","rawFingerprint","jobId","internalId","providerObservationId","sessionAssociationKey","freshnessEpoch","datasetPath","email","phone","customerName","fullName","postalAddress","paymentData","destination","redirect","redirectUrl","moneyPage","safePage","route","routingDecision","policyDecision","allow","block","challenge","offer","landingPage","campaignDestination","decisionDestination"]);
const statuses=new Set(["COMPLETE","PARTIAL","OWNED_ONLY","PROVIDER_UNAVAILABLE","EXPIRED","UNKNOWN"]),stages=new Set(["OWNED","NETWORK_LOCAL","NETWORK_LIVE","BROWSER","AUTOMATION","BEHAVIORAL","DERIVATION","UNKNOWN"]),freshnesses=new Set(["CURRENT","AGING","STALE","UNKNOWN"]),sources=new Set(["OWNED_AUTHORITATIVE","OWNED_OBSERVATION","LOCAL_SNAPSHOT","LOCAL_STALE","LIVE_PROVIDER","DERIVED","UNKNOWN"]);
export function validateEdgeIntelligenceV1(payload:unknown,expected?:{tenantRef?:string}):EdgeIntelligenceV1Validation{
 const errors:Array<{path:string;code:string}>=[],bad=(path:string,code:string)=>errors.push({path,code});
 if(!payload||typeof payload!=="object"||Array.isArray(payload))return{ok:false,errors:[{path:"$",code:"TYPE"}]};const v=payload as Record<string,any>;
 const walk=(x:unknown,p:string)=>{if(!x||typeof x!=="object")return;if(Array.isArray(x)){x.forEach((e,i)=>walk(e,p+"["+i+"]"));return;}for(const[k,e]of Object.entries(x as Record<string,unknown>)){if(forbidden.has(k))bad(p+"."+k,"FORBIDDEN_FIELD");walk(e,p+"."+k);}};walk(v,"$");
 if(v.schemaVersion!=="1.0")bad("$.schemaVersion","SCHEMA_VERSION");for(const k of["observationId","tenantRef","sessionRef"]){if(typeof v[k]!=="string"||!opaque.test(v[k]))bad("$."+k,"IDENTITY");}if(v.eventRef!==undefined&&(typeof v.eventRef!=="string"||!opaque.test(v.eventRef)))bad("$.eventRef","IDENTITY");if(expected?.tenantRef&&v.tenantRef!==expected.tenantRef)bad("$.tenantRef","TENANT_MISMATCH");
 if(typeof v.semanticsVersion!=="string"||!v.semanticsVersion||typeof v.derivationRuleVersion!=="string"||!v.derivationRuleVersion)bad("$","SEMANTICS");if(!Number.isInteger(v.revision)||v.revision<1)bad("$.revision","REVISION");if((v.revision===1&&v.previousRevision!==undefined)||(v.revision>1&&v.previousRevision!==v.revision-1))bad("$.previousRevision","REVISION_CHAIN");
 for(const k of["observedAt","updatedAt"]){if(!iso(v[k]))bad("$."+k,"TIMESTAMP");}if(v.completedAt!==undefined&&!iso(v.completedAt))bad("$.completedAt","TIMESTAMP");if(!statuses.has(v.status))bad("$.status","STATUS");
 for(const k of["completedStages","pendingStages"]){if(!Array.isArray(v[k]))bad("$."+k,"STAGES");else{const seen=new Set;for(const s of v[k]){if(!stages.has(s))bad("$."+k,"STAGE");if(seen.has(s))bad("$."+k,"DUPLICATE_STAGE");seen.add(s);}}}
 if(!v.intelligence||typeof v.intelligence!=="object"||Array.isArray(v.intelligence))bad("$.intelligence","INTELLIGENCE");for(const k of["evidence","conflicts","explanations","errors"])if(!Array.isArray(v[k]))bad("$."+k,"ARRAY");
 const ids=new Set<string>();for(const [i,e] of (Array.isArray(v.evidence)?v.evidence:[]).entries()){if(!e||typeof e.id!=="string"||ids.has(e.id))bad("$.evidence["+i+"].id","EVIDENCE_ID");else ids.add(e.id);if(!sources.has(e?.sourceClass))bad("$.evidence["+i+"].sourceClass","SOURCE_CLASS");if(!freshnesses.has(e?.freshness))bad("$.evidence["+i+"].freshness","FRESHNESS");if(typeof e?.provider!=="string"||!e.provider)bad("$.evidence["+i+"].provider","PROVIDER");if(!iso(e?.observedAt))bad("$.evidence["+i+"].observedAt","TIMESTAMP");}
 const text=JSON.stringify(v);if(/\b(?:\d{1,3}\.){3}\d{1,3}\b/.test(text))bad("$","RAW_IPV4");if(/(?:[0-9a-f]{1,4}:){4,}[0-9a-f:]{1,}/i.test(text))bad("$","RAW_IPV6");if(/ipref:|m25\/(?:vault|provider-observations|derived|jobs)\//i.test(text))bad("$","INTERNAL_REFERENCE");if(/SPUR_TOKEN|BEGIN PRIVATE KEY|sk_live_/i.test(text))bad("$","CREDENTIAL");
 const network=v.intelligence?.network;if(network&&typeof network==="object")for(const[field,a]of Object.entries(network)){if(field==="serviceOperators")continue;const x=a as any;if(!["TRUE","FALSE","UNKNOWN","KNOWN"].includes(x?.state))bad("$.intelligence.network."+field+".state","STATE");if(!freshnesses.has(x?.freshness))bad("$.intelligence.network."+field+".freshness","FRESHNESS");for(const ref of x?.evidenceRefs??[])if(!ids.has(ref))bad("$.intelligence.network."+field+".evidenceRefs","BROKEN_EVIDENCE_REF");}
 return errors.length?{ok:false,errors}:{ok:true,value:v};
}
