import{randomUUID}from"node:crypto";import{NextResponse}from"next/server";import{resolveApplicationSession}from"@/lib/identity/application-session";import{requirePermission,AuthorizationDeniedError}from"@/lib/identity/authorization-gateway";import{createCommerceControlPlane}from"@/lib/commerce/server-control-plane";import{MemoryCommerceEvidenceStore}from"@/lib/commerce/evidence-store";import{CommerceProviderConnectionVerifier}from"@/lib/commerce/provider-verifier";import{parseShopifyConnectionCredential}from"@/lib/commerce/shopify-verifier";import{createTraceKitShopifyWebhookSubscription,deleteTraceKitShopifyWebhookSubscription}from"@/lib/commerce/shopify-webhook-registration";
const CONTROLLED_DOMAIN="izkfvg-k0.myshopify.com",CONTROLLED_CONNECTION="ed3bb791-4cc2-4624-a887-3a6518018316",TOPIC="ORDERS_CREATE" as const;
function sameOrigin(r:Request){const o=r.headers.get("origin"),s=r.headers.get("sec-fetch-site");return(!o||o===new URL(r.url).origin)&&(!s||s==="same-origin");}
function out(b:Record<string,unknown>,s=200){return NextResponse.json(b,{status:s});}
export async function POST(request:Request){try{if(!sameOrigin(request))return out({ok:false,code:"request_verification_failed"},403);const resolution=await resolveApplicationSession();if(resolution.kind!=="authenticated"||!resolution.session.activeOrganization)return out({ok:false,code:"resource_unavailable"},404);requirePermission(resolution.session,"actions.execute");const body=await request.json().catch(()=>({})) as Record<string,unknown>;if(body.confirm!==true||body.connectionId!==CONTROLLED_CONNECTION||body.shopDomain!==CONTROLLED_DOMAIN)return out({ok:false,code:"controlled_target_confirmation_required"},400);
 const plane=createCommerceControlPlane({evidenceStore:new MemoryCommerceEvidenceStore(),verifier:new CommerceProviderConnectionVerifier()}),connection=await plane.getConnection(resolution.session,CONTROLLED_CONNECTION);if(connection.provider!=="shopify")return out({ok:false,code:"resource_unavailable"},404);const credential=parseShopifyConnectionCredential(await plane.resolveCredentialForExecution(resolution.session,CONTROLLED_CONNECTION));if(credential.shopDomain!==CONTROLLED_DOMAIN)return out({ok:false,code:"controlled_target_mismatch"},409);
 const callbackUrl=`${new URL(request.url).origin}/api/webhooks/shopify`,auditCorrelationId=resolution.session.correlationId,idempotencyKey=randomUUID();
 const created=await createTraceKitShopifyWebhookSubscription({credential,callbackUrl,topic:TOPIC});if(created.decision!=="created")return out({ok:false,code:"controlled_topic_already_exists",topic:TOPIC,providerMutation:false},409);
 const rollback=await deleteTraceKitShopifyWebhookSubscription({credential,subscription:created.subscription,callbackUrl});
 return out({ok:rollback.verifiedAbsent,provider:"shopify",operation:"controlled_webhook_create_delete_proof",shopDomain:CONTROLLED_DOMAIN,topic:TOPIC,createdSubscriptionId:created.subscription.id,verifiedPresent:created.verifiedPresent,rollback:{deletedSubscriptionId:rollback.deletedSubscriptionId,verifiedAbsent:rollback.verifiedAbsent},audit:{auditCorrelationId,idempotencyKey},netProviderConfigurationMutation:rollback.verifiedAbsent?false:true},rollback.verifiedAbsent?200:502);
 }catch(e){if(e instanceof AuthorizationDeniedError)return out({ok:false,code:"resource_unavailable"},404);return out({ok:false,code:"shopify_controlled_mutation_proof_failed"},500);}}
