"use client";
import * as React from "react";
import { Card } from "@/components/ui/card";

type Account={id:string;externalId:string;label:string|null;currency:string|null;timezoneName:string|null;status:string;eligibleForSpendSync:boolean;selectedForSync:boolean};
type Connection={connectionId:string;displayName:string;status:string;reauthorizationRequired:boolean;connected:boolean;accountCount:number;selectedAccountCount:number;accounts:Account[]};

export function TikTokAdsIntegrationPanel(){
 const [connections,setConnections]=React.useState<Connection[]>([]),[message,setMessage]=React.useState(""),[busy,setBusy]=React.useState<string|null>(null),[dates,setDates]=React.useState<Record<string,{since:string;until:string}>>({});
 const load=React.useCallback(async()=>{try{const r=await fetch("/v1/integrations/tiktok/status",{cache:"no-store",credentials:"same-origin"});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.message);setConnections(x.connections||[]);}catch(e:any){setMessage(e?.message||"TikTok Ads state unavailable.");}},[]);
 React.useEffect(()=>{void load();},[load]);
 React.useEffect(()=>{const p=new URLSearchParams(window.location.search),v=p.get("tiktok");if(v==="connected")setMessage(`TikTok connected. ${p.get("accounts")||"0"} advertiser(s) discovered.`);else if(v==="configuration")setMessage("TikTok live connection is waiting for developer-app configuration.");else if(v==="cancelled")setMessage("TikTok authorization was cancelled.");else if(v==="state"||v==="failed")setMessage("TikTok authorization could not be completed.");},[]);
 async function save(c:Connection,next:Set<string>){setBusy(c.connectionId);try{const r=await fetch("/v1/integrations/tiktok/accounts",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId:c.connectionId,accountIds:Array.from(next)})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.message);setMessage(`${x.selectedAccountCount||0} TikTok advertiser(s) selected. Automatic scheduling remains off.`);await load();}catch(e:any){setMessage(e?.message||"TikTok account selection failed.");}finally{setBusy(null);}}
 async function run(c:Connection,a:Account){const d=dates[a.id]||{};if(!d.since||!d.until){setMessage("Choose both Run Now dates.");return;}setBusy(a.id);try{const r=await fetch("/v1/integrations/tiktok/run-now",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId:c.connectionId,providerAccountId:a.id,since:d.since,until:d.until})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.message);setMessage(`TikTok Run Now completed: ${x.seen||0} row(s) seen, ${x.costsCreated||0} spend cost(s) created, ${x.costsUpdated||0} updated.`);}catch(e:any){setMessage(e?.message||"TikTok Run Now failed safely.");}finally{setBusy(null);}}
 return <div className="space-y-6">
  <Card title="TikTok Ads" right={<button type="button" disabled className="rounded-md border px-3 py-2 text-sm opacity-50">Connect TikTok</button>}>
   <p className="text-sm text-gray-600 dark:text-gray-300">Connect advertisers, choose spend-sync targets, and run bounded manual reporting imports.</p>
   <p className="mt-2 text-xs font-medium text-amber-700 dark:text-amber-300">Live TikTok developer-app access is not currently available. OAuth certification and automatic scheduling remain blocked.</p>
  </Card>
  {message?<div className="rounded-md border p-3 text-sm">{message}</div>:null}
  {!connections.length?<Card title="Connections"><p className="text-sm text-gray-600 dark:text-gray-300">No live TikTok connection is configured. The connector is fixture-certified through manual spend sync and is waiting for TikTok developer-app access for live certification.</p></Card>:connections.map(c=><Card key={c.connectionId} title={c.displayName} right={<span className="rounded-full bg-gray-100 px-2 py-1 text-xs">{c.status}</span>}>
   <div className="space-y-3">{c.accounts.map(a=>{const selected=new Set(c.accounts.filter(x=>x.selectedForSync).map(x=>x.id));return <div key={a.id} className="rounded-md border p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><label className="flex items-center gap-2 font-medium"><input type="checkbox" checked={a.selectedForSync} disabled={busy===c.connectionId||!a.eligibleForSpendSync} onChange={e=>{const next=new Set(selected);e.target.checked?next.add(a.id):next.delete(a.id);void save(c,next);}}/>{a.label||a.externalId}</label><div className="mt-1 text-xs text-gray-500">ID {a.externalId} · {a.currency||"currency unknown"} · {a.timezoneName||"timezone unknown"}</div></div>{a.selectedForSync?<div className="flex gap-2"><input type="date" aria-label="Sync from" value={dates[a.id]?.since||""} onChange={e=>setDates(v=>({...v,[a.id]:{since:e.target.value,until:v[a.id]?.until||""}}))}/><input type="date" aria-label="Sync through" value={dates[a.id]?.until||""} onChange={e=>setDates(v=>({...v,[a.id]:{since:v[a.id]?.since||"",until:e.target.value}}))}/><button type="button" disabled={busy===a.id} onClick={()=>void run(c,a)} className="rounded-md border px-3 py-1.5 text-sm">Run Now</button></div>:null}</div></div>})}</div>
  </Card>)}
  <Card title="Certification status"><div className="space-y-2 text-sm"><div><strong>Fixture certification:</strong> Passed through controlled manual spend sync.</div><div><strong>Live certification:</strong> Blocked — TikTok developer-app access required.</div><div><strong>Automatic scheduling:</strong> Disabled and not eligible until live certification passes.</div></div></Card>
 </div>;
}
