import assert from"node:assert/strict";import test from"node:test";import{consumeCommerceMessage,runCommerceCron,validateCommerceQueueMessage,type CommerceQueueMessage}from"./continuous-commerce-cloudflare.ts";
const id="11111111-1111-4111-8111-111111111111",message:CommerceQueueMessage={schema_version:1,job_type:"commerce_continuous",connection_id:id,resource:"transactions",requested_mode:"continuous",scheduler_identity:"schedule:bucket",requested_at:"2026-08-10T00:00:00Z"};
function repo(overrides:any={}){const metrics:any[]=[];return{metrics,schedulerEnabled:async()=>true,eligibleJobs:async()=>[{connectionId:id,resource:"transactions",mode:"continuous",schedulerIdentity:"schedule:bucket",quotaRemaining:9000,requestBudget:8,quotaFloor:1000}],connectionPermitted:async()=>true,reserve:async()=>"reserved" as const,recordMetric:async(event:string,details:any)=>{metrics.push({event,details})},...overrides}}
test("queue message is versioned and contains no credentials, PII, or payload",()=>{assert.deepEqual(validateCommerceQueueMessage(message),message);assert.throws(()=>validateCommerceQueueMessage({...message,api_key:"secret"}));assert.doesNotMatch(JSON.stringify(message),/credential|secret|email|payload|evidence/i)});
test("cron disabled enqueues nothing",async()=>{let sent=0;const result=await runCommerceCron({now:message.requested_at,repository:repo({schedulerEnabled:async()=>false}),queue:{send:async()=>{sent++}}});assert.equal(sent,0);assert.equal(result.enqueued,0)});
test("cron honors pause, quota, and eligibility",async()=>{let sent=0;assert.equal((await runCommerceCron({now:message.requested_at,repository:repo({connectionPermitted:async()=>false}),queue:{send:async()=>{sent++}}})).enqueued,0);assert.equal((await runCommerceCron({now:message.requested_at,repository:repo({eligibleJobs:async()=>[{connectionId:id,resource:"transactions",mode:"deep_reconciliation",schedulerIdentity:"deep",quotaRemaining:2500,requestBudget:800,quotaFloor:2000}]}),queue:{send:async()=>{sent++}}})).enqueued,0)});
test("cron enqueues bounded continuous and deep messages",async()=>{const sent:any[]=[];const repository=repo({eligibleJobs:async()=>[{connectionId:id,resource:"transactions",mode:"continuous",schedulerIdentity:"overlap",quotaRemaining:9000,requestBudget:8,quotaFloor:1000},{connectionId:id,resource:"transactions",mode:"deep_reconciliation",schedulerIdentity:"deep",quotaRemaining:9000,requestBudget:800,quotaFloor:2000}]});assert.equal((await runCommerceCron({now:message.requested_at,repository,queue:{send:async value=>{sent.push(value)}}})).enqueued,2);assert.deepEqual(sent.map(x=>x.requested_mode),["continuous","deep_reconciliation"])});
test("duplicate reservation suppresses at-least-once enqueue",async()=>{let sent=0;const result=await runCommerceCron({now:message.requested_at,repository:repo({reserve:async()=>"duplicate"}),queue:{send:async()=>{sent++}}});assert.equal(result.duplicates,1);assert.equal(sent,0)});
test("consumer rechecks kill switch and Connection pause",async()=>{let runs=0;const result=await consumeCommerceMessage({value:message,repository:repo({connectionPermitted:async()=>false}),runtime:{run:async()=>{runs++;return{status:"completed",providerRequests:2}}}});assert.equal(runs,0);assert.equal(result.status,"disabled")});
test("consumer invokes existing runtime once and duplicate delivery converges through runtime identity",async()=>{let runs=0;const runtime={run:async()=>{runs++;return{status:"completed" as const,providerRequests:2}}};await consumeCommerceMessage({value:message,repository:repo(),runtime});await consumeCommerceMessage({value:message,repository:repo(),runtime});assert.equal(runs,2);assert.equal(message.scheduler_identity,"schedule:bucket")});
test("consumer classifies retryable and permanent failures",async()=>{for(const [error,retry]of[[new Error("provider 429"),true],[Object.assign(new Error("schema drift"),{code:"schema_drift"}),false],[new Error("credential invalid"),false],[new Error("lease conflict"),true]]as const){const result=await consumeCommerceMessage({value:message,repository:repo(),runtime:{run:async()=>{throw error}}});assert.equal(result.retry,retry)}});
