export const CONTINUOUS_COMMERCE_QUEUE_SCHEMA=1;
export type CommerceJobType="commerce_continuous"|"commerce_deep_reconciliation"|"investigation_candidate_evaluation"|"investigation_refresh";
export type CommerceQueueMessage={schema_version:1;job_type:CommerceJobType;connection_id:string;resource:string;requested_mode:"continuous"|"deep_reconciliation"|"candidate_evaluation"|"investigation_refresh";scheduler_identity:string;requested_at:string};
export type EligibleCommerceJob={connectionId:string;resource:string;mode:"continuous"|"deep_reconciliation";schedulerIdentity:string;quotaRemaining:number|null;requestBudget:number;quotaFloor:number};
export type CommerceAdapterRepository={schedulerEnabled():Promise<boolean>;eligibleJobs(now:string):Promise<EligibleCommerceJob[]>;connectionPermitted(connectionId:string):Promise<boolean>;reserve(message:CommerceQueueMessage):Promise<"reserved"|"duplicate">;recordMetric(event:string,details:Record<string,unknown>):Promise<void>};
export type CommerceQueue={send(message:CommerceQueueMessage):Promise<void>};
export type CommerceRuntime={run(message:CommerceQueueMessage):Promise<{status:"completed"|"completed_with_warnings";providerRequests:number}>};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function validateCommerceQueueMessage(value:unknown):CommerceQueueMessage{if(!value||typeof value!=="object")throw new Error("invalid_queue_message");const v=value as any,keys=Object.keys(v);if(keys.some(key=>!["schema_version","job_type","connection_id","resource","requested_mode","scheduler_identity","requested_at"].includes(key))||v.schema_version!==1||!uuid.test(v.connection_id)||!/^transactions$/.test(v.resource)||!/^commerce_(continuous|deep_reconciliation)$/.test(v.job_type)||!['continuous','deep_reconciliation'].includes(v.requested_mode)||typeof v.scheduler_identity!=="string"||v.scheduler_identity.length>160||!Number.isFinite(Date.parse(v.requested_at)))throw new Error("invalid_queue_message");return structuredClone(v)}
export function classifyCommerceQueueFailure(error:unknown){const code=String((error as any)?.code||(error as Error)?.message||"");if(/schema|credential|unauthorized|invalid_queue|cross_tenant/i.test(code))return{retry:false,code:"permanent_runtime_failure"};if(/paused|disabled/i.test(code))return{retry:false,code:"capability_disabled"};if(/lease/i.test(code))return{retry:true,code:"lease_conflict"};if(/429|rate|timeout|network|evidence|database|storage|interrupt/i.test(code))return{retry:true,code:"transient_runtime_failure"};return{retry:true,code:"runtime_failure"}}
export async function runCommerceCron(input:{now:string;repository:CommerceAdapterRepository;queue:CommerceQueue}){const started=Date.now();if(!await input.repository.schedulerEnabled()){await input.repository.recordMetric("commerce.cron.disabled",{});return{eligible:0,enqueued:0,duplicates:0}}let eligible=0,enqueued=0,duplicates=0;for(const job of await input.repository.eligibleJobs(input.now)){eligible++;if(!await input.repository.connectionPermitted(job.connectionId))continue;if(job.quotaRemaining===null||job.quotaRemaining-job.requestBudget<job.quotaFloor){await input.repository.recordMetric("commerce.cron.quota_suppressed",{connection_id:job.connectionId,mode:job.mode});continue}const message:CommerceQueueMessage={schema_version:1,job_type:job.mode==="continuous"?"commerce_continuous":"commerce_deep_reconciliation",connection_id:job.connectionId,resource:job.resource,requested_mode:job.mode,scheduler_identity:job.schedulerIdentity,requested_at:input.now};const reservation=await input.repository.reserve(message);if(reservation==="duplicate"){duplicates++;continue}await input.queue.send(message);enqueued++}await input.repository.recordMetric("commerce.cron.completed",{eligible,enqueued,duplicates,duration_ms:Date.now()-started});return{eligible,enqueued,duplicates}}
export async function consumeCommerceMessage(input:{value:unknown;repository:CommerceAdapterRepository;runtime:CommerceRuntime}){const started=Date.now(),message=validateCommerceQueueMessage(input.value);if(!await input.repository.schedulerEnabled()||!await input.repository.connectionPermitted(message.connection_id))return{ack:true,retry:false,status:"disabled"};try{const result=await input.runtime.run(message);await input.repository.recordMetric("commerce.queue.completed",{connection_id:message.connection_id,mode:message.requested_mode,provider_requests:result.providerRequests,duration_ms:Date.now()-started});return{ack:true,retry:false,status:result.status}}catch(error){const failure=classifyCommerceQueueFailure(error);await input.repository.recordMetric("commerce.queue.failed",{connection_id:message.connection_id,mode:message.requested_mode,code:failure.code,retry:failure.retry});return{ack:!failure.retry,retry:failure.retry,status:"failed"}}}
