import assert from "node:assert/strict";
import test from "node:test";
import { aggregateJourneyAttributionEvidence, JOURNEY_EVIDENCE_MAX_IDENTIFIERS, JOURNEY_EVIDENCE_MAX_REFERRER_ORIGINS } from "./journey-attribution-evidence.ts";

const obs = (raw_param: string, value: string, provider = "everflow", category = "affiliate_network", source_location = "page_url") => ({ raw_param, value, provider, category, identifier_type: raw_param.includes("clid") ? "click_id" : "transaction_id", source_location });
const event = (id: string, at: string, identifiers: any[] = [], referrer: any = { client: null, origin: null, domain: null, missing: true }, page_url = "https://example.com/page") => ({ id, event_time: at, metadata: { page_url, attribution_evidence_v1: { schema_version: 1, identifiers, marketing_params: [], referrer, flags: [] } } });
const t1 = "2026-01-01T00:00:00Z", t2 = "2026-01-02T00:00:00Z", refA = { client: "https://a.example/path", origin: "https://a.example", domain: "a.example", missing: false };

test("single Everflow identity remains unchanged", () => { const r = aggregateJourneyAttributionEvidence([event("a", t1, [obs("_ef_transaction_id", "x")]), event("b", t2, [obs("_ef_transaction_id", "x")])]); assert.equal(r.identifiers[0].event_count, 2); assert.equal(r.identifiers[0].value_changed, false); });
test("Meta and Everflow produce descriptive cross-category flag", () => { const r = aggregateJourneyAttributionEvidence([event("a", t1, [obs("fbclid", "m", "meta", "paid_media"), obs("_ef_transaction_id", "e")])]); assert.ok(r.flags.includes("paid_media_and_affiliate_observed")); assert.equal(r.flags.some((f) => /fraud|suspicious/.test(f)), false); });
test("Google then Meta transition is deterministic", () => { const r = aggregateJourneyAttributionEvidence([event("b", t2, [obs("fbclid", "m", "meta", "paid_media")]), event("a", t1, [obs("gclid", "g", "google", "paid_media")])]); assert.deepEqual(r.providers.map((p) => p.provider), ["google", "meta"]); });
test("identifier value change is retained", () => { const r = aggregateJourneyAttributionEvidence([event("a", t1, [obs("_ef_transaction_id", "x")]), event("b", t2, [obs("_ef_transaction_id", "y")])]); assert.equal(r.identifiers[0].distinct_value_count, 2); assert.ok(r.flags.includes("identifier_value_changed")); });
test("source locations retain first and latest", () => { const r = aggregateJourneyAttributionEvidence([event("a", t1, [obs("_ef_transaction_id", "x")]), event("b", t2, [obs("_ef_transaction_id", "x", "everflow", "affiliate_network", "current_touch.params")])]); assert.equal(r.identifiers[0].first_source_location, "page_url"); assert.equal(r.identifiers[0].latest_source_location, "current_touch.params"); });
test("multiple affiliate networks are descriptive", () => { const r = aggregateJourneyAttributionEvidence([event("a", t1, [obs("_ef_transaction_id", "x"), obs("aff_click_id", "y", "tune", "affiliate_network")])]); assert.ok(r.flags.includes("multiple_affiliate_networks_observed")); });
test("multiple trackers are descriptive", () => { const r = aggregateJourneyAttributionEvidence([event("a", t1, [obs("transaction_id", "x", "unknown", "tracker"), obs("click_id", "y", "unknown", "tracker")])]); assert.ok(r.flags.includes("multiple_trackers_observed")); });
test("missing referrer on any event is retained", () => { const r = aggregateJourneyAttributionEvidence([event("a", t1, [], refA), event("b", t2)]); assert.equal(r.referrers.missing_observed, true); assert.ok(r.flags.includes("referrer_missing_observed")); });
test("external referrer changes are retained", () => { const refB = { client: "https://b.example/path", origin: "https://b.example", missing: false }; const r = aggregateJourneyAttributionEvidence([event("a", t1, [], refA), event("b", t2, [], refB)]); assert.equal(r.referrers.changed, true); assert.ok(r.flags.includes("external_referrer_changed")); });
test("duplicate observations do not inflate distinct values", () => { const r = aggregateJourneyAttributionEvidence([event("a", t1, [obs("_ef_transaction_id", "x"), obs("_ef_transaction_id", "x")])]); assert.equal(r.identifiers[0].distinct_value_count, 1); assert.equal(r.identifiers[0].event_count, 1); });
test("same timestamp ordering uses event id", () => { const r = aggregateJourneyAttributionEvidence([event("b", t1, [obs("_ef_transaction_id", "latest")]), event("a", t1, [obs("_ef_transaction_id", "first")])]); assert.equal(r.identifiers[0].first_value, "first"); assert.equal(r.identifiers[0].latest_value, "latest"); });
test("empty evidence is safe", () => { const r = aggregateJourneyAttributionEvidence([]); assert.deepEqual(r.identifiers, []); assert.deepEqual(r.providers, []); assert.equal(r.truncation.truncated, false); });
test("identifier cap exposes truncation", () => { const ids = Array.from({ length: JOURNEY_EVIDENCE_MAX_IDENTIFIERS + 1 }, (_, i) => obs(`tracker_${i}`, `${i}`, "unknown", "tracker")); const r = aggregateJourneyAttributionEvidence([event("a", t1, ids)]); assert.equal(r.identifiers.length, JOURNEY_EVIDENCE_MAX_IDENTIFIERS); assert.equal(r.truncation.identifiers, true); });
test("referrer origin cap exposes truncation", () => { const rows = Array.from({ length: JOURNEY_EVIDENCE_MAX_REFERRER_ORIGINS + 1 }, (_, i) => event(String(i), new Date(Date.parse(t1) + i * 1000).toISOString(), [], { client: `https://r${i}.example/path`, origin: `https://r${i}.example`, missing: false })); const r = aggregateJourneyAttributionEvidence(rows); assert.equal(r.referrers.distinct_external_origins.length, JOURNEY_EVIDENCE_MAX_REFERRER_ORIGINS); assert.equal(r.truncation.referrer_origins, true); });
test("source event cap is explicit", () => { const r = aggregateJourneyAttributionEvidence([], { source_truncated: true }); assert.equal(r.truncation.events, true); assert.equal(r.truncation.truncated, true); });
