import assert from"node:assert/strict";import test from"node:test";import{executeTkidErasure,type ErasureRun}from"./tkid-erasure.ts";
function fixture(options:{authorized?:boolean;objectFailure?:boolean;dbFailure?:boolean;completed?:boolean}={}){const run:ErasureRun={id:"run",organizationId:"org",journeyId:"journey",policyId:"policy",status:options.completed?"completed":"queued",evidence:[{id:"e1",objectReference:"private/object",erasedAt:null}]},events:string[]=[];let objectPresent=true;return{run,events,repository:{authorize:async()=>options.authorized!==false,begin:async()=>run,markObjectErased:async()=>{run.evidence[0].erasedAt="now";events.push("object_tombstone")},completeDatabase:async()=>{if(options.dbFailure)throw new Error("db");run.status="completed";events.push("database_tombstone")},fail:async(_id:string,status:any)=>{run.status=status;events.push(status)},audit:async()=>{events.push("audit")}},objects:{erase:async()=>{if(options.objectFailure)throw new Error("object");objectPresent=false;events.push("object_deleted")},absent:async()=>!objectPresent}}}
const input=(f:any)=>({organizationId:"org",journeyId:"journey",policyId:"policy",actorContext:"retention_worker",repository:f.repository,objects:f.objects,now:"2026-08-10T00:00:00Z"});
test("authorized erasure deletes object before database tombstone and audits",async()=>{const f=fixture();assert.equal((await executeTkidErasure(input(f))).status,"completed");assert.deepEqual(f.events,["object_deleted","object_tombstone","database_tombstone","audit"])});
test("cross-Organization or unknown Journey fails closed",async()=>{const f=fixture({authorized:false});await assert.rejects(()=>executeTkidErasure(input(f)),/journey_unavailable/);assert.deepEqual(f.events,[])});
test("second execution is idempotent",async()=>{const f=fixture({completed:true});assert.equal((await executeTkidErasure(input(f))).status,"already_erased");assert.deepEqual(f.events,[])});
test("object failure checkpoints retry without false completion",async()=>{const f=fixture({objectFailure:true});assert.equal((await executeTkidErasure(input(f))).status,"retry_required");assert.equal(f.run.status,"object_failed");assert.doesNotMatch(f.events.join(","),/database_tombstone|audit/)});
test("database failure preserves completed object work for retry",async()=>{const f=fixture({dbFailure:true});assert.equal((await executeTkidErasure(input(f))).status,"retry_required");assert.equal(f.run.evidence[0].erasedAt,"now");assert.equal(f.run.status,"database_failed")});
test("erasure contract carries opaque IDs and no behavioral payload",()=>{const f=fixture();assert.doesNotMatch(JSON.stringify(input(f)),/email|phone|payload|offer|price|storage_url/i)});
