import assert from"node:assert/strict";import test from"node:test";import{abuseFailureDisposition,enforceTkidRate,ephemeralTransportDimension,type DistributedCounterStore}from"./tkid-distributed-abuse.ts";
class SharedStore implements DistributedCounterStore{rows=new Map<string,{count:number;resetAt:string}>();async consume(i:any){const window=Math.floor(Date.parse(i.now)/(i.windowSeconds*1000)),key=`${i.organizationId}:${i.sourceId}:${i.rateClass}:${i.keyHash}:${window}`,resetAt=new Date((window+1)*i.windowSeconds*1000).toISOString(),row=this.rows.get(key)||{count:0,resetAt};row.count++;this.rows.set(key,row);return{allowed:row.count<=i.limit,count:row.count,limit:i.limit,resetAt}}}
const base={organizationId:"org-a",sourceId:"source-a",rateClass:"event_accepted" as const,dimension:"origin",limit:2,now:"2026-08-10T00:00:00Z"};
test("multiple Worker instances share one distributed source limit",async()=>{const store=new SharedStore();await enforceTkidRate({...base,store});await enforceTkidRate({...base,store});await assert.rejects(()=>enforceTkidRate({...base,store}),/rate limit/)});
test("fixed window resets and permits configured burst",async()=>{const store=new SharedStore();await enforceTkidRate({...base,store});await enforceTkidRate({...base,store,now:"2026-08-10T00:01:00Z"});assert.equal(store.rows.size,2)});
test("rate classes and Organizations cannot collide",async()=>{const store=new SharedStore();for(const value of [{...base},{...base,organizationId:"org-b"},{...base,rateClass:"handoff_issue" as const},{...base,rateClass:"checkout_association" as const}])await enforceTkidRate({...value,store});assert.equal(store.rows.size,4)});
test("invalid and handoff rates have independent thresholds",async()=>{const store=new SharedStore();await enforceTkidRate({...base,store,rateClass:"event_invalid",limit:1});await assert.rejects(()=>enforceTkidRate({...base,store,rateClass:"event_invalid",limit:1}));await enforceTkidRate({...base,store,rateClass:"handoff_consume",limit:2})});
test("backend unavailable fails TKID closed while checkout remains allowed",async()=>{const store={consume:async()=>{throw new Error("db unavailable")}};await assert.rejects(()=>enforceTkidRate({...base,store}),/abuse_control_unavailable/);assert.equal(abuseFailureDisposition("checkout_association").checkoutAllowed,true)});
test("transport IP is irreversibly hashed and never exposed",async()=>{const key=await ephemeralTransportDimension("203.0.113.1","https://shop.example/path");assert.equal(key.length,64);assert.doesNotMatch(key,/203\.0\.113\.1|shop\.example/)});
