const encoder=new TextEncoder();
export const TKID_SCHEMA_VERSION=1, TKID_NORMALIZER_VERSION="tkid-normalizer-v1", TKID_MAX_BATCH=20, TKID_MAX_BODY_BYTES=32768;
export const TKID_EVENT_NAMES=["journey_started","page_viewed","funnel_step_viewed","offer_viewed","upsell_viewed","cta_clicked","offer_accepted","offer_declined","checkout_started","checkout_submitted","purchase_confirmed","confirmation_viewed","receipt_observed","cross_domain_handoff","client_error","vsl_milestone"] as const;
export type TkidEventName=typeof TKID_EVENT_NAMES[number]; export type PrivacyMode="essential"|"analytics_allowed";
export type TkidSource={id:string;organizationId:string;businessContextId:string;publicSourceId:string;allowedOrigins:string[];status:"active"|"disabled"|"revoked";captureMode:PrivacyMode;rateLimitPerMinute:number};
export type TkidEventInput={event_id:string;event_name:string;schema_version:number;occurred_at:string;journey_id:string;browser_session_id:string;checkout_session_id?:string;privacy_mode:PrivacyMode;funnel_step_id?:string;offer_id?:string;offer_version_id?:string;cta_id?:string;cta_version?:string;price?:{amount:string;currency:string;recurring:boolean;billing_cadence?:string;trial_state?:string};terms_version?:string;disclosure_version?:string;affirmative_action?:boolean;displayed_descriptor?:string;descriptor_version?:string;milestone?:string;duration_bucket?:string;action_type?:string;error?:{code:string;category:string};app_version?:string;page_id?:string};
export type NormalizedTkidEvent=TkidEventInput&{event_name:TkidEventName;received_at:string;normalizer_version:string;evidence_hash:string};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, tokenId=/^tksrc_[A-Za-z0-9_-]{16,96}$/;
const forbidden=/^(email|phone|name|full_name|customer_name|address|ip|ip_address|user_agent|card|card_number|password|query|query_string|stack|stack_trace|free_text|html|dom|selector|fingerprint|fingerprint_hash)$/i;
const allowedEventKeys=new Set(["event_id","event_name","schema_version","occurred_at","journey_id","browser_session_id","checkout_session_id","privacy_mode","funnel_step_id","offer_id","offer_version_id","cta_id","cta_version","price","terms_version","disclosure_version","affirmative_action","displayed_descriptor","descriptor_version","milestone","duration_bucket","action_type","error","app_version","page_id"]);
export function opaqueId(){return crypto.randomUUID();}
export function journeyExpiry(start:string){return new Date(Date.parse(start)+2*60*60*1000).toISOString()}
export function browserSessionExpiry(lastSeen:string){return new Date(Date.parse(lastSeen)+30*60*1000).toISOString()}
export function normalizeOrigin(value:string){const u=new URL(value);return `${u.protocol}//${u.host}`}
export function originAllowed(origin:string|null,source:TkidSource){if(!origin)return false;try{return source.status==="active"&&source.allowedOrigins.includes(normalizeOrigin(origin))}catch{return false}}
function assertText(value:unknown,name:string,max=96,required=false){if(value==null||value===""){if(required)throw new TkidError("invalid_schema",`${name} is required`);return}if(typeof value!=="string"||value.length>max||/[\u0000-\u001f]/.test(value))throw new TkidError("invalid_schema",`${name} is invalid`)}
export class TkidError extends Error{code:string;status:number;constructor(code:string,message:string,status=400){super(message);this.code=code;this.status=status}}
function stable(value:any):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(k=>JSON.stringify(k)+":"+stable(value[k])).join(",")}}`;return JSON.stringify(value)}
export async function sha256(value:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value)))].map(x=>x.toString(16).padStart(2,"0")).join("")}
export function validateEvent(input:unknown,now=Date.now()):TkidEventInput{if(!input||typeof input!=="object"||Array.isArray(input))throw new TkidError("invalid_schema","event must be an object");const e=input as any;for(const key of Object.keys(e)){if(forbidden.test(key))throw new TkidError("privacy_field_rejected",`field ${key} is not allowed`);if(!allowedEventKeys.has(key))throw new TkidError("unknown_field",`field ${key} is not part of TKID v1`)}if(!uuid.test(e.event_id)||!uuid.test(e.journey_id)||!uuid.test(e.browser_session_id)||(e.checkout_session_id&&!uuid.test(e.checkout_session_id)))throw new TkidError("invalid_identifier","opaque UUIDv4 identifiers are required");if(!TKID_EVENT_NAMES.includes(e.event_name)||e.schema_version!==1)throw new TkidError("unsupported_schema","event name/schema version is not supported");const occurred=Date.parse(e.occurred_at);if(!Number.isFinite(occurred)||occurred>now+5*60_000||occurred<now-24*60*60_000)throw new TkidError("timestamp_out_of_range","occurred_at is outside the accepted window");if(!["essential","analytics_allowed"].includes(e.privacy_mode))throw new TkidError("invalid_privacy_mode","privacy_mode is required");for(const k of ["funnel_step_id","offer_id","offer_version_id","cta_id","cta_version","terms_version","disclosure_version","descriptor_version","milestone","duration_bucket","action_type","app_version","page_id"])assertText(e[k],k);assertText(e.displayed_descriptor,"displayed_descriptor",96);if(e.error){assertText(e.error.code,"error.code",64,true);assertText(e.error.category,"error.category",64,true);if(Object.keys(e.error).some(k=>!["code","category"].includes(k)))throw new TkidError("privacy_field_rejected","client error details are bounded")};if(e.price){if(Object.keys(e.price).some(k=>!["amount","currency","recurring","billing_cadence","trial_state"].includes(k)))throw new TkidError("unknown_field","price contains an unsupported field");if(!/^\d+(\.\d{1,6})?$/.test(e.price.amount)||!Number.isFinite(Number(e.price.amount))||Number(e.price.amount)<0)throw new TkidError("invalid_price","price amount is invalid");if(!/^[A-Z]{3}$/.test(e.price.currency))throw new TkidError("invalid_currency","currency must be ISO-4217");if(typeof e.price.recurring!=="boolean")throw new TkidError("invalid_price","recurring must be boolean");assertText(e.price.billing_cadence,"price.billing_cadence",32);assertText(e.price.trial_state,"price.trial_state",32)}return structuredClone(e)}
export async function normalizeEvent(input:unknown,receivedAt=new Date().toISOString()):Promise<NormalizedTkidEvent>{const e=validateEvent(input,Date.parse(receivedAt));return {...e,event_name:e.event_name as TkidEventName,received_at:receivedAt,normalizer_version:TKID_NORMALIZER_VERSION,evidence_hash:await sha256(stable(e))}}
export function validateBatch(body:unknown){const events=(body as any)?.events;if(!Array.isArray(events)||events.length<1||events.length>TKID_MAX_BATCH)throw new TkidError("invalid_batch",`events must contain 1-${TKID_MAX_BATCH} items`);if(encoder.encode(JSON.stringify(body)).byteLength>TKID_MAX_BODY_BYTES)throw new TkidError("payload_too_large","payload exceeds 32 KiB",413);return events}
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function fromB64url(s:string){const raw=atob(s.replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign","verify"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,encoder.encode(value)))}
export async function issueHandoff(input:{handoffId:string;journeyId:string;browserSessionId:string;sourceId:string;targetOrigin:string;expiresAt:string},secret:string){const payload=b64url(encoder.encode(JSON.stringify(input)));return`${payload}.${b64url(await hmac(secret,payload))}`}
export async function validateHandoff(token:string,secret:string,source:TkidSource,targetOrigin:string,consumed:Set<string>,now=Date.now()){const [payload,sig,...extra]=token.split(".");if(!payload||!sig||extra.length)throw new TkidError("invalid_handoff","handoff is malformed",401);const expected=await hmac(secret,payload),actual=fromB64url(sig);let diff=actual.length^expected.length;for(let i=0;i<Math.min(actual.length,expected.length);i++)diff|=actual[i]^expected[i];if(diff)throw new TkidError("invalid_handoff","handoff signature failed",401);const value=JSON.parse(new TextDecoder().decode(fromB64url(payload)));if(!uuid.test(value.handoffId)||!uuid.test(value.journeyId)||!uuid.test(value.browserSessionId)||value.sourceId!==source.id||normalizeOrigin(value.targetOrigin)!==normalizeOrigin(targetOrigin)||!source.allowedOrigins.includes(normalizeOrigin(targetOrigin))||Date.parse(value.expiresAt)<now)throw new TkidError("invalid_handoff","handoff scope or expiry failed",401);if(consumed.has(value.handoffId))throw new TkidError("handoff_replayed","handoff was already consumed",409);consumed.add(value.handoffId);return value}
export type TkidRepository={eventIds:Set<string>;events:NormalizedTkidEvent[]};
export async function ingestBatch(args:{body:unknown;origin:string|null;publicSourceId:string;source:TkidSource;repo:TkidRepository;now?:string}){if(!tokenId.test(args.publicSourceId)||args.publicSourceId!==args.source.publicSourceId)throw new TkidError("source_not_found","source unavailable",404);if(!originAllowed(args.origin,args.source))throw new TkidError("origin_not_allowed","origin is not approved",403);const events=validateBatch(args.body),now=args.now||new Date().toISOString(),accepted:NormalizedTkidEvent[]=[],duplicates:string[]=[];for(const raw of events){const normalized=await normalizeEvent(raw,now);if(args.repo.eventIds.has(normalized.event_id)){duplicates.push(normalized.event_id);continue}args.repo.eventIds.add(normalized.event_id);args.repo.events.push(normalized);accepted.push(normalized)}return{accepted:accepted.length,duplicates:duplicates.length,rejected:0,event_ids:accepted.map(e=>e.event_id)}}
export function safeJourneyReadModel(events:NormalizedTkidEvent[],links:Array<{chargeReference:string;parentChargeReference?:string;relationship:string;sequencePosition:number}>){const ordered=[...events].sort((a,b)=>a.occurred_at.localeCompare(b.occurred_at));const names=new Set(ordered.map(e=>e.event_name)),offer=ordered.find(e=>e.event_name==="upsell_viewed"||e.event_name==="offer_viewed");return{journeyId:ordered[0]?.journey_id||null,start:ordered[0]?.occurred_at||null,end:ordered.at(-1)?.occurred_at||null,eventCount:ordered.length,steps:ordered.map(e=>({name:e.event_name,at:e.occurred_at,state:"observed",funnelStepId:e.funnel_step_id||null,offerId:e.offer_id||null})),offerSnapshot:offer?{offerId:offer.offer_id,versionId:offer.offer_version_id,price:offer.price}:null,upsellDecision:ordered.find(e=>e.event_name==="offer_accepted"||e.event_name==="offer_declined")?.event_name||null,confirmationObserved:names.has("confirmation_viewed"),handoffObserved:names.has("cross_domain_handoff"),clientErrorCount:ordered.filter(e=>e.event_name==="client_error").length,charges:links,completeness:names.has("checkout_started")?(names.has("confirmation_viewed")?(links.length?"complete":"unlinked_commerce"):"missing_confirmation"):"missing_checkout",missing:[...(!names.has("confirmation_viewed")?["confirmation_viewed"]:[]),...(links.length?[]:["server_commerce_link"])]}}
export function erasedJourneyReadModel(journeyId:string,erasedAt:string){return{journeyId,start:null,end:null,eventCount:0,steps:[],offerSnapshot:null,upsellDecision:null,confirmationObserved:false,handoffObserved:false,clientErrorCount:0,charges:[],completeness:"erased",missing:["Evidence erased under retention/privacy policy"],erasedAt}}
export function matchTkidRoute(method:string,path:string){if(path==="/v1/tkid/events")return method==="POST"?"ingest":"method_not_allowed";if(path==="/v1/tkid/bootstrap")return method==="POST"?"bootstrap":"method_not_allowed";if(path==="/v1/tkid/handoff")return method==="POST"?"handoff":"method_not_allowed";if(path==="/v1/tkid/checkout-association")return method==="POST"?"checkout_association":"method_not_allowed";return null}
