import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { CommercePersistenceError, SupabaseCommerceControlRepository, commercePersistenceRequest } from "@/lib/commerce/supabase-control-repository";
import { loadProductMappingRecommendations } from "@/lib/commerce/product-mapping-intelligence-repository";
import type { MappingRecommendation } from "@/lib/commerce/product-mapping-intelligence";
import { resolveApplicationSession } from "@/lib/identity/application-session";
import { AuthorizationDeniedError, requirePermission } from "@/lib/identity/authorization-gateway";

const ORGANIZATION_ID="5f1de64a-1b37-40bb-81c8-32197eda0b41",ACCOUNT_ID="39d895f9-71ac-44d3-ac33-6e9043f6267e",CONNECTION_ID="ea1c2313-6120-4692-84c5-ec3562e7dcf6",PROVIDER_ACCOUNT_ID="0369c701-717f-4c34-b230-8341bcdb7e65";
const select="provider_product_row_id,provider_product_id,title,mapping_status,mapping_version,business_context_id,canonical_offer_id,offer_step_id,offer_variant_id,integrity_status,order_count,gross_revenue,refund_count,refund_amount,first_seen_at,last_seen_at,reviewed_at,alert_open,work_item_open,observed_prices";
function sameOrigin(r:Request){const o=r.headers.get("origin"),s=r.headers.get("sec-fetch-site");return(!o||o===new URL(r.url).origin)&&(!s||s==="same-origin")}
function response(id:string,body:Record<string,unknown>,status=200){return NextResponse.json({...body,requestId:id},{status,headers:{"x-tracekit-request-id":id}})}
async function session(){const r=await resolveApplicationSession();if(r.kind!=="authenticated"||!r.session.activeOrganization||r.session.activeOrganization.id!==ORGANIZATION_ID||r.session.activeAccount.id!==ACCOUNT_ID)throw new AuthorizationDeniedError();requirePermission(r.session,"offers.manage");return r.session}
const scope=`organization_id=eq.${ORGANIZATION_ID}&connection_id=eq.${CONNECTION_ID}&provider_account_id=eq.${PROVIDER_ACCOUNT_ID}`;
async function product(externalId:string){return (await commercePersistenceRequest(`commerce_product_mapping_review_v1?${scope}&provider_product_id=eq.${encodeURIComponent(externalId)}&select=${select}&limit=1`))[0]||null}
async function history(rowId:string){return commercePersistenceRequest(`commerce_product_mapping_decisions?organization_id=eq.${ORGANIZATION_ID}&connection_id=eq.${CONNECTION_ID}&provider_account_id=eq.${PROVIDER_ACCOUNT_ID}&provider_product_id=eq.${encodeURIComponent(rowId)}&select=id,previous_state,resulting_state,business_context_id,canonical_offer_id,offer_step_id,offer_variant_id,mapping_version,decided_by_user_id,reason,correlation_id,decided_at:created_at&order=created_at.desc&limit=50`)}

async function recommendations(rows:Record<string,unknown>[]) {
  try {
    return await loadProductMappingRecommendations(
      { organizationId: ORGANIZATION_ID, connectionId: CONNECTION_ID, providerAccountId: PROVIDER_ACCOUNT_ID, provider: "commas" },
      rows.map((row) => ({ providerProductId: String(row.provider_product_id || ""), title: String(row.title || ""), observedPrices: Array.isArray(row.observed_prices) ? row.observed_prices.map(Number) : [], currency: "USD" })),
    );
  } catch (error) {
    // Keep the existing review surface available during staged rollout if the
    // intelligence migration has not reached the environment yet. Mapping
    // decisions still use the same guarded RPC and do not depend on this layer.
    if (error instanceof CommercePersistenceError) return new Map<string, MappingRecommendation>();
    throw error;
  }
}

function recommendationTarget(recommendation?:MappingRecommendation){return recommendation?{businessContextId:recommendation.businessContextId,canonicalOfferId:recommendation.canonicalOfferId,offerStepId:recommendation.offerStepId,offerVariantId:recommendation.offerVariantId}:null}
function safeProduct(row:Record<string,unknown>, recommendation?:MappingRecommendation){return{providerProductRowId:row.provider_product_row_id,providerProductId:row.provider_product_id,title:row.title,mappingStatus:row.mapping_status,mappingVersion:row.mapping_version,businessContextId:row.business_context_id,canonicalOfferId:row.canonical_offer_id,offerStepId:row.offer_step_id,offerVariantId:row.offer_variant_id,integrityStatus:row.integrity_status,orderCount:Number(row.order_count||0),grossRevenue:Number(row.gross_revenue||0),refundCount:Number(row.refund_count||0),refundAmount:Number(row.refund_amount||0),observedPrices:Array.isArray(row.observed_prices)?row.observed_prices.map(Number).filter(Number.isFinite).sort((a,b)=>a-b):[],firstSeenAt:row.first_seen_at,lastSeenAt:row.last_seen_at,reviewedAt:row.reviewed_at,alertOpen:row.alert_open===true,workItemOpen:row.work_item_open===true,recommendation:recommendation||null,authorizedPreset:recommendationTarget(recommendation)}}

export async function GET(request:Request){const id=randomUUID();try{await session();const external=new URL(request.url).searchParams.get("providerProductId");const [rows,contexts,offers,steps,variants]=await Promise.all([external?product(external).then(r=>r&&r.mapping_status!=="retired"?[r]:[]):Promise.resolve(null),commercePersistenceRequest(`tracekit_business_contexts?organization_id=eq.${ORGANIZATION_ID}&status=eq.active&select=id,name,status`),commercePersistenceRequest(`canonical_offers?organization_id=eq.${ORGANIZATION_ID}&status=eq.active&select=id,business_context_id,name,status`),commercePersistenceRequest(`offer_steps?organization_id=eq.${ORGANIZATION_ID}&select=id,canonical_offer_id,role,sequence,label,metadata&order=canonical_offer_id,sequence`),commercePersistenceRequest(`offer_variants?organization_id=eq.${ORGANIZATION_ID}&select=id,offer_step_id,kind,sequence,label`)]);const productRows=rows||await commercePersistenceRequest(`commerce_product_mapping_review_v1?${scope}&mapping_status=neq.retired&select=${select}&order=gross_revenue.desc,order_count.desc&limit=100`);const recs=await recommendations(productRows);const products=productRows.map((row:Record<string,unknown>)=>safeProduct(row,recs.get(String(row.provider_product_id))));return response(id,{ok:true,products,targets:{contexts,offers,steps,variants},history:products.length===1?await history(String(productRows[0].provider_product_row_id)):[]})}catch(e){if(e instanceof AuthorizationDeniedError)return response(id,{ok:false,code:"resource_unavailable"},404);return response(id,{ok:false,code:"mapping_review_unavailable"},500)}}

export async function POST(request:Request){const id=randomUUID();try{const s=await session();if(!sameOrigin(request))return response(id,{ok:false,code:"request_verification_failed"},403);const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return response(id,{ok:false,code:"validation_failed"},400);const allowed=new Set(["providerProductId","result","expectedMappingVersion","businessContextId","canonicalOfferId","offerStepId","offerVariantId","reason","confirmation"]);if(Object.keys(body).some(k=>!allowed.has(k))||body.confirmation!=="confirm-product-mapping-decision")return response(id,{ok:false,code:"explicit_confirmation_required"},400);const external=String(body.providerProductId||""),result=String(body.result||""),expected=String(body.expectedMappingVersion||""),reason=String(body.reason||"").trim();if(!external||!expected||!reason||reason.length>500||!["approved","rejected"].includes(result))return response(id,{ok:false,code:"validation_failed"},400);const current=await product(external);if(!current)return response(id,{ok:false,code:"product_not_found"},404);if(current.mapping_status==="retired")return response(id,{ok:false,code:"product_not_actionable"},409);if(current.mapping_version!==expected)return response(id,{ok:false,code:"stale_mapping_version",reload:true},409);
    let contextId:string|undefined,offerId:string|undefined,stepId:string|undefined,variantId:string|undefined;
    if(result==="approved"){contextId=String(body.businessContextId||"");offerId=String(body.canonicalOfferId||"");stepId=String(body.offerStepId||"");variantId=body.offerVariantId?String(body.offerVariantId):undefined;if(!contextId||!offerId||!stepId)return response(id,{ok:false,code:"mapping_target_incomplete"},400);const [c,o,st,v]=await Promise.all([commercePersistenceRequest(`tracekit_business_contexts?organization_id=eq.${ORGANIZATION_ID}&id=eq.${encodeURIComponent(contextId)}&status=eq.active&select=id&limit=1`),commercePersistenceRequest(`canonical_offers?organization_id=eq.${ORGANIZATION_ID}&business_context_id=eq.${encodeURIComponent(contextId)}&id=eq.${encodeURIComponent(offerId)}&status=eq.active&select=id&limit=1`),commercePersistenceRequest(`offer_steps?organization_id=eq.${ORGANIZATION_ID}&canonical_offer_id=eq.${encodeURIComponent(offerId)}&id=eq.${encodeURIComponent(stepId)}&select=id&limit=1`),variantId?commercePersistenceRequest(`offer_variants?organization_id=eq.${ORGANIZATION_ID}&offer_step_id=eq.${encodeURIComponent(stepId)}&id=eq.${encodeURIComponent(variantId)}&select=id&limit=1`):Promise.resolve([{}])]);if(!c[0]||!o[0]||!st[0]||!v[0])return response(id,{ok:false,code:"mapping_target_invalid"},400)}else if(body.businessContextId||body.canonicalOfferId||body.offerStepId||body.offerVariantId)return response(id,{ok:false,code:"rejected_mapping_has_target"},400);
    const mappingVersion=`operator:${new Date().toISOString()}:${randomUUID()}`;const repo=new SupabaseCommerceControlRepository();await repo.decideProductMapping({organizationId:ORGANIZATION_ID,connectionId:CONNECTION_ID,providerAccountId:PROVIDER_ACCOUNT_ID,providerProductId:String(current.provider_product_row_id),resultingState:result as "approved"|"rejected",businessContextId:contextId,canonicalOfferId:offerId,offerStepId:stepId,offerVariantId:variantId,expectedMappingVersion:expected,mappingVersion,actorUserId:s.user.id,reason,correlationId:id});const updated=await product(external);if(!updated)return response(id,{ok:false,code:"mapping_result_unavailable"},502);const updatedRecs=await recommendations([updated]);return response(id,{ok:true,product:safeProduct(updated,updatedRecs.get(external)),history:await history(String(current.provider_product_row_id)),alertReconciliation:"pending_evaluator"})
  }catch(e){if(e instanceof AuthorizationDeniedError)return response(id,{ok:false,code:"resource_unavailable"},404);if(e instanceof CommercePersistenceError){if(e.databaseCode==="40001")return response(id,{ok:false,code:"stale_mapping_version",reload:true},409);if(["22023","23503"].includes(e.databaseCode))return response(id,{ok:false,code:"mapping_target_invalid"},400)}return response(id,{ok:false,code:"mapping_decision_failed"},500)}}
