export type Health = "Excellent" | "Degraded" | "Poor";
export type ProfitState = "Estimated" | "Reconciled";
export type Tone = "up" | "down" | "attention";

export type TrafficSource = { id: string; name: string; spend: number; revenue: number; profit: number; roas: number; cpa: number; orders: number; quality: string; trend: string; health: Health; campaigns: string[] };
export type ProfitDriver = { id: string; label: string; amount: number; detail: string; actionable: string };
export type OfferEvent = { id: string; date: string; title: string; outcome: string; evidence: string[] };
export type Intelligence = { id: string; observation: string; comparison: string; reason: string; recommendation: string; evidence: string[] };
export type TrendPoint = { label: string; profit: number; revenue: number; spend: number };
export type OfferContext = {
  id: string; mark: string; name: string; brand: string; profit: number; revenue: number; spend: number; state: ProfitState; trend: number; trendLabel: string;
  orders: number; customers: number; aov: number; margin: number; roas: number; cpa: number; refundRate: number; chargebackRate: number; shippingMargin: number; health: Health; attention: string;
  customerQuality: { newCustomers: number; returningCustomers: number; ltv: number; repeatRate: number; clickToPurchase: string; highValueShare: number };
  traffic: TrafficSource[]; drivers: ProfitDriver[]; timeline: OfferEvent[]; intelligence: Intelligence[]; trendPoints: TrendPoint[];
};

const source = (id: string, name: string, spend: number, revenue: number, profit: number, orders: number, quality: string, trend: string, health: Health = "Excellent"): TrafficSource => ({ id, name, spend, revenue, profit, roas: +(revenue / Math.max(spend, 1)).toFixed(2), cpa: +(spend / Math.max(orders, 1)).toFixed(2), orders, quality, trend, health, campaigns: [`${name} Scale`, `${name} Retargeting`] });
const driver = (id: string, label: string, amount: number, detail: string, actionable: string): ProfitDriver => ({ id, label, amount, detail, actionable });
const event = (id: string, date: string, title: string, outcome: string): OfferEvent => ({ id, date, title, outcome, evidence: [`${title} change record`, `Performance comparison before and after ${date}`, "Source timestamp preserved"] });

function offer(input: Partial<OfferContext> & Pick<OfferContext, "id" | "mark" | "name" | "brand" | "profit" | "revenue" | "spend">): OfferContext {
  const orders = input.orders ?? 1284; const customers = input.customers ?? 1178;
  return {
    state: "Reconciled", trend: 8.4, trendLabel: "Improving vs prior 7 days", orders, customers,
    aov: +(input.revenue / orders).toFixed(2), margin: +(input.profit / input.revenue * 100).toFixed(1), roas: +(input.revenue / input.spend).toFixed(2), cpa: +(input.spend / customers).toFixed(2),
    refundRate: 3.1, chargebackRate: 0.7, shippingMargin: -4280, health: "Excellent", attention: "Shipping margin needs attention",
    customerQuality: { newCustomers: 942, returningCustomers: 236, ltv: 184, repeatRate: 20, clickToPurchase: "18m 42s", highValueShare: 31 },
    traffic: [], drivers: [], timeline: [], intelligence: [], trendPoints: [
      { label: "Jul 25", profit: 12200, revenue: 48200, spend: 18800 }, { label: "Jul 26", profit: 13100, revenue: 50100, spend: 19200 }, { label: "Jul 27", profit: 12800, revenue: 49700, spend: 19500 }, { label: "Jul 28", profit: 14300, revenue: 53600, spend: 20100 }, { label: "Jul 29", profit: 15100, revenue: 55800, spend: 20400 }, { label: "Jul 30", profit: 16400, revenue: 58100, spend: 20700 }, { label: "Jul 31", profit: 17800, revenue: 61200, spend: 21100 },
    ],
    ...input,
  };
}

const bullseye = offer({ id: "bullseye", mark: "B", name: "Bullseye", brand: "Bullseye Health", profit: 94620, revenue: 486240, spend: 173400, orders: 3240, customers: 2918, margin: 19.5, roas: 2.8, cpa: 59.42, refundRate: 5.4, chargebackRate: 1.1, shippingMargin: -12480, trend: 6.8, attention: "Shipping losses are reducing margin", traffic: [source("meta", "Meta / Facebook", 104000, 278000, 48200, 1710, "Moderate", "+7.2%"), source("google", "Google", 38200, 103000, 26300, 690, "Strong", "+4.1%"), source("affiliate", "Affiliates", 19600, 66200, 15400, 510, "Strong", "+9.8%"), source("email", "Email", 3200, 24200, 4720, 210, "High repeat", "+2.4%"), source("organic", "Organic", 8400, 14840, 0, 120, "High", "Stable")], drivers: [driver("media", "Media cost", -173400, "Largest cost · Meta-heavy mix", "Review source allocation"), driver("cogs", "COGS", -103200, "Product and bundle costs", "Inspect Product costs"), driver("shipping", "Net shipping", -12480, "$18,420 charged · $29,560 carrier · $1,340 Packaging", "Review shipping terms"), driver("processor", "Processor fees", -14980, "Observed settlement fees", "Compare pricing rule"), driver("affiliate", "Affiliate commission", -18640, "Approved conversion commissions", "Inspect Affiliate quality"), driver("refund", "Refunds", -26240, "5.4% refund rate", "Inspect refunded Orders"), driver("tax", "Taxes", -15420, "Observed tax treatment", "Explain treatment"), driver("discount", "Discounts", -9840, "Promotion and offer discounts", "Inspect promotions"), driver("upsell", "Upsell performance", 68400, "28% take rate", "Inspect contribution"), driver("bump", "Order Bump performance", 28400, "17% take rate", "Inspect contribution")], timeline: [event("landing", "Jul 18", "Landing Page updated", "Conversion improved 6.2% afterward"), event("shipping", "Jul 21", "Shipping charge changed", "Net shipping margin declined"), event("creative", "Jul 24", "New Creative launched", "CPA decreased 8.1%"), event("budget", "Jul 27", "Campaign budget increased", "Profit continued to grow"), event("cost", "Jul 29", "Product cost changed", "Margin declined 1.2 points")], intelligence: [{ id: "ship", observation: "Shipping losses are reducing margin.", comparison: "Net shipping margin is $8,200 worse than ValueRx Individual.", reason: "Carrier cost rose while customer shipping stayed fixed.", recommendation: "Review shipping terms before increasing Meta spend.", evidence: ["Carrier invoices", "Shipping Charged", "Packaging costs", "3,240 matched Orders"] }, { id: "cpa", observation: "Profit increased because CPA decreased.", comparison: "CPA improved 8.1% after Creative B launched.", reason: "Meta conversion efficiency improved with stable AOV.", recommendation: "Maintain the winning Creative while monitoring refund quality.", evidence: ["Meta spend", "Creative launch event", "Customer acquisition comparison"] }], });

export const offerContexts: OfferContext[] = [
  bullseye,
  offer({ id: "valuerx-individual", mark: "V1", name: "ValueRx Individual", brand: "ValueRx", profit: 112840, revenue: 392400, spend: 108600, margin: 28.8, cpa: 38.2, refundRate: 2.1, chargebackRate: 0.4, shippingMargin: -4280, trend: 12.6, attention: "No critical issue", traffic: [source("affiliate", "Affiliates", 27200, 141000, 51400, 840, "High LTV", "+14.2%"), source("meta", "Meta / Facebook", 48600, 139400, 36800, 720, "Strong", "+11.5%"), source("google", "Google", 22800, 84000, 21600, 410, "Strong", "+8.1%")], drivers: bullseye.drivers.map(d => d.id === "shipping" ? { ...d, amount: -4280, detail: "Low physical-shipping exposure" } : d), timeline: [event("affiliate", "Jul 17", "Affiliate launched", "Higher-value Customers increased"), event("price", "Jul 23", "Offer price changed", "Margin improved 2.4 points")], intelligence: [{ id: "affiliate", observation: "Affiliate traffic is generating higher-value Customers.", comparison: "Affiliate LTV is 22% above Meta LTV.", reason: "Repeat-purchase behavior is stronger.", recommendation: "Expand the highest-quality Affiliate relationship.", evidence: ["Affiliate cohort LTV", "Repeat Orders", "Commission records"] }] }),
  offer({ id: "valuerx-family", mark: "VF", name: "ValueRx Family", brand: "ValueRx", profit: 78420, revenue: 348900, spend: 98600, aov: 218.4, margin: 22.5, cpa: 67.8, trend: 3.2, attention: "Conversion rate below target", customerQuality: { newCustomers: 1210, returningCustomers: 388, ltv: 326, repeatRate: 29, clickToPurchase: "31m 10s", highValueShare: 44 }, traffic: [source("google", "Google", 40200, 148000, 31400, 580, "High AOV", "+3.4%"), source("meta", "Meta / Facebook", 37400, 121000, 22600, 510, "High LTV", "+1.8%"), source("affiliate", "Affiliates", 21000, 79900, 18200, 280, "Strong", "+5.1%")], drivers: bullseye.drivers, timeline: [event("checkout", "Jul 19", "Checkout flow updated", "Conversion rate declined 1.3 points")], intelligence: [{ id: "aov", observation: "Higher AOV is offsetting a lower conversion rate.", comparison: "AOV is 42% above ValueRx Individual.", reason: "Family bundle value is higher.", recommendation: "Investigate checkout friction before increasing spend.", evidence: ["Checkout sessions", "Order values", "Conversion comparison"] }] }),
  offer({ id: "petes-pasta", mark: "PP", name: "Pete’s Pasta", brand: "Pete’s", profit: 46280, revenue: 214600, spend: 38400, margin: 21.6, refundRate: 1.3, shippingMargin: -8620, trend: 4.7, attention: "Shipping variability requires review", customerQuality: { newCustomers: 610, returningCustomers: 530, ltv: 242, repeatRate: 46, clickToPurchase: "9m 18s", highValueShare: 38 }, traffic: [source("email", "Email", 6800, 72400, 21400, 380, "High repeat", "+8.4%"), source("organic", "Organic", 1200, 51900, 16900, 290, "High repeat", "+3.2%"), source("meta", "Meta / Facebook", 30400, 90300, 7980, 470, "Moderate", "-1.1%")], drivers: bullseye.drivers, timeline: [event("shipping", "Jul 20", "Shipping carrier mix changed", "Shipping variability increased")], intelligence: [{ id: "repeat", observation: "Repeat Customers produce most incremental Profit.", comparison: "46% repeat rate versus 20% for Bullseye.", reason: "Email and Organic traffic have strong retention.", recommendation: "Protect retention while reviewing paid-media dependence.", evidence: ["Repeat Orders", "Email attribution", "Customer LTV"] }] }),
  offer({ id: "manifest-rx", mark: "MR", name: "Manifest RX", brand: "Manifest", profit: 38940, revenue: 188200, spend: 61200, state: "Estimated", health: "Poor", trend: -5.8, trendLabel: "Declining vs prior 7 days", attention: "Tracking and financial reconciliation need attention", traffic: [source("meta", "Meta / Facebook", 42200, 118000, 18800, 610, "Uncertain", "-7.2%", "Poor"), source("affiliate", "Affiliates", 12800, 44100, 10400, 230, "Partial", "-2.4%", "Degraded")], drivers: bullseye.drivers, timeline: [event("tracking", "Jul 25", "Tracking issue detected", "Attribution confidence declined"), event("connector", "Jul 28", "Connector degradation", "Financial Evidence became partial")], intelligence: [{ id: "tracking", observation: "Margin has declined for three consecutive days.", comparison: "Observed Profit is 5.8% below the prior period.", reason: "Tracking and financial Evidence are partial.", recommendation: "Resolve Evidence gaps before reallocating budget.", evidence: ["Tracking Diagnostics", "Connector health", "Pending settlement Evidence"] }] }),
];

export type SearchHit = { id: string; type: string; value: string; offerId: string; objectType: string; title: string; subtitle: string };
export const offerSearchHits: SearchHit[] = [
  { id: "s1", type: "Offer", value: "Bullseye", offerId: "bullseye", objectType: "Offer", title: "Bullseye", subtitle: "Offer · Bullseye Health" },
  { id: "s2", type: "Offer URL", value: "bullseye.health/restore", offerId: "bullseye", objectType: "Offer URL", title: "Restore Offer URL", subtitle: "Bullseye · active" },
  { id: "s3", type: "Campaign", value: "Meta Scale Q3", offerId: "bullseye", objectType: "Campaign", title: "Meta Scale Q3", subtitle: "Bullseye · Meta / Facebook" },
  { id: "s4", type: "Affiliate", value: "Affiliate 104", offerId: "valuerx-individual", objectType: "Affiliate", title: "Affiliate 104", subtitle: "ValueRx Individual" },
  { id: "s5", type: "Order ID", value: "TK-10482", offerId: "bullseye", objectType: "Order", title: "Order TK-10482", subtitle: "Bullseye · John Smith" },
  { id: "s6", type: "Customer Email", value: "mary@example.com", offerId: "petes-pasta", objectType: "Customer", title: "Mary Johnson", subtitle: "Pete’s Pasta · repeat Customer" },
  { id: "s7", type: "Everflow Transaction ID", value: "ef_offer_771", offerId: "valuerx-individual", objectType: "Attribution Decision", title: "Everflow conversion", subtitle: "ValueRx Individual · Affiliate" },
  { id: "s8", type: "Facebook Click ID", value: "IwARoffer88", offerId: "manifest-rx", objectType: "Identifier", title: "Facebook click", subtitle: "Manifest RX · tracking issue" },
  { id: "s9", type: "Google Click ID", value: "Cj0KCQjOffer91", offerId: "valuerx-family", objectType: "Identifier", title: "Google click", subtitle: "ValueRx Family · Google" },
  { id: "s10", type: "Creative", value: "Family Bundle V3", offerId: "valuerx-family", objectType: "Creative", title: "Family Bundle V3", subtitle: "ValueRx Family · Google" },
  { id: "s11", type: "Landing Page", value: "valuerx.com/family", offerId: "valuerx-family", objectType: "Landing Page", title: "Family Offer Landing Page", subtitle: "ValueRx Family · active" },
];
export function searchOffers(query: string) { const q = query.trim().toLowerCase(); return q ? offerSearchHits.filter(h => [h.type, h.value, h.title, h.subtitle].some(v => v.toLowerCase().includes(q))) : offerSearchHits.slice(0, 6); }
export function detectOfferIdentifier(value: string) { const q = value.trim(); if (!q) return "Paste any Offer evidence"; if (q.includes("@")) return "Customer Email"; if (/^TK-/i.test(q)) return "Order ID"; if (/^ef_/i.test(q)) return "Everflow Transaction ID"; if (/^IwAR/i.test(q)) return "Facebook Click ID"; if (/^Cj0/i.test(q)) return "Google Click ID"; if (q.includes("/") || q.includes(".")) return "URL or Landing Page"; return "Offer, Campaign, Affiliate, or Creative"; }
