import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { ACCUFY_PRESENTATION } from "../lib/investigations/accufy-reference";
import { OTO2_CHILD_PRESENTATION } from "../lib/investigations/oto2-selective-reference";
import { buildInvestigationInspections } from "../lib/investigations/inspection-presentation";
import { inspectionHref, withoutInspectionHref } from "../lib/investigations/inspection-state";
import { assertClientSafePresentation, type SafeInvestigationDetail } from "../lib/investigations/presentation";

function detail(child=false):Omit<SafeInvestigationDetail,"inspections">{return {id:child?"child":"parent",title:child?"OTO2 Selective Dispute Analysis":"Accufy Chargeback Investigation",organization:"Accufy",type:"chargeback",status:"completed_with_warnings",period:"period",primarySignal:"signal",evidenceQuality:"limited",lastUpdated:"2026-08-08T00:00:00Z",version:child?1:3,parentInvestigationId:child?"parent":null,freshnessStatus:"current",runId:"run",warnings:[],versions:{commerce:"commerce-v1",journey:"journey-v2",dispute:"dispute-v1",reason:"reason-v1",cohort:"cohort-v3",algorithm:child?"oto2-selective-v1":"accufy-investigation-v3"},presentation:child?OTO2_CHILD_PRESENTATION:ACCUFY_PRESENTATION,parent:child?{id:"parent",title:"Accufy Chargeback Investigation",question:"Why?",version:3,branchSignal:"OTO2 elevated",branchReason:"Narrow question"}:null,branches:child?[]:[{id:"child",title:"OTO2 Selective Dispute Analysis",organization:"Accufy",type:"chargeback",status:"completed_with_warnings",period:"period",primarySignal:"signal",evidenceQuality:"limited",lastUpdated:"2026-08-08T00:00:00Z",version:1,parentInvestigationId:"parent",freshnessStatus:"current"}]};}

test("authorized presentation builds the bounded inspection taxonomy",()=>{const catalog=buildInvestigationInspections(detail());assert.deepEqual(new Set(catalog.map(item=>item.type)),new Set(["product","cohort","finding","evidence-quality","journey","dispute","freshness"]));for(const target of [["product","oto2-platinum"],["product","push-button-system"],["cohort","nandi"],["finding","multi-charge"],["evidence-quality","eligible-order-attribution"],["journey","everflow-click"],["dispute","lost"],["freshness","investigation-freshness"]])assert.ok(catalog.some(item=>item.type===target[0]&&item.key===target[1]),target.join(":"));});
test("OTO2 inspection links the existing child without creating one",()=>{const item=buildInvestigationInspections(detail()).find(entry=>entry.type==="product"&&entry.key==="oto2-platinum");assert.equal(item?.relatedInvestigation?.id,"child");assert.match(item?.relatedInvestigation?.context||"",/Version 3/);});
test("child catalog retains affected/control cohorts and Evidence ceiling",()=>{const catalog=buildInvestigationInspections(detail(true));for(const key of ["affected","control","both-disputed","main-only"])assert.ok(catalog.some(item=>item.type==="cohort"&&item.key===key));assert.ok(catalog.some(item=>item.key==="historical-evidence-ceiling"));});
test("cohort drawer groups each metric with definitions, values, difference, and interpretation",()=>{const drawer=buildInvestigationInspections(detail(true)).find(item=>item.type==="cohort"&&item.key==="oto2-only-v-neither");assert.deepEqual(drawer?.cohortDefinitions,[{label:"Affected",sample:"12 Journeys",definition:"Buyers who purchased Main + OTO2 and disputed only the OTO2 charge."},{label:"Control",sample:"156 Journeys",definition:"Comparable Main + OTO2 buyers where neither charge was disputed."}]);assert.equal(drawer?.comparisons?.length,OTO2_CHILD_PRESENTATION.comparison.length);assert.deepEqual(drawer?.comparisons?.[0],{metric:"Time from Main charge to OTO2",definition:"Median for each cohort",affected:"6.02 min",control:"6.53 min",difference:"−0.51 min",differenceExplanation:"Affected is lower than control.",interpretation:"No material difference in how quickly buyers reached the OTO2 charge.",limitation:undefined});assert.match(drawer?.comparisonSummary?.statement||"",/Timing, charge count, dominant Product sequence, total amount, traffic fingerprint, refunds, prior history, and dispute lag/);});
test("sparse comparisons explain limitations instead of presenting Fragile or Small as deltas",()=>{const comparisons=buildInvestigationInspections(detail(true)).find(item=>item.key==="oto2-only-v-neither")?.comparisons||[],refund=comparisons.find(item=>item.metric==="Any Refund"),prior=comparisons.find(item=>item.metric==="Buyer had a prior Order");assert.equal(refund?.affected,"1 / 12");assert.equal(refund?.control,"6 / 156");assert.equal(refund?.difference,undefined);assert.match(refund?.limitation||"",/Too few Refunds/);assert.equal(prior?.difference,undefined);assert.match(prior?.limitation||"",/does not meaningfully distinguish/);assert.doesNotMatch(JSON.stringify(comparisons.map(item=>item.difference)),/Fragile|Small/);});
test("comparison renderer keeps affected, control, and difference in one responsive unit before provenance",()=>{const source=readFileSync(new URL("../components/investigations/investigation-inspection-drawer.tsx",import.meta.url),"utf8");assert.match(source,/inspection\.comparisons\.map\(comparison=>[\s\S]*ComparisonValue label="Affected"[\s\S]*ComparisonValue label="Control"[\s\S]*ComparisonValue label="Difference"/);assert.match(source,/grid-cols-1 gap-3 sm:grid-cols-3/);assert.ok(source.indexOf("inspection.comparisonSummary")<source.indexOf("Safe provenance"));});
test("inspection DTO excludes PII and raw Evidence",()=>{const catalog=buildInvestigationInspections(detail());assert.doesNotThrow(()=>assertClientSafePresentation(catalog));assert.doesNotMatch(JSON.stringify(catalog),/customer_email|phone|ip_address|raw user agent|raw_payload|storage_reference|ciphertext|api_key/i);});
test("deep-link state preserves unrelated query state and closes safely",()=>{const opened=inspectionHref("/investigations/parent","version=3",{type:"product",key:"oto2-platinum"});assert.equal(opened,"/investigations/parent?version=3&inspect=product&key=oto2-platinum");assert.equal(withoutInspectionHref("/investigations/parent","version=3&inspect=product&key=oto2-platinum"),"/investigations/parent?version=3");});
test("drawer source includes modal focus, Escape, restoration, responsive sheet, and browser Back",()=>{const source=readFileSync(new URL("../components/investigations/investigation-inspection-drawer.tsx",import.meta.url),"utf8"),css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8");for(const expected of [/role="dialog"/,/aria-modal="true"/,/event\.key==="Escape"/,/triggerRef\.current\?\.focus/,/router\.back\(\)/,/document\.body\.style\.overflow/,/inert=/])assert.match(source,expected);assert.match(css,/sm:max-w-\[520px\]/);});
test("drawer remains a read-only presentation surface",()=>{const source=readFileSync(new URL("../components/investigations/investigation-inspection-drawer.tsx",import.meta.url),"utf8");assert.doesNotMatch(source,/fetch\(|insert\(|update\(|createInvestigation|refreshInvestigation|commerce_evidence_records|everflow_conversion_events/);const repository=readFileSync(new URL("../lib/investigations/server-repository.ts",import.meta.url),"utf8");assert.match(repository,/authorizeInvestigationAccess/);assert.match(repository,/buildInvestigationInspections/);});
test("Investigation targets expose restrained keyboard triggers",()=>{const source=readFileSync(new URL("../components/investigations/investigation-experience.tsx",import.meta.url),"utf8");for(const expected of [/InspectionTrigger/,/type="evidence-quality"/,/type="journey"/,/type="finding"/,/type="cohort"/,/type="dispute"/,/type="freshness"/,/\?"product":"cohort"/])assert.match(source,expected);});
