import assert from"node:assert/strict";import test from"node:test";import{readFileSync}from"node:fs";
const route=readFileSync(new URL("../app/api/actions/shopify/controlled-webhook-proof/route.ts",import.meta.url),"utf8"),lib=readFileSync(new URL("../lib/commerce/shopify-webhook-registration.ts",import.meta.url),"utf8");
test("M11 Shopify proof is hard-bound to approved Stem Labs target and one topic",()=>{assert.match(route,/izkfvg-k0\.myshopify\.com/);assert.match(route,/ed3bb791-4cc2-4624-a887-3a6518018316/);assert.match(route,/\["ORDERS_CREATE","REFUNDS_CREATE"\]/);});
test("M11 Shopify proof requires actions.execute same-origin and explicit target confirmation",()=>{assert.match(route,/requirePermission\(resolution\.session,"actions\.execute"\)/);assert.match(route,/sameOrigin\(request\)/);assert.match(route,/body\.confirm!==true/);assert.match(route,/body\.shopDomain!==CONTROLLED_DOMAIN/);});
test("M11 Shopify proof refuses preexisting controlled topic rather than deleting customer state",()=>{assert.match(route,/created\.decision!=="created"/);assert.match(route,/controlled_topic_already_exists/);});
test("M11 bounded create verifies provider read-back before rollback",()=>{assert.match(lib,/creation could not be verified by read-back/);assert.match(lib,/decision:"created"/);assert.match(route,/verifiedPresent/);});
test("M11 proof deletes only subscription created in same execution and reports net-zero config",()=>{assert.match(route,/subscription:created\.subscription/);assert.match(route,/verifiedAbsent/);assert.match(route,/netProviderConfigurationMutation:rollback\.verifiedAbsent\?false:true/);});

test("M11 Shopify proof selects only an unoccupied TraceKit topic and fails closed if none exists",()=>{assert.match(route,/listTraceKitShopifyWebhookSubscriptions/);assert.match(route,/find\(t=>!occupied\.includes\(t\)\)/);assert.match(route,/no_disposable_tracekit_topic/);assert.match(route,/providerMutation:false/);});
