import assert from"node:assert/strict";import test from"node:test";import{assessEverflowSyncRemediationEligibility}from"../lib/mcp/m17-everflow-sync-remediation";
const base:any={id:"ef-1",provider:"everflow",status:"connected",freshness:{status:"current"},diagnostics:{activeRun:false,stalled:false,failedCheckpoints:0,pendingCheckpoints:0},syncRuns:[{status:"completed",completedAt:"2026-10-02T04:25:34Z"}]};
test("M17 Everflow sync remediation is not offered for healthy state",()=>{const x=assessEverflowSyncRemediationEligibility(base);assert.equal(x.state,"healthy");assert.equal(x.eligible,false);});
test("M17 Everflow sync remediation is eligible for retained degraded evidence without active run",()=>{const x=assessEverflowSyncRemediationEligibility({...base,freshness:{status:"degraded"}});assert.equal(x.state,"eligible");assert.equal(x.eligible,true);});
test("M17 Everflow sync remediation fails closed for active or stalled run",()=>{for(const diagnostics of[{...base.diagnostics,activeRun:true},{...base.diagnostics,stalled:true}]){const x=assessEverflowSyncRemediationEligibility({...base,freshness:{status:"failed"},diagnostics});assert.equal(x.state,"blocked");assert.equal(x.eligible,false);}});
test("M17 Everflow sync remediation fails closed outside connected Everflow",()=>{assert.equal(assessEverflowSyncRemediationEligibility({...base,provider:"shopify",freshness:{status:"failed"}}).eligible,false);assert.equal(assessEverflowSyncRemediationEligibility({...base,status:"degraded",freshness:{status:"failed"}}).eligible,false);});

test("M17 recovered historical failed checkpoints do not trigger remediation",()=>{const x=assessEverflowSyncRemediationEligibility({...base,diagnostics:{...base.diagnostics,failedCheckpoints:22}});assert.equal(x.state,"healthy");assert.equal(x.eligible,false);assert.match(x.reason,/Historical failed checkpoints remain/);assert.equal(x.evidence.latestRunStatus,"completed");});
test("M17 latest failed run remains eligible even before freshness degrades",()=>{const x=assessEverflowSyncRemediationEligibility({...base,syncRuns:[{status:"failed",completedAt:null}]});assert.equal(x.state,"eligible");assert.equal(x.eligible,true);});
