import assert from"node:assert/strict";import test from"node:test";import{evaluateAuthorizationConsumption,type ExecutionEnvelope,type AuthorizationConsumptionRecord}from"../lib/mcp/journey-repository";
const envelope:ExecutionEnvelope={version:1,state:"authorized",envelopeIdentity:"exec-v1-abc",organizationId:"org",planIdentity:"plan",target:{customerId:"c",journeyId:"j",boundaries:[]},operation:{type:"inspect_evidence",parameters:{}},evidence:{supportingEventIds:[],uncertainty:[]},requiredPermission:"actions.execute",confirmation:{confirmationId:"confirm",confirmedAt:"2026-09-26T21:00:00Z",confirmedPlanIdentity:"plan",confirmedCustomerId:"c",confirmedJourneyId:"j"},preconditions:[],expectedPostconditions:[],verification:[],rollback:{available:false,reason:"none"},idempotencyKey:"idem-1",auditCorrelationId:"audit-1",createdAt:"2026-09-26T21:00:00Z",expiresAt:"2026-09-26T22:00:00Z",executionAvailable:false,stateReasons:[]};
const auth:AuthorizationConsumptionRecord={authorizationId:"auth-1",envelopeIdentity:"exec-v1-abc",idempotencyKey:"idem-1",state:"available",consumedAt:null,consumptionId:null,auditCorrelationId:"audit-1"};
const req=(a=auth,x:any={})=>({authorization:a,envelope,requestedEnvelopeIdentity:"exec-v1-abc",requestedIdempotencyKey:"idem-1",requestedAt:"2026-09-26T21:30:00Z",consumptionId:"consume-1",...x});
test("M10 authorization can be consumed once for exact immutable envelope",()=>{const x=evaluateAuthorizationConsumption(req());assert.equal(x.decision,"consume");assert.equal(x.next.state,"consumed");assert.equal(x.next.consumptionId,"consume-1");assert.equal(x.executionAvailable,false);});
test("M10 exact retry after consumption is replay-safe and does not consume twice",()=>{const first=evaluateAuthorizationConsumption(req());const retry=evaluateAuthorizationConsumption(req(first.next,{consumptionId:"consume-2"}));assert.equal(retry.decision,"replay_same_result");assert.equal(retry.next.consumptionId,"consume-1");});
test("M10 consumed authorization cannot cross envelope or idempotency boundary",()=>{const consumed=evaluateAuthorizationConsumption(req()).next;assert.equal(evaluateAuthorizationConsumption(req(consumed,{requestedEnvelopeIdentity:"exec-v1-other"})).decision,"reject");assert.equal(evaluateAuthorizationConsumption(req(consumed,{requestedIdempotencyKey:"idem-other"})).decision,"reject");});
test("M10 expired or invalid envelope fails closed",()=>{assert.equal(evaluateAuthorizationConsumption(req(auth,{requestedAt:"2026-09-26T23:00:00Z"})).decision,"reject");assert.equal(evaluateAuthorizationConsumption(req(auth,{requestedEnvelopeIdentity:"wrong"})).next.state,"invalidated");});
test("M10 consumption semantics remain a decision model with no execution primitive",()=>{const s=JSON.stringify(evaluateAuthorizationConsumption(req()));assert.doesNotMatch(s,/providerWrite|executeAction|mutationToken|executedAt/i);});
