import assert from "node:assert/strict";
import test from "node:test";
import { classifySelectiveOutcome, compareBinary, elapsedBucket, fisherExactTwoSided, historyScope, journeyOutcome, mainToOto2Minutes, normalizeSelectiveReason, percentile, productSequence, qualityForSample, summarize, validateSelectiveJourney, type FindingClassification, type SelectiveJourney } from "../lib/investigations/oto2-selective-analysis";

const order=(id:string,title:string,minute:number,disputed=false,organizationId="org-a")=>({id,organizationId,connectionId:"connection-a",personId:"person-a",title,occurredAt:`2026-05-01T00:${String(minute).padStart(2,"0")}:00Z`,amount:title==="OTO2-platinum"?299:106,evidenceId:`evidence-${id}`,disputed});
const journey=(orders:ReturnType<typeof order>[],id="journey-a"):SelectiveJourney=>({id,organizationId:"org-a",connectionId:"connection-a",orders});

test("cohort construction requires Main and OTO2 in one tenant-scoped evidenced Journey",()=>{const value=journey([order("main","Push Button System",0),order("oto","OTO2-platinum",6)]);assert.doesNotThrow(()=>validateSelectiveJourney(value,new Set()));assert.throws(()=>validateSelectiveJourney(journey([order("main","Push Button System",0)]),new Set()));assert.throws(()=>validateSelectiveJourney(journey([order("main","Push Button System",0),order("oto","OTO2-platinum",6,false,"org-b")]),new Set()),/tenant/);});
test("exclusive affected and clean-control outcomes remain distinct",()=>{assert.equal(classifySelectiveOutcome(false,true),"oto2_only");assert.equal(classifySelectiveOutcome(false,false),"neither");assert.equal(classifySelectiveOutcome(true,true),"both");assert.equal(classifySelectiveOutcome(true,false),"main_only");assert.equal(journeyOutcome(journey([order("main","Push Button System",0),order("oto","OTO2-platinum",6,true)])),"oto2_only");});
test("an Order cannot be claimed by two Journeys",()=>{const claimed=new Set<string>(),first=journey([order("main","Push Button System",0),order("oto","OTO2-platinum",6)]);validateSelectiveJourney(first,claimed);assert.throws(()=>validateSelectiveJourney({...first,id:"journey-b"},claimed),/multiple Journeys/);});
test("charge sequencing and elapsed buckets are deterministic",()=>{const value=journey([order("oto","OTO2-platinum",6),order("main","Push Button System",0),order("oto1","OTO1-gold",3)]);assert.deepEqual(productSequence(value),["Push Button System","OTO1-gold","OTO2-platinum"]);assert.equal(mainToOto2Minutes(value),6);assert.equal(elapsedBucket(6),"5-10m");});
test("charge-count strata retain small denominators",()=>{const rows=[2,3,3,3];assert.equal(rows.filter(value=>value===2).length,1);assert.equal(rows.filter(value=>value===3).length,3);assert.equal(qualityForSample(12),"limited");});
test("numeric summaries use distributions rather than means alone",()=>{assert.deepEqual(summarize([4,6,7,8]),{n:4,mean:6.25,p25:5.5,median:6.5,p75:7.25,p90:7.7});assert.equal(percentile([100,1,2],.5),2);});
test("refund comparison retains numerator, denominator, and exact small-sample result",()=>{const refunded={...order("main","Push Button System",0),refunded:true};assert.equal(refunded.refunded,true);assert.equal(refunded.evidenceId,"evidence-main");const comparison=compareBinary(1,12,6,156);assert.equal(comparison.affectedN,12);assert.equal(comparison.controlN,156);assert.ok(comparison.exactP>.4);});
test("reason families preserve recognition distinctions and exact comparison",()=>{assert.equal(normalizeSelectiveReason("Fraud Card Absent Environment"),"fraud_or_unauthorized");assert.equal(normalizeSelectiveReason("duplicate"),"duplicate");assert.equal(normalizeSelectiveReason("unrecognized"),"unrecognized_or_cardholder_dispute");const p=fisherExactTwoSided(5,7,5,36);assert.ok(p>0&&p<.1);assert.equal(fisherExactTwoSided(0,0,0,0),1);});
test("customer history outside the Everflow window stays Commerce-only",()=>{assert.equal(historyScope("2026-03-01T00:00:00Z","2026-04-01T04:04:16Z","2026-08-07T21:30:53Z"),"commerce_history_only");assert.equal(historyScope("2026-06-01T00:00:00Z","2026-04-01T04:04:16Z","2026-08-07T21:30:53Z"),"inside_attribution_window");});
test("affected n=12 cannot be promoted beyond limited quality",()=>assert.equal(qualityForSample(12,1),"limited"));
test("finding taxonomy has no causal classification",()=>{const values:FindingClassification[]=["observation","correlation","negative_finding","hypothesis"];assert.deepEqual(values,["observation","correlation","negative_finding","hypothesis"]);});
test("analysis output is replay deterministic",()=>{const value=journey([order("main","Push Button System",0),order("oto","OTO2-platinum",6,true)]);assert.equal(JSON.stringify({outcome:journeyOutcome(value),sequence:productSequence(value),minutes:mainToOto2Minutes(value)}),JSON.stringify({outcome:journeyOutcome(value),sequence:productSequence(value),minutes:mainToOto2Minutes(value)}));});
