import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {execFileSync} from "node:child_process";
import {mkdtempSync,readFileSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join,resolve} from "node:path";
import test from "node:test";
import vm from "node:vm";
const ui=resolve(import.meta.dirname,".."),release=resolve(ui,"sdk/releases/1.0.0"),artifact=readFileSync(resolve(release,"tracekit-journey.min.js")),manifest=JSON.parse(readFileSync(resolve(release,"manifest.json"),"utf8"));
test("release metadata and integrity are deterministic",()=>{assert.equal(manifest.version,"1.0.0");assert.equal(manifest.byteSize,artifact.byteLength);assert.equal(manifest.sha256,createHash("sha256").update(artifact).digest("hex"));assert.equal(manifest.sri,`sha384-${createHash("sha384").update(artifact).digest("base64")}`);assert.equal(manifest.sourceMap,"none");assert.match(manifest.sourceCommit,/^[0-9a-f]{40}$/)});
test("two clean builds produce identical bytes",()=>{const a=mkdtempSync(join(tmpdir(),"tkid-sdk-a-")),b=mkdtempSync(join(tmpdir(),"tkid-sdk-b-"));try{for(const out of[a,b])execFileSync(process.execPath,["scripts/build-tkid-sdk.mjs","--output-root",out],{cwd:ui,env:{...process.env,TRACEKIT_SDK_SOURCE_COMMIT:manifest.sourceCommit}});assert.deepEqual(readFileSync(join(a,"tracekit-journey.min.js")),readFileSync(join(b,"tracekit-journey.min.js")));assert.deepEqual(readFileSync(join(a,"manifest.json")),readFileSync(join(b,"manifest.json")))}finally{rmSync(a,{recursive:true,force:true});rmSync(b,{recursive:true,force:true})}});
test("artifact is generic, CSP-safe, and canonical",()=>{const text=artifact.toString("utf8");assert.match(text,/1\.0\.0/);assert.doesNotMatch(text,/EcoWatt|buyecowatt|workers\.dev|39d895f9|5f1de64a|b0d5abc3|b784b15c/i);assert.doesNotMatch(text,/eval\(|new Function|localStorage|document\.cookie|innerHTML|outerHTML/);assert.equal(manifest.canonicalApiEndpoint,"https://api.trace-kit.io")});
function context(handler:()=>Promise<any>){const store=new Map<string,string>(),ctx:any={URL,Date,JSON,Promise,Set,Map,TypeError,Error,crypto:{randomUUID:()=>"00000000-0000-4000-8000-000000000001"},location:{pathname:"/proof"},sessionStorage:{getItem:(k:string)=>store.get(k)||null,setItem:(k:string,v:string)=>store.set(k,v),removeItem:(k:string)=>store.delete(k)},fetch:handler,window:null};ctx.window=ctx;return ctx}
test("script load and initialization are idempotent",()=>{const ctx=context(async()=>({ok:false,json:async()=>({code:"ingestion_stopped"})}));vm.runInNewContext(artifact.toString("utf8"),ctx);vm.runInNewContext(artifact.toString("utf8"),ctx);assert.equal(ctx.TraceKitJourney.version,"1.0.0");const config={endpoint:"https://api.trace-kit.io",publicSourceId:"tksrc_stage1_test",privacyMode:"essential",autoPageView:false};assert.equal(ctx.TraceKitJourney.init(config),ctx.TraceKitJourney.init(config))});
test("terminal M1 response fails closed without retry",async()=>{const errors:any[]=[];let calls=0;const ctx=context(async()=>{calls++;return{ok:false,json:async()=>({code:"proof_expired"})}});vm.runInNewContext(artifact.toString("utf8"),ctx);const client=ctx.TraceKitJourney.init({endpoint:"https://api.trace-kit.io",publicSourceId:"tksrc_stage1_test",onError:(e:any)=>errors.push(e)});assert.equal(await client.startJourney(),null);assert.equal(await client.startJourney(),null);assert.equal(calls,1);assert.equal(errors[0].code,"proof_expired")});
test("successful essential bootstrap persists only session identity and respects autoPageView false",async()=>{const requests:any[]=[];const ctx=context(async(url:string,init:any)=>{requests.push({url,init});if(url.endsWith("/bootstrap"))return{ok:true,json:async()=>({journey_id:"journey",browser_session_id:"session",journey_expires_at:"2999-01-01T00:00:00.000Z",browser_session_expires_at:"2999-01-01T00:00:00.000Z"})};return{ok:true,json:async()=>({ok:true})}});vm.runInNewContext(artifact.toString("utf8"),ctx);const client=ctx.TraceKitJourney.init({endpoint:"https://api.trace-kit.io",publicSourceId:"tksrc_stage1_test",privacyMode:"essential",autoPageView:false});assert.equal((await client.startJourney()).journeyId,"journey");assert.equal(requests.filter(request=>request.url.endsWith("/bootstrap")).length,1);const events=requests.filter(request=>request.url.endsWith("/events")).flatMap(request=>JSON.parse(request.init.body).events);assert.deepEqual(events.map((event:any)=>event.event_name),["journey_started"]);assert.equal(events[0].privacy_mode,"essential");assert.equal(await client.startJourney().then((value:any)=>value.browserSessionId),"session");assert.equal(requests.filter(request=>request.url.endsWith("/bootstrap")).length,1)});
test("bundle contains no implicit behavioral, fingerprint, or referrer collection",()=>{const text=artifact.toString("utf8");for(const prohibited of["email","phone","address","userAgent","referrer","utm_","querySelector","document.cookie","localStorage"])assert.equal(text.includes(prohibited),false)});
test("configuration validation fails closed",()=>{const ctx=context(async()=>({ok:true,json:async()=>({})}));vm.runInNewContext(artifact.toString("utf8"),ctx);assert.throws(()=>ctx.TraceKitJourney.init({endpoint:"http://api.trace-kit.io",publicSourceId:"bad"}),/Invalid TraceKit Journey configuration/)});
