import assert from"node:assert/strict";import test from"node:test";import{readFileSync}from"node:fs";
const root=new URL("..",import.meta.url),source=(p:string)=>readFileSync(new URL(p,root),"utf8");
const workList=source("app/api/work-items/route.ts"),workDetail=source("app/api/work-items/[...workItemPath]/route.ts"),notifications=source("app/api/notifications/route.ts"),notificationDetail=source("app/api/notifications/[...notificationPath]/route.ts");
test("WS-017 Intelligence browser proxies resolve authenticated organization scope",()=>{for(const s of[workList,workDetail,notifications,notificationDetail]){assert.match(s,/resolveApplicationSession/);assert.match(s,/activeOrganization/);assert.match(s,/requirePermission/);}});
test("WS-017 read routes overwrite caller workspace scope",()=>{assert.match(workList,/searchParams\.set\("workspace_id",scope\.workspaceId\)/);assert.match(notifications,/searchParams\.set\("workspace_id",resolution\.session\.activeOrganization\.id\)/);assert.match(workDetail,/searchParams\.set\("workspace_id",scope\.workspaceId\)/);assert.match(notificationDetail,/workspace_id=\$\{encodeURIComponent\(workspaceId\)\}/);});
test("WS-017 lifecycle mutations require actions.execute",()=>{assert.match(workDetail,/authorizedScope\("actions\.execute"\)/);assert.match(notificationDetail,/scope\("actions\.execute"\)/);});
test("WS-017 Work Item mutation strips caller identity and overwrites actor/workspace",()=>{assert.match(workDetail,/workspace_id:scope\.workspaceId,actor_id:scope\.actorId/);for(const key of["workspaceId","actorId","user_id","userId"])assert.match(workDetail,new RegExp(`delete safeBody\\.${key}`));});
test("WS-017 Notification mutation forwards only server-derived workspace",()=>{assert.match(notificationDetail,/JSON\.stringify\(\{workspace_id:workspaceId\}\)/);assert.doesNotMatch(notificationDetail,/req\.json|body\?\.workspace|body\?\.user|body\?\.actor/);});
test("WS-017 unauthorized proxy access fails closed without exposing authorization detail",()=>{for(const s of[workList,workDetail,notifications,notificationDetail]){assert.match(s,/resource_unavailable/);assert.doesNotMatch(s,/access_denied|permission_required|organization_id_required/);}});
