import"server-only";import{supabaseAuthHeaders}from"@/lib/commerce/supabase-auth";import type{TraceKitNotification}from"@/lib/notifications";
function cfg(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,""),key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("action_notification_storage_unavailable");return{url,key};}
async function rest(path:string,init:RequestInit={}){const{url,key}=cfg(),r=await fetch(`${url}/rest/v1/${path}`,{...init,cache:"no-store",headers:{...supabaseAuthHeaders(key),...(init.headers||{})}});if(!r.ok)throw new Error("action_notification_storage_failed");return r.status===204?null:r.json();}
const nid=(kind:string,id:string)=>`action_notification:${kind}:${id}`;
function base(args:{id:string;org:string;created:string;severity:"warning"|"critical";title:string;summary:string;recommended:string;kind:string;evidence:Record<string,unknown>;resolved?:boolean}):TraceKitNotification{return{id:args.id,type:"platform",lifecycle_state:args.resolved?"resolved":"degraded",severity:args.severity,status:args.resolved?"resolved":"unread",title:args.title,summary:args.summary,created_at:args.created,resolved_at:args.resolved?args.created:null,read_at:null,dismissed_at:null,deep_link:"/activity",recommended_action:args.recommended,workspace_id:args.org,health_finding_id:`governed_action:${args.kind}`,why_it_matters:"Governed actions remain human-controlled and every material lifecycle state must be visible.",evidence:args.evidence,related_metrics:{},timeline:[{label:args.title,timestamp:args.created,status:args.resolved?"resolved":"detected",summary:args.summary}],metadata:{source:"governed_action",action_notification_kind:args.kind,delivery_channels:["notification_center"]}};}
export async function listGovernedActionNotifications(organizationId:string){
 const q=new URLSearchParams({organization_id:`eq.${organizationId}`,select:"intent_id,operation,plan_identity,audit_correlation_id,issued_at,expires_at",order:"issued_at.desc",limit:"100"}),intents=await rest(`mcp_action_intents?${q}`)as any[];
 const ids=intents.map(x=>x.intent_id);if(!ids.length)return[];
 const inIds=encodeURIComponent(`(${ids.join(",")})`);
 const [confirmations,results,recovery,states]=await Promise.all([
  rest(`mcp_action_confirmations?organization_id=eq.${organizationId}&intent_id=in.${inIds}&select=confirmation_id,intent_id,confirmed_at`) as Promise<any[]>,
  rest(`mcp_action_execution_results?organization_id=eq.${organizationId}&select=id,audit_correlation_id,result,created_at&order=created_at.desc&limit=100`) as Promise<any[]>,
  rest(`mcp_shopify_mutation_recovery?organization_id=eq.${organizationId}&intent_id=in.${inIds}&select=intent_id,state,created_verified,rollback_verified,updated_at`) as Promise<any[]>,
  rest(`mcp_action_notification_states?organization_id=eq.${organizationId}&select=notification_id,read_at,dismissed_at`) as Promise<any[]>,
 ]);
 const confirmed=new Set(confirmations.map(x=>x.intent_id)),byAudit=new Map(results.map(x=>[x.audit_correlation_id,x])),byRecovery=new Map(recovery.map(x=>[x.intent_id,x])),state=new Map(states.map(x=>[x.notification_id,x])),out:TraceKitNotification[]=[];
 for(const i of intents){const execution=byAudit.get(i.audit_correlation_id),rec=byRecovery.get(i.intent_id);
  if(!confirmed.has(i.intent_id)&&new Date(i.expires_at).getTime()>Date.now())out.push(base({id:nid("awaiting_approval",i.intent_id),org:organizationId,created:i.issued_at,severity:"warning",title:"Action awaiting approval",summary:`${i.operation} is prepared and requires explicit human confirmation before execution.`,recommended:"Review the exact target and approve only if the proposed effect is intended.",kind:"awaiting_approval",evidence:{intent_id:i.intent_id,operation:i.operation,plan_identity:i.plan_identity}}));
  if(execution){const status=String(execution.result?.status||"").toLowerCase(),failed=status&&status!=="completed"&&status!=="success";if(failed)out.push(base({id:nid("execution_failure",execution.id),org:organizationId,created:execution.created_at,severity:"critical",title:"Governed action execution failed",summary:`${i.operation} did not complete successfully.`,recommended:"Inspect the durable execution evidence and recovery state before retrying.",kind:"execution_failure",evidence:{intent_id:i.intent_id,operation:i.operation,execution_id:execution.id,status}}));}
  if(rec&&rec.created_verified&&!rec.rollback_verified)out.push(base({id:nid("verification_failure",i.intent_id),org:organizationId,created:rec.updated_at,severity:"critical",title:"Governed action verification incomplete",summary:"The controlled Shopify proof created and verified its disposable object but rollback verification is not complete.",recommended:"Do not repeat execution. Follow the recovery runbook and verify provider absence.",kind:"verification_failure",evidence:{intent_id:i.intent_id,operation:i.operation,recovery_state:rec.state}}));
 }
 return out.map(n=>{const s=state.get(n.id);if(!s)return n;return{...n,status:s.dismissed_at?"dismissed":s.read_at?"read":n.status,read_at:s.read_at||null,dismissed_at:s.dismissed_at||null};}).sort((a,b)=>b.created_at.localeCompare(a.created_at));
}
export async function updateGovernedActionNotificationState(organizationId:string,notificationId:string,action:"read"|"dismiss"){const existing=(await listGovernedActionNotifications(organizationId)).find(x=>x.id===notificationId);if(!existing)throw new Error("action_notification_not_found");const now=new Date().toISOString(),body={organization_id:organizationId,notification_id:notificationId,read_at:now,dismissed_at:action==="dismiss"?now:null,updated_at:now};await rest("mcp_action_notification_states?on_conflict=organization_id,notification_id",{method:"POST",headers:{"Content-Type":"application/json","Prefer":"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(body)});return{...existing,status:action==="dismiss"?"dismissed":"read",read_at:now,dismissed_at:action==="dismiss"?now:null};}
