import "server-only";
import { supabaseAuthHeaders } from "@/lib/commerce/supabase-auth";
import type { TraceKitNotification, NotificationSeverity, NotificationStatus } from "@/lib/notifications";
import { assessIntelligenceAction } from "./production-v1-policy";

type Row = Record<string, any>;
type NotificationKind = "awaiting_approval" | "execution_failure" | "verification_failure";
export type GovernedNotificationQuery = { status?: string | null; severity?: string | null; search?: string | null; limit?: number; cursor?: number };

function cfg() { const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("action_notification_storage_unavailable");return{url,key}; }
async function rest(path:string,init:RequestInit={}){const{url,key}=cfg();const response=await fetch(`${url}/rest/v1/${path}`,{...init,cache:"no-store",headers:{...supabaseAuthHeaders(key),...(init.headers||{})}});if(!response.ok)throw new Error("action_notification_storage_failed");const body=await response.text();return body?JSON.parse(body):null;}
const notificationId=(kind:NotificationKind,id:string)=>`action_notification:${kind}:${id}`;
const lifecycleLink=(intentId:string)=>`/activity?intent_id=${encodeURIComponent(intentId)}`;

function notification(input:{id:string;organizationId:string;intentId:string;createdAt:string;severity:Extract<NotificationSeverity,"warning"|"critical">;priority:"high"|"urgent";title:string;summary:string;recommendedAction:string;kind:NotificationKind;evidence:Record<string,unknown>}):TraceKitNotification{return{id:input.id,type:"platform",lifecycle_state:"degraded",severity:input.severity,status:"unread",title:input.title,summary:input.summary,created_at:input.createdAt,resolved_at:null,read_at:null,dismissed_at:null,deep_link:lifecycleLink(input.intentId),recommended_action:input.recommendedAction,workspace_id:input.organizationId,health_finding_id:`governed_action:${input.kind}`,why_it_matters:"Governed actions remain human-controlled and abnormal states require explicit operator awareness.",evidence:input.evidence,related_metrics:{},timeline:[{label:input.title,timestamp:input.createdAt,status:"detected",summary:input.summary}],metadata:{source:"governed_action",action_notification_kind:input.kind,priority:input.priority,intent_id:input.intentId,delivery_channels:["notification_center"]}};}
const durableKey=(...parts:unknown[])=>parts.map(value=>String(value??"")).join("\u001f");
function exactlyOne<T>(rows:T[],label:string):T|null{if(rows.length>1)throw new Error(`action_notification_${label}_ambiguous`);return rows[0]||null;}

export async function listGovernedActionNotifications(organizationId:string):Promise<TraceKitNotification[]>{
 const intentQuery=new URLSearchParams({organization_id:`eq.${organizationId}`,select:"intent_id,operation,plan_identity,audit_correlation_id,issued_at,expires_at",order:"issued_at.desc",limit:"100"});
 const intents=await rest(`mcp_action_intents?${intentQuery}`)as Row[],ids=intents.map(row=>row.intent_id);if(!ids.length)return[];
 const inIds=encodeURIComponent(`(${ids.join(",")})`);
 const[confirmations,authorizations,results,recoveries,states]=await Promise.all([
  rest(`mcp_action_confirmations?organization_id=eq.${organizationId}&intent_id=in.${inIds}&select=confirmation_id,intent_id,confirmed_at`)as Promise<Row[]>,
  rest(`mcp_action_authorizations?organization_id=eq.${organizationId}&select=authorization_id,envelope_identity,idempotency_key,audit_correlation_id,state,consumption_id,created_at&order=created_at.asc&limit=200`)as Promise<Row[]>,
  rest(`mcp_action_execution_results?organization_id=eq.${organizationId}&select=id,envelope_identity,idempotency_key,audit_correlation_id,consumption_id,result,created_at&order=created_at.asc&limit=200`)as Promise<Row[]>,
  rest(`mcp_shopify_mutation_recovery?organization_id=eq.${organizationId}&intent_id=in.${inIds}&select=recovery_id,intent_id,state,created_verified,rollback_verified,updated_at`)as Promise<Row[]>,
  rest(`mcp_action_notification_states?organization_id=eq.${organizationId}&select=notification_id,read_at,dismissed_at`)as Promise<Row[]>,
 ]);
 const confirmed=new Set(confirmations.map(row=>row.intent_id)),stateById=new Map(states.map(row=>[row.notification_id,row])),output:TraceKitNotification[]=[];
 for(const intent of intents){
  const intentId=String(intent.intent_id),operation=String(intent.operation);
  const authorization=exactlyOne(authorizations.filter(row=>row.audit_correlation_id===intent.audit_correlation_id),"authorization");
  const execution=exactlyOne(authorization?results.filter(row=>durableKey(row.envelope_identity,row.idempotency_key,row.audit_correlation_id,row.consumption_id)===durableKey(authorization.envelope_identity,authorization.idempotency_key,authorization.audit_correlation_id,authorization.consumption_id)):[],"execution_result");
  const recovery=exactlyOne(recoveries.filter(row=>row.intent_id===intentId),"recovery");
  if(assessIntelligenceAction(operation).allowed&&!confirmed.has(intentId)&&new Date(intent.expires_at).getTime()>Date.now())output.push(notification({id:notificationId("awaiting_approval",intentId),organizationId,intentId,createdAt:String(intent.issued_at),severity:"warning",priority:"high",title:"Action awaiting approval",summary:`${operation} is prepared and requires explicit human confirmation before execution.`,recommendedAction:"Review the immutable proposal and approve only if the exact target and effect are intended.",kind:"awaiting_approval",evidence:{intent_id:intentId,operation,plan_identity:intent.plan_identity}}));
  if(execution){const status=String(execution.result?.status||"").toLowerCase();if(status&&status!=="completed"&&status!=="success")output.push(notification({id:notificationId("execution_failure",String(execution.id)),organizationId,intentId,createdAt:String(execution.created_at),severity:"critical",priority:"urgent",title:"Governed action execution failed",summary:`${operation} did not complete successfully.`,recommendedAction:"Inspect the durable execution and recovery evidence before attempting any further action.",kind:"execution_failure",evidence:{intent_id:intentId,operation,execution_result_id:execution.id,status}}));}
  if(recovery?.created_verified&&!recovery.rollback_verified)output.push(notification({id:notificationId("verification_failure",String(recovery.recovery_id||intentId)),organizationId,intentId,createdAt:String(recovery.updated_at),severity:"critical",priority:"urgent",title:"Governed action recovery is incomplete",summary:"Provider state may have changed and net-zero rollback has not been proven.",recommendedAction:"Do not repeat execution. Inspect recovery evidence and verify provider absence.",kind:"verification_failure",evidence:{intent_id:intentId,operation,recovery_id:recovery.recovery_id,recovery_state:recovery.state}}));
 }
 return output.map(item=>{const state=stateById.get(item.id);return state?{...item,status:(state.dismissed_at?"dismissed":state.read_at?"read":item.status)as NotificationStatus,read_at:state.read_at||null,dismissed_at:state.dismissed_at||null}:item;}).sort((a,b)=>b.created_at.localeCompare(a.created_at)||a.id.localeCompare(b.id));
}

export async function queryGovernedActionNotifications(organizationId:string,query:GovernedNotificationQuery={}){const all=await listGovernedActionNotifications(organizationId),search=String(query.search||"").trim().toLowerCase(),filtered=all.filter(item=>(!query.status||item.status===query.status)&&(!query.severity||item.severity===query.severity)&&(!search||`${item.title} ${item.summary} ${item.recommended_action}`.toLowerCase().includes(search))),cursor=Math.max(0,Number(query.cursor||0)),limit=Math.min(100,Math.max(1,Number(query.limit||50))),counts={total:filtered.length,unread:filtered.filter(item=>item.status==="unread").length,read:filtered.filter(item=>item.status==="read").length,resolved:0,dismissed:filtered.filter(item=>item.status==="dismissed").length,critical:filtered.filter(item=>item.severity==="critical").length,warning:filtered.filter(item=>item.severity==="warning").length,info:0,healthy:0};return{notifications:filtered.slice(cursor,cursor+limit),counts,next_cursor:cursor+limit<filtered.length?String(cursor+limit):null,has_more:cursor+limit<filtered.length};}

export async function updateGovernedActionNotificationState(organizationId:string,notificationIdValue:string,action:"read"|"dismiss"){const existing=(await listGovernedActionNotifications(organizationId)).find(item=>item.id===notificationIdValue);if(!existing)throw new Error("action_notification_not_found");const now=new Date().toISOString(),body={organization_id:organizationId,notification_id:notificationIdValue,read_at:now,dismissed_at:action==="dismiss"?now:null,updated_at:now};await rest("mcp_action_notification_states?on_conflict=organization_id,notification_id",{method:"POST",headers:{"Content-Type":"application/json","Prefer":"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(body)});return{...existing,status:action==="dismiss"?"dismissed":"read",read_at:now,dismissed_at:body.dismissed_at};}
