import type{TraceKitSessionContext}from"@/lib/identity/persistent-types";import{consumeMcpActionAuthorization,issueMcpActionAuthorization}from"./action-authorization-repository";import{resolveM12PlanCapability}from"./action-capability-registry";import{buildExecutionEnvelope,executeBoundedInspection,verifyBoundedExecution,type ExecutionVerificationEvidence,type GovernedActionPlan}from"./journey-repository";
export type InspectEvidenceOrchestrationInput={plan:GovernedActionPlan;planIdentity:string;confirmation:{confirmationId:string;confirmedAt:string;confirmedPlanIdentity:string;confirmedCustomerId:string;confirmedJourneyId:string|null};authorizationId?:string;requestedAt:string;consumptionId:string;idempotencyKey:string;auditCorrelationId:string;expiresAt:string;verificationEvidence:ExecutionVerificationEvidence[]};
const MAX_CONFIRMATION_AGE_MS=5*60*1000;
export async function orchestrateInspectEvidence(session:TraceKitSessionContext,input:InspectEvidenceOrchestrationInput){
 const capability=resolveM12PlanCapability(input.plan),planPermissionGranted=session.effectivePermissions.includes("customers.view"),executionPermissionGranted=session.effectivePermissions.includes("actions.execute"),confirmedAt=Date.parse(input.confirmation.confirmedAt),requestedAt=Date.parse(input.requestedAt),confirmationFresh=Number.isFinite(confirmedAt)&&Number.isFinite(requestedAt)&&confirmedAt<=requestedAt&&requestedAt-confirmedAt<=MAX_CONFIRMATION_AGE_MS,confirmationValid=Boolean(input.confirmation.confirmationId&&confirmationFresh&&input.confirmation.confirmedPlanIdentity===input.planIdentity&&input.confirmation.confirmedCustomerId===input.plan.target.customerId&&input.confirmation.confirmedJourneyId===input.plan.target.journeyId);
 if(!capability.bound||!planPermissionGranted||!executionPermissionGranted||!confirmationValid)return{status:"rejected" as const,reason:"governance_gate_failed",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:capability.bound},executionAvailable:false as const,providerMutation:false as const};
 const envelope=buildExecutionEnvelope({plan:input.plan,organizationId:session.activeOrganization!.id,planIdentity:input.planIdentity,operation:{type:"inspect_evidence",parameters:{}},confirmation:input.confirmation,createdAt:input.requestedAt,expiresAt:input.expiresAt,idempotencyKey:input.idempotencyKey,auditCorrelationId:input.auditCorrelationId},input.requestedAt);
 if(!capability.executionAvailable)return{status:"rejected" as const,reason:"capability_execution_disabled",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:true},envelope,executionAvailable:false as const,providerMutation:false as const};
 const authorization=input.authorizationId?null:await issueMcpActionAuthorization(envelope),authorizationId=input.authorizationId||authorization!.authorizationId;
 const durable=await consumeMcpActionAuthorization({authorizationId,envelope,requestedAt:input.requestedAt,consumptionId:input.consumptionId}),consumption={decision:durable.decision,reason:"Durable server-side authorization decision.",next:{authorizationId,envelopeIdentity:envelope.envelopeIdentity,idempotencyKey:envelope.idempotencyKey,state:durable.state as any,consumedAt:durable.consumedAt,consumptionId:durable.consumptionId,auditCorrelationId:envelope.auditCorrelationId},executionAvailable:false as const};
 const execution=executeBoundedInspection({envelope,consumption,operation:"inspect_evidence"}),verification=verifyBoundedExecution(execution,input.verificationEvidence,input.requestedAt);
 return{status:execution.status,reason:execution.status==="completed"?"completed":"execution_rejected",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:true},envelope,consumption,execution,verification,executionAvailable:execution.status==="completed",providerMutation:false as const};
}
