import type{TraceKitSessionContext}from"@/lib/identity/persistent-types";import{consumeMcpActionAuthorization,findMcpActionAuthorization,issueMcpActionAuthorization,readMcpActionAuthorization,readMcpActionAuthorizationById}from"./action-authorization-repository";import{persistMcpExecutionResult,readMcpExecutionResult}from"./action-execution-result-repository";import{resolveM12PlanCapability}from"./action-capability-registry";import{buildExecutionEnvelope,executeBoundedInspection,verifyBoundedExecution,type BoundedExecutionResult,type ExecutionVerificationEvidence,type GovernedActionPlan}from"./journey-repository";
export type InspectEvidenceOrchestrationInput={acceptanceProofAuthorized?:boolean;plan:GovernedActionPlan;planIdentity:string;confirmation:{confirmationId:string;confirmedAt:string;confirmedPlanIdentity:string;confirmedCustomerId:string;confirmedJourneyId:string|null};authorizationId?:string;requestedAt:string;consumptionId:string;idempotencyKey:string;auditCorrelationId:string;expiresAt:string;verificationEvidence:ExecutionVerificationEvidence[]};
const MAX_CONFIRMATION_AGE_MS=5*60*1000;
export async function orchestrateInspectEvidence(session:TraceKitSessionContext,input:InspectEvidenceOrchestrationInput){
 const capability=resolveM12PlanCapability(input.plan),planPermissionGranted=session.effectivePermissions.includes("customers.view"),executionPermissionGranted=session.effectivePermissions.includes("actions.execute"),confirmedAt=Date.parse(input.confirmation.confirmedAt),requestedAt=Date.parse(input.requestedAt),confirmationFresh=Number.isFinite(confirmedAt)&&Number.isFinite(requestedAt)&&confirmedAt<=requestedAt&&requestedAt-confirmedAt<=MAX_CONFIRMATION_AGE_MS,confirmationMatches=Boolean(input.confirmation.confirmationId&&input.confirmation.confirmedPlanIdentity===input.planIdentity&&input.confirmation.confirmedCustomerId===input.plan.target.customerId&&input.confirmation.confirmedJourneyId===input.plan.target.journeyId);
 if(!capability.bound||!planPermissionGranted||!executionPermissionGranted||!confirmationMatches)return{status:"rejected" as const,reason:"governance_gate_failed",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid:false,confirmationFresh,capabilityBound:capability.bound},executionAvailable:false as const,providerMutation:false as const};
 const replayAuthorization=input.authorizationId?await readMcpActionAuthorizationById({authorizationId:input.authorizationId,organizationId:session.activeOrganization!.id}):null,replayCandidate=replayAuthorization?.state==="consumed"&&Boolean(replayAuthorization.envelopeCreatedAt),envelopeCreatedAt=replayCandidate?replayAuthorization!.envelopeCreatedAt:input.requestedAt,confirmationValid=confirmationMatches&&(replayCandidate||confirmationFresh);
 if(!confirmationValid)return{status:"rejected" as const,reason:"governance_gate_failed",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:capability.bound},executionAvailable:false as const,providerMutation:false as const};
 const envelope=buildExecutionEnvelope({plan:input.plan,organizationId:session.activeOrganization!.id,planIdentity:input.planIdentity,operation:{type:"inspect_evidence",parameters:{}},confirmation:input.confirmation,createdAt:envelopeCreatedAt,expiresAt:input.expiresAt,idempotencyKey:input.idempotencyKey,auditCorrelationId:input.auditCorrelationId},envelopeCreatedAt);
 if(!capability.executionAvailable&&!input.acceptanceProofAuthorized)return{status:"rejected" as const,reason:"capability_execution_disabled",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:true,acceptanceProof:false},envelope,executionAvailable:false as const,providerMutation:false as const};
 const authorization=input.authorizationId?await readMcpActionAuthorization({authorizationId:input.authorizationId,envelope}):(await findMcpActionAuthorization(envelope))||await issueMcpActionAuthorization(envelope);if(!authorization)return{status:"rejected" as const,reason:"authorization_provenance_failed",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:true},envelope,executionAvailable:false as const,providerMutation:false as const};const authorizationId=authorization.authorizationId;
 const durable=await consumeMcpActionAuthorization({authorizationId,envelope,requestedAt:input.requestedAt,consumptionId:input.consumptionId}),consumption={decision:durable.decision,reason:"Durable server-side authorization decision.",next:{authorizationId,envelopeIdentity:envelope.envelopeIdentity,idempotencyKey:envelope.idempotencyKey,state:durable.state as any,consumedAt:durable.consumedAt,consumptionId:durable.consumptionId,auditCorrelationId:envelope.auditCorrelationId},executionAvailable:false as const};
 if(durable.decision==="replay_same_result"){const prior=await readMcpExecutionResult<BoundedExecutionResult>({envelope});if(!prior)return{status:"rejected" as const,reason:"replay_result_unavailable",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:true},envelope,consumption,executionAvailable:false as const,providerMutation:false as const};return{status:prior.status,reason:"replay_same_result" as const,governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:true},envelope,consumption,execution:prior,verification:verifyBoundedExecution(prior,input.verificationEvidence,input.requestedAt),executionAvailable:prior.status==="completed",providerMutation:false as const};}
 const execution=executeBoundedInspection({envelope,consumption,operation:"inspect_evidence",acceptanceProofAuthorized:input.acceptanceProofAuthorized}),verification=verifyBoundedExecution(execution,input.verificationEvidence,input.requestedAt);if(execution.status==="completed"&&consumption.next.consumptionId)await persistMcpExecutionResult({envelope,consumptionId:consumption.next.consumptionId,result:execution});
 return{status:execution.status,reason:execution.status==="completed"?"completed":"execution_rejected",governance:{planPermissionGranted,executionPermissionGranted,confirmationValid,confirmationFresh,capabilityBound:true},envelope,consumption,execution,verification,executionAvailable:execution.status==="completed",providerMutation:false as const};
}
