import type { ProductionCustomerScope } from "@/lib/customers/types";
export type JourneyIntelligence={
 customerId:string; journeyId:string|null;
 chronology:Array<{eventId:string;eventType:string;occurredAt:string;sourcePlatform:string;role:string;observed:boolean;identifiers:Array<{type:string;value:string}>;relationships:Array<{type:string;id:string}>;provenance:{sourceConnector:string|null;sourceRecordId:string|null}}>;
 attribution:{status:"attributed"|"unresolved";affiliateId:string|null;offerId:string|null;source:string|null;primaryEvidenceEventIds:string[];corroboratingEventIds:string[];supportingEventIds:string[]};
 relationships:Array<{type:"customer_journey"|"journey_order";fromId:string;toId:string;evidenceEventIds:string[]}>;
 evidenceGroups:Array<{type:"shared_identifier";identifierType:string;identifierValue:string;participantEventIds:string[]}>;
 conclusions:Array<{type:"attribution_established"|"commerce_linked"|"deterministic_identity_bridge";status:"established"|"unresolved";summary:string;evidenceEventIds:string[];relationshipTypes:string[];evidenceGroupIndexes:number[]}>;
 commerce:Array<{orderId:string;amount:number|null;status:string;createdAt:string|null}>;
 evidenceLimits:string[];
};
function base(){return String(process.env.TRACEKIT_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE||"http://127.0.0.1:8787").replace(/\/+$/,"");}
function secret(){return String(process.env.TK_SECRET_KEY||process.env.TRACEKIT_TK_SECRET||"").trim();}
async function get(path:string){const s=secret();if(!s)throw new Error("mcp_journey_repository_unavailable");const r=await fetch(`${base()}${path}`,{cache:"no-store",headers:{accept:"application/json","x-tk-secret":s}});const t=await r.text();let b:any={};try{b=t?JSON.parse(t):{};}catch{}if(!r.ok)throw new Error("mcp_journey_repository_failed");return b;}
export function buildJourneyIntelligence(d:any,j:any,customerId:string,selected:any):JourneyIntelligence {
  const events=Array.isArray(j?.events)?j.events:Array.isArray(j?.activity)?j.activity:[];const credits=Array.isArray(j?.attribution)?j.attribution:[];const credit=credits.find((x:any)=>x?.status==="attributed")||null;
  const chronology=events.map((e:any)=>{const tech=e?.technical_evidence||e?.technical||{};const id=String(e?.id||"");const identifiers=[e?.transaction_id?{type:"Transaction ID",value:String(e.transaction_id)}:null,e?.affiliate_id?{type:"Affiliate ID",value:String(e.affiliate_id)}:null,e?.offer_id?{type:"Offer ID",value:String(e.offer_id)}:null].filter(Boolean) as Array<{type:string;value:string}>;return{eventId:id,eventType:String(e?.event_type||e?.activity_type||"event"),occurredAt:String(e?.occurred_at||e?.event_time||"Not observed"),sourcePlatform:String(e?.source_platform||tech?.source_platform||"TraceKit"),role:String(e?.category||"evidence"),observed:!e?.system_derived,identifiers,relationships:[],provenance:{sourceConnector:tech?.source_connector?String(tech.source_connector):null,sourceRecordId:tech?.source_record_id?String(tech.source_record_id):null}};});
  const primary=credit?chronology.filter((e:any)=>e.role==="marketing_touchpoint"&&e.identifiers.some((i:any)=>(i.type==="Affiliate ID"&&credit?.affiliate_id&&i.value===String(credit.affiliate_id))||(i.type==="Offer ID"&&credit?.offer_id&&i.value===String(credit.offer_id)))).map((e:any)=>e.eventId):[];const corroborating=credit?chronology.filter((e:any)=>!primary.includes(e.eventId)&&e.identifiers.some((i:any)=>i.type==="Affiliate ID"&&credit?.affiliate_id&&i.value===String(credit.affiliate_id))).map((e:any)=>e.eventId):[];const supporting=[...primary,...corroborating];
  const orders=(d.orders||[]).map((o:any)=>({orderId:String(o?.order_id||o?.platform_order_id||""),amount:Number.isFinite(Number(o?.amount))?Number(o.amount):null,status:String(o?.status||"Unknown"),createdAt:o?.created_at?String(o.created_at):null}));const relationships:JourneyIntelligence["relationships"]=[{type:"customer_journey",fromId:customerId,toId:String(selected.id),evidenceEventIds:chronology.map((e:any)=>e.eventId)}];for(const o of orders)relationships.push({type:"journey_order",fromId:String(selected.id),toId:o.orderId,evidenceEventIds:chronology.filter((e:any)=>e.role==="commerce_event").map((e:any)=>e.eventId)});
  const tx=new Map<string,string[]>();for(const e of chronology)for(const i of e.identifiers)if(i.type==="Transaction ID"){const a=tx.get(i.value)||[];a.push(e.eventId);tx.set(i.value,a);}const evidenceGroups:JourneyIntelligence["evidenceGroups"]=Array.from(tx.entries()).filter(([,ids])=>ids.length>1).map(([value,ids])=>({type:"shared_identifier",identifierType:"Transaction ID",identifierValue:value,participantEventIds:ids}));const commerceEvidence=chronology.filter((e:any)=>e.role==="commerce_event").map((e:any)=>e.eventId);
  const conclusions:JourneyIntelligence["conclusions"]=[{type:"attribution_established",status:credit&&primary.length?"established":"unresolved",summary:credit&&primary.length?`Attribution is supported by ${primary.length} primary marketing touchpoint(s) and ${corroborating.length} corroborating event(s).`:"No primary marketing touchpoint supports an attribution conclusion.",evidenceEventIds:supporting,relationshipTypes:[],evidenceGroupIndexes:[]},{type:"commerce_linked",status:orders.length&&commerceEvidence.length?"established":"unresolved",summary:orders.length&&commerceEvidence.length?`${orders.length} commerce order(s) are linked to retained Journey commerce evidence.`:"No retained commerce evidence establishes a Journey-to-Order link.",evidenceEventIds:commerceEvidence,relationshipTypes:["journey_order"],evidenceGroupIndexes:[]},{type:"deterministic_identity_bridge",status:evidenceGroups.length?"established":"unresolved",summary:evidenceGroups.length?`${evidenceGroups.length} shared deterministic identifier group(s) bridge retained source events.`:"No shared deterministic identifier bridges retained source events.",evidenceEventIds:evidenceGroups.flatMap(g=>g.participantEventIds),relationshipTypes:[],evidenceGroupIndexes:evidenceGroups.map((_,i)=>i)}];const limits=Array.isArray(d.customer_360?.evidence_limits)?d.customer_360.evidence_limits.map(String):[];if(!credit)limits.push("No attributed credit was returned for the selected Journey.");return{customerId,journeyId:String(selected.id),chronology,attribution:{status:credit?"attributed":"unresolved",affiliateId:credit?.affiliate_id?String(credit.affiliate_id):null,offerId:credit?.offer_id?String(credit.offer_id):null,source:credit?.source?String(credit.source):null,primaryEvidenceEventIds:primary,corroboratingEventIds:corroborating,supportingEventIds:supporting},relationships,evidenceGroups,conclusions,commerce:orders,evidenceLimits:Array.from(new Set(limits))};
}
function qs(s:ProductionCustomerScope,x:Record<string,unknown>={}){const p=new URLSearchParams({workspace_id:s.workspaceId});for(const[k,v]of Object.entries(x))if(v!==null&&v!==undefined&&v!=="")p.set(k,String(v));return p.toString();}
export type CohortComparison={value:string;journeys:number;attributionEstablished:{count:number;denominator:number};commerceLinked:{count:number;denominator:number};deterministicIdentityBridge:{count:number;denominator:number};evidenceLimited:{count:number;denominator:number};sampleJourneyIds:string[]};
export type CrossJourneyAnalysis={
 population:{customersRequested:number;customersScanned:number;journeysDiscovered:number;journeysAnalyzed:number;journeysSkippedByLimit:number;journeysFailed:number};
 conclusions:{attributionEstablished:{count:number;denominator:number};attributionUnresolved:{count:number;denominator:number};commerceLinked:{count:number;denominator:number};deterministicIdentityBridge:{count:number;denominator:number};deterministicIdentityBridgeMissing:{count:number;denominator:number}};
 bySourcePlatform:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;byConnector:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;byAffiliate:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;byOffer:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;evidenceLimits:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;comparisons:{byAffiliate:Array<CohortComparison>;byOffer:Array<CohortComparison>;bySourcePlatform:Array<CohortComparison>;byConnector:Array<CohortComparison>};cohorts:{attributionUnresolved:string[];deterministicIdentityBridgeMissing:string[];commerceUnlinked:string[]};samples:Array<{customerId:string;journeyId:string|null;attributionStatus:string;commerceLinked:boolean;deterministicIdentityBridge:boolean}>;
};

function add(map:Map<string,{count:number;ids:string[]}>,values:string[],journeyId:string){for(const v of Array.from(new Set(values.filter(Boolean)))){const x=map.get(v)||{count:0,ids:[]};x.count++;if(x.ids.length<10&&!x.ids.includes(journeyId))x.ids.push(journeyId);map.set(v,x);}}
export const mcpJourneyRepository={
 async analyze(s:ProductionCustomerScope,customerLimit=25,journeyLimit=50):Promise<CrossJourneyAnalysis>{
  const empty=(population:CrossJourneyAnalysis["population"]):CrossJourneyAnalysis=>({population,conclusions:{attributionEstablished:{count:0,denominator:0},attributionUnresolved:{count:0,denominator:0},commerceLinked:{count:0,denominator:0},deterministicIdentityBridge:{count:0,denominator:0},deterministicIdentityBridgeMissing:{count:0,denominator:0}},bySourcePlatform:[],byConnector:[],byAffiliate:[],byOffer:[],evidenceLimits:[],comparisons:{byAffiliate:[],byOffer:[],bySourcePlatform:[],byConnector:[]},cohorts:{attributionUnresolved:[],deterministicIdentityBridgeMissing:[],commerceUnlinked:[]},samples:[]});
  if(!s.authenticated)return empty({customersRequested:customerLimit,customersScanned:0,journeysDiscovered:0,journeysAnalyzed:0,journeysSkippedByLimit:0,journeysFailed:0});
  const list=await get(`/v1/customers?${qs(s,{limit:customerLimit})}`);const rows=Array.isArray(list.customers)?list.customers.slice(0,customerLimit):[];
  const discovered:Array<{customerId:string;detail:any;journey:any}>=[];let failed=0;
  for(const row of rows){const customerId=String(row?.customer?.id||"");if(!customerId)continue;try{const detail=await get(`/v1/customers/${encodeURIComponent(customerId)}?${qs(s)}`);for(const journey of Array.isArray(detail.journeys)?detail.journeys:[])if(journey?.id)discovered.push({customerId,detail,journey});}catch{failed++;}}
  const selected=discovered.slice(0,journeyLimit);const xs:JourneyIntelligence[]=[];
  for(const item of selected){try{const j=await get(`/v1/customers/${encodeURIComponent(item.customerId)}/journeys/${encodeURIComponent(String(item.journey.id))}?${qs(s,{limit:100})}`);xs.push(buildJourneyIntelligence(item.detail,j,item.customerId,item.journey));}catch{failed++;}}
  const n=xs.length;const source=new Map<string,{count:number;ids:string[]}>(),connector=new Map<string,{count:number;ids:string[]}>(),affiliate=new Map<string,{count:number;ids:string[]}>(),offer=new Map<string,{count:number;ids:string[]}>(),limits=new Map<string,{count:number;ids:string[]}>();
  for(const x of xs){const id=x.journeyId||"";add(source,x.chronology.map(e=>e.sourcePlatform),id);add(connector,x.chronology.map(e=>e.provenance.sourceConnector||""),id);add(affiliate,x.attribution.affiliateId?[x.attribution.affiliateId]:[],id);add(offer,x.attribution.offerId?[x.attribution.offerId]:[],id);add(limits,x.evidenceLimits,id);}
  const established=(x:JourneyIntelligence,t:string)=>x.conclusions.find(c=>c.type===t)?.status==="established";
  const compare=(values:(x:JourneyIntelligence)=>string[]):CohortComparison[]=>{const buckets=new Map<string,JourneyIntelligence[]>();for(const x of xs)for(const v of Array.from(new Set(values(x).filter(Boolean)))){const a=buckets.get(v)||[];a.push(x);buckets.set(v,a);}return Array.from(buckets.entries()).map(([value,a])=>({value,journeys:a.length,attributionEstablished:{count:a.filter(x=>established(x,"attribution_established")).length,denominator:a.length},commerceLinked:{count:a.filter(x=>established(x,"commerce_linked")).length,denominator:a.length},deterministicIdentityBridge:{count:a.filter(x=>established(x,"deterministic_identity_bridge")).length,denominator:a.length},evidenceLimited:{count:a.filter(x=>x.evidenceLimits.length>0).length,denominator:a.length},sampleJourneyIds:a.map(x=>x.journeyId||"").filter(Boolean).slice(0,10)})).sort((a,b)=>b.journeys-a.journeys||a.value.localeCompare(b.value));};
  const comparisons={byAffiliate:compare(x=>x.attribution.affiliateId?[x.attribution.affiliateId]:[]),byOffer:compare(x=>x.attribution.offerId?[x.attribution.offerId]:[]),bySourcePlatform:compare(x=>x.chronology.map(e=>e.sourcePlatform)),byConnector:compare(x=>x.chronology.map(e=>e.provenance.sourceConnector||""))};const arr=(m:Map<string,{count:number;ids:string[]}>)=>Array.from(m.entries()).map(([value,x])=>({value,journeys:x.count,sampleJourneyIds:x.ids})).sort((a,b)=>b.journeys-a.journeys||a.value.localeCompare(b.value));
  return{population:{customersRequested:customerLimit,customersScanned:rows.length,journeysDiscovered:discovered.length,journeysAnalyzed:n,journeysSkippedByLimit:Math.max(0,discovered.length-selected.length),journeysFailed:failed},conclusions:{attributionEstablished:{count:xs.filter(x=>established(x,"attribution_established")).length,denominator:n},attributionUnresolved:{count:xs.filter(x=>!established(x,"attribution_established")).length,denominator:n},commerceLinked:{count:xs.filter(x=>established(x,"commerce_linked")).length,denominator:n},deterministicIdentityBridge:{count:xs.filter(x=>established(x,"deterministic_identity_bridge")).length,denominator:n},deterministicIdentityBridgeMissing:{count:xs.filter(x=>!established(x,"deterministic_identity_bridge")).length,denominator:n}},bySourcePlatform:arr(source),byConnector:arr(connector),byAffiliate:arr(affiliate),byOffer:arr(offer),evidenceLimits:arr(limits),comparisons,cohorts:{attributionUnresolved:xs.filter(x=>!established(x,"attribution_established")).map(x=>x.journeyId||"").filter(Boolean).slice(0,10),deterministicIdentityBridgeMissing:xs.filter(x=>!established(x,"deterministic_identity_bridge")).map(x=>x.journeyId||"").filter(Boolean).slice(0,10),commerceUnlinked:xs.filter(x=>!established(x,"commerce_linked")).map(x=>x.journeyId||"").filter(Boolean).slice(0,10)},samples:xs.slice(0,10).map(x=>({customerId:x.customerId,journeyId:x.journeyId,attributionStatus:x.attribution.status,commerceLinked:established(x,"commerce_linked"),deterministicIdentityBridge:established(x,"deterministic_identity_bridge")}))};
 },
 async explain(s:ProductionCustomerScope,customerId:string,journeyId?:string):Promise<JourneyIntelligence|null>{
  if(!s.authenticated||!customerId)return null;
  const d=await get(`/v1/customers/${encodeURIComponent(customerId)}?${qs(s)}`);
  const journeys=Array.isArray(d.journeys)?d.journeys:[];const selected=journeyId?journeys.find((x:any)=>String(x?.id||"")===journeyId):journeys[0];if(!selected?.id)return{customerId,journeyId:null,chronology:[],attribution:{status:"unresolved",affiliateId:null,offerId:null,source:null,primaryEvidenceEventIds:[],corroboratingEventIds:[],supportingEventIds:[]},relationships:[],evidenceGroups:[],conclusions:[{type:"attribution_established",status:"unresolved",summary:"No canonical Journey is available to support an attribution conclusion.",evidenceEventIds:[],relationshipTypes:[],evidenceGroupIndexes:[]}],commerce:(d.orders||[]).map((o:any)=>({orderId:String(o?.order_id||o?.platform_order_id||""),amount:Number.isFinite(Number(o?.amount))?Number(o.amount):null,status:String(o?.status||"Unknown"),createdAt:o?.created_at?String(o.created_at):null})),evidenceLimits:["No canonical Journey was returned for this customer."]};
  const j=await get(`/v1/customers/${encodeURIComponent(customerId)}/journeys/${encodeURIComponent(selected.id)}?${qs(s,{limit:100})}`);
  return buildJourneyIntelligence(d,j,customerId,selected);
 }
};
