import type { ProductionCustomerScope } from "@/lib/customers/types";
export type JourneyIntelligence={
 customerId:string; journeyId:string|null;
 chronology:Array<{eventId:string;eventType:string;occurredAt:string;sourcePlatform:string;role:string;observed:boolean;identifiers:Array<{type:string;value:string}>;relationships:Array<{type:string;id:string}>;provenance:{sourceConnector:string|null;sourceRecordId:string|null}}>;
 attribution:{status:"attributed"|"unresolved";affiliateId:string|null;offerId:string|null;source:string|null;primaryEvidenceEventIds:string[];corroboratingEventIds:string[];supportingEventIds:string[]};
 relationships:Array<{type:"customer_journey"|"journey_order";fromId:string;toId:string;evidenceEventIds:string[]}>;
 evidenceGroups:Array<{type:"shared_identifier";identifierType:string;identifierValue:string;participantEventIds:string[]}>;
 conclusions:Array<{type:"attribution_established"|"commerce_linked"|"deterministic_identity_bridge";status:"established"|"unresolved";summary:string;evidenceEventIds:string[];relationshipTypes:string[];evidenceGroupIndexes:number[]}>;
 commerce:Array<{orderId:string;amount:number|null;status:string;createdAt:string|null}>;
 evidenceLimits:string[];
};
function base(){return String(process.env.TRACEKIT_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE||"http://127.0.0.1:8787").replace(/\/+$/,"");}
function secret(){return String(process.env.TK_SECRET_KEY||process.env.TRACEKIT_TK_SECRET||"").trim();}
async function get(path:string){const s=secret();if(!s)throw new Error("mcp_journey_repository_unavailable");const r=await fetch(`${base()}${path}`,{cache:"no-store",headers:{accept:"application/json","x-tk-secret":s}});const t=await r.text();let b:any={};try{b=t?JSON.parse(t):{};}catch{}if(!r.ok)throw new Error("mcp_journey_repository_failed");return b;}
export function buildJourneyIntelligence(d:any,j:any,customerId:string,selected:any):JourneyIntelligence {
  const events=Array.isArray(j?.events)?j.events:Array.isArray(j?.activity)?j.activity:[];const credits=Array.isArray(j?.attribution)?j.attribution:[];const credit=credits.find((x:any)=>x?.status==="attributed")||null;
  const chronology=events.map((e:any)=>{const tech=e?.technical_evidence||e?.technical||{};const id=String(e?.id||"");const identifiers=[e?.transaction_id?{type:"Transaction ID",value:String(e.transaction_id)}:null,e?.affiliate_id?{type:"Affiliate ID",value:String(e.affiliate_id)}:null,e?.offer_id?{type:"Offer ID",value:String(e.offer_id)}:null].filter(Boolean) as Array<{type:string;value:string}>;return{eventId:id,eventType:String(e?.event_type||e?.activity_type||"event"),occurredAt:String(e?.occurred_at||e?.event_time||"Not observed"),sourcePlatform:String(e?.source_platform||tech?.source_platform||"TraceKit"),role:String(e?.category||"evidence"),observed:!e?.system_derived,identifiers,relationships:[],provenance:{sourceConnector:tech?.source_connector?String(tech.source_connector):null,sourceRecordId:tech?.source_record_id?String(tech.source_record_id):null}};});
  const primary=credit?chronology.filter((e:any)=>e.role==="marketing_touchpoint"&&e.identifiers.some((i:any)=>(i.type==="Affiliate ID"&&credit?.affiliate_id&&i.value===String(credit.affiliate_id))||(i.type==="Offer ID"&&credit?.offer_id&&i.value===String(credit.offer_id)))).map((e:any)=>e.eventId):[];const corroborating=credit?chronology.filter((e:any)=>!primary.includes(e.eventId)&&e.identifiers.some((i:any)=>i.type==="Affiliate ID"&&credit?.affiliate_id&&i.value===String(credit.affiliate_id))).map((e:any)=>e.eventId):[];const supporting=[...primary,...corroborating];
  const orders=(d.orders||[]).map((o:any)=>({orderId:String(o?.order_id||o?.platform_order_id||""),amount:Number.isFinite(Number(o?.amount))?Number(o.amount):null,status:String(o?.status||"Unknown"),createdAt:o?.created_at?String(o.created_at):null}));const relationships:JourneyIntelligence["relationships"]=[{type:"customer_journey",fromId:customerId,toId:String(selected.id),evidenceEventIds:chronology.map((e:any)=>e.eventId)}];for(const o of orders)relationships.push({type:"journey_order",fromId:String(selected.id),toId:o.orderId,evidenceEventIds:chronology.filter((e:any)=>e.role==="commerce_event").map((e:any)=>e.eventId)});
  const tx=new Map<string,string[]>();for(const e of chronology)for(const i of e.identifiers)if(i.type==="Transaction ID"){const a=tx.get(i.value)||[];a.push(e.eventId);tx.set(i.value,a);}const evidenceGroups:JourneyIntelligence["evidenceGroups"]=Array.from(tx.entries()).filter(([,ids])=>ids.length>1).map(([value,ids])=>({type:"shared_identifier",identifierType:"Transaction ID",identifierValue:value,participantEventIds:ids}));const commerceEvidence=chronology.filter((e:any)=>e.role==="commerce_event").map((e:any)=>e.eventId);
  const conclusions:JourneyIntelligence["conclusions"]=[{type:"attribution_established",status:credit&&primary.length?"established":"unresolved",summary:credit&&primary.length?`Attribution is supported by ${primary.length} primary marketing touchpoint(s) and ${corroborating.length} corroborating event(s).`:"No primary marketing touchpoint supports an attribution conclusion.",evidenceEventIds:supporting,relationshipTypes:[],evidenceGroupIndexes:[]},{type:"commerce_linked",status:orders.length&&commerceEvidence.length?"established":"unresolved",summary:orders.length&&commerceEvidence.length?`${orders.length} commerce order(s) are linked to retained Journey commerce evidence.`:"No retained commerce evidence establishes a Journey-to-Order link.",evidenceEventIds:commerceEvidence,relationshipTypes:["journey_order"],evidenceGroupIndexes:[]},{type:"deterministic_identity_bridge",status:evidenceGroups.length?"established":"unresolved",summary:evidenceGroups.length?`${evidenceGroups.length} shared deterministic identifier group(s) bridge retained source events.`:"No shared deterministic identifier bridges retained source events.",evidenceEventIds:evidenceGroups.flatMap(g=>g.participantEventIds),relationshipTypes:[],evidenceGroupIndexes:evidenceGroups.map((_,i)=>i)}];const limits=Array.isArray(d.customer_360?.evidence_limits)?d.customer_360.evidence_limits.map(String):[];if(!credit)limits.push("No attributed credit was returned for the selected Journey.");return{customerId,journeyId:String(selected.id),chronology,attribution:{status:credit?"attributed":"unresolved",affiliateId:credit?.affiliate_id?String(credit.affiliate_id):null,offerId:credit?.offer_id?String(credit.offer_id):null,source:credit?.source?String(credit.source):null,primaryEvidenceEventIds:primary,corroboratingEventIds:corroborating,supportingEventIds:supporting},relationships,evidenceGroups,conclusions,commerce:orders,evidenceLimits:Array.from(new Set(limits))};
}
function qs(s:ProductionCustomerScope,x:Record<string,unknown>={}){const p=new URLSearchParams({workspace_id:s.workspaceId});for(const[k,v]of Object.entries(x))if(v!==null&&v!==undefined&&v!=="")p.set(k,String(v));return p.toString();}
export type TrackingInvestigation={
 scope:{customerId:string;journeyId:string|null};
 observedConditions:Array<{type:"attribution_unresolved"|"commerce_unlinked"|"deterministic_identity_bridge_missing"|"evidence_limited";status:"observed"|"not_observed";evidenceEventIds:string[]}>;
 presentEvidence:{sourcePlatforms:string[];connectors:string[];identifierTypes:string[];commerceOrders:string[]};
 missingEvidence:Array<{type:"primary_attribution_evidence"|"commerce_link_evidence"|"shared_deterministic_identifier";reason:string}>;
 boundaries:Array<{sourcePlatform:string;connector:string|null;eventIds:string[]}>;
 inspectionTargets:Array<{type:"event"|"source_connector"|"order";id:string;reason:string}>;
 evidenceLimits:string[];
};
export function buildTrackingInvestigation(x:JourneyIntelligence):TrackingInvestigation{
 const established=(t:string)=>x.conclusions.find(c=>c.type===t)?.status==="established";const events=(t:string)=>x.conclusions.find(c=>c.type===t)?.evidenceEventIds||[];
 const sourcePlatforms=Array.from(new Set(x.chronology.map(e=>e.sourcePlatform).filter(Boolean))),connectors=Array.from(new Set(x.chronology.map(e=>e.provenance.sourceConnector).filter(Boolean))) as string[],identifierTypes=Array.from(new Set(x.chronology.flatMap(e=>e.identifiers.map(i=>i.type))));
 const missing:TrackingInvestigation["missingEvidence"]=[];if(!established("attribution_established"))missing.push({type:"primary_attribution_evidence",reason:"No retained primary marketing touchpoint establishes attribution."});if(!established("commerce_linked"))missing.push({type:"commerce_link_evidence",reason:"No retained commerce evidence establishes the Journey-to-Order relationship."});if(!established("deterministic_identity_bridge"))missing.push({type:"shared_deterministic_identifier",reason:"No shared deterministic identifier bridges retained source events."});
 const boundaryMap=new Map<string,{sourcePlatform:string;connector:string|null;eventIds:string[]}>();for(const e of x.chronology){const key=e.sourcePlatform+"|"+(e.provenance.sourceConnector||"");const b=boundaryMap.get(key)||{sourcePlatform:e.sourcePlatform,connector:e.provenance.sourceConnector,eventIds:[]};b.eventIds.push(e.eventId);boundaryMap.set(key,b);}
 const inspectionTargets:TrackingInvestigation["inspectionTargets"]=[];for(const e of x.chronology)if(missing.length)inspectionTargets.push({type:"event",id:e.eventId,reason:"Retained event at an investigation boundary; compare identifiers and provenance against the missing evidence."});for(const v of connectors)inspectionTargets.push({type:"source_connector",id:v,reason:"Connector contributed retained evidence to this Journey."});for(const o of x.commerce)inspectionTargets.push({type:"order",id:o.orderId,reason:"Commerce entity related to this Journey."});
 return{scope:{customerId:x.customerId,journeyId:x.journeyId},observedConditions:[{type:"attribution_unresolved",status:established("attribution_established")?"not_observed":"observed",evidenceEventIds:events("attribution_established")},{type:"commerce_unlinked",status:established("commerce_linked")?"not_observed":"observed",evidenceEventIds:events("commerce_linked")},{type:"deterministic_identity_bridge_missing",status:established("deterministic_identity_bridge")?"not_observed":"observed",evidenceEventIds:events("deterministic_identity_bridge")},{type:"evidence_limited",status:x.evidenceLimits.length?"observed":"not_observed",evidenceEventIds:[]}],presentEvidence:{sourcePlatforms,connectors,identifierTypes,commerceOrders:x.commerce.map(o=>o.orderId)},missingEvidence:missing,boundaries:Array.from(boundaryMap.values()),inspectionTargets:inspectionTargets.slice(0,25),evidenceLimits:x.evidenceLimits};
}
export type AdvisoryRecommendation={id:string;sequence:number;dependsOn:string[];blockedByEvidenceLimits:boolean;type:"inspect_attribution_evidence"|"inspect_commerce_linkage"|"inspect_identifier_propagation"|"review_evidence_limits";mode:"advisory";reason:string;supportingEventIds:string[];affectedBoundaries:Array<{sourcePlatform:string;connector:string|null}>;prerequisites:string[];successEvidence:string[];impact:"diagnostic";uncertainty:string[]};
export type RecommendationIntelligence={scope:TrackingInvestigation["scope"];recommendations:AdvisoryRecommendation[];evidenceLimits:string[]};
export function buildRecommendations(i:TrackingInvestigation):RecommendationIntelligence{
 const recommendations:AdvisoryRecommendation[]=[];const boundaries=i.boundaries.map(b=>({sourcePlatform:b.sourcePlatform,connector:b.connector}));const events=(type:TrackingInvestigation["observedConditions"][number]["type"])=>i.observedConditions.find(c=>c.type===type)?.evidenceEventIds||[];
 const add=(r:Omit<AdvisoryRecommendation,"id"|"sequence"|"dependsOn"|"blockedByEvidenceLimits"|"mode"|"impact"|"uncertainty">)=>{const id=`rec-${recommendations.length+1}`;const evidenceReview=recommendations.find(x=>x.type==="review_evidence_limits")?.id;recommendations.push({...r,id,sequence:recommendations.length+1,dependsOn:evidenceReview?[evidenceReview]:[],blockedByEvidenceLimits:Boolean(i.evidenceLimits.length&&r.type!=="review_evidence_limits"),mode:"advisory",impact:"diagnostic",uncertainty:i.evidenceLimits});};
 if(i.evidenceLimits.length)add({type:"review_evidence_limits",reason:"Retained evidence limits constrain the investigation.",supportingEventIds:[],affectedBoundaries:boundaries,prerequisites:["Review each retained evidence limit before acting on an investigation conclusion."],successEvidence:["Evidence limits are resolved or explicitly accepted before any remediation decision."]});
 if(i.observedConditions.find(c=>c.type==="attribution_unresolved")?.status==="observed")add({type:"inspect_attribution_evidence",reason:"Primary attribution evidence is not established for this Journey.",supportingEventIds:events("attribution_unresolved"),affectedBoundaries:boundaries,prerequisites:["Confirm retained marketing-touchpoint evidence and provider attribution identifiers."],successEvidence:["A retained primary marketing touchpoint supports attribution with provider provenance."]});
 if(i.observedConditions.find(c=>c.type==="commerce_unlinked")?.status==="observed")add({type:"inspect_commerce_linkage",reason:"Journey-to-Order commerce linkage is not established.",supportingEventIds:events("commerce_unlinked"),affectedBoundaries:boundaries,prerequisites:["Confirm retained commerce events and deterministic order references."],successEvidence:["Retained commerce evidence establishes a Journey-to-Order relationship."]});
 if(i.observedConditions.find(c=>c.type==="deterministic_identity_bridge_missing")?.status==="observed")add({type:"inspect_identifier_propagation",reason:"No shared deterministic identifier bridges the retained source events.",supportingEventIds:events("deterministic_identity_bridge_missing"),affectedBoundaries:boundaries,prerequisites:["Compare retained identifiers across acquisition and commerce boundaries without assuming which boundary failed."],successEvidence:["The same deterministic identifier is retained across the relevant source events."]});
 
 return{scope:i.scope,recommendations:recommendations.slice(0,10),evidenceLimits:i.evidenceLimits};
}
export type DeviationInvestigation={deviation:CrossJourneyAnalysis["deviations"][number];affectedJourneys:number;investigations:Array<TrackingInvestigation>;journeysUnavailable:string[]};
export function buildDeviationInvestigation(deviation:CrossJourneyAnalysis["deviations"][number],investigations:TrackingInvestigation[],requestedJourneyIds=deviation.supportingJourneyIds.slice(0,10)):DeviationInvestigation{
 const resolved=new Set(investigations.map(i=>i.scope.journeyId).filter(Boolean));return{deviation,affectedJourneys:deviation.cohort.denominator,investigations:investigations.slice(0,10),journeysUnavailable:requestedJourneyIds.filter(id=>!resolved.has(id))};
}
export type CohortComparison={value:string;journeys:number;attributionEstablished:{count:number;denominator:number};commerceLinked:{count:number;denominator:number};deterministicIdentityBridge:{count:number;denominator:number};evidenceLimited:{count:number;denominator:number};sampleJourneyIds:string[]};
export type CrossJourneyAnalysis={
 population:{customersRequested:number;customersScanned:number;journeysDiscovered:number;journeysAnalyzed:number;journeysSkippedByLimit:number;journeysFailed:number};
 conclusions:{attributionEstablished:{count:number;denominator:number};attributionUnresolved:{count:number;denominator:number};commerceLinked:{count:number;denominator:number};deterministicIdentityBridge:{count:number;denominator:number};deterministicIdentityBridgeMissing:{count:number;denominator:number}};
 bySourcePlatform:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;byConnector:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;byAffiliate:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;byOffer:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;evidenceLimits:Array<{value:string;journeys:number;sampleJourneyIds:string[]}>;deviations:Array<{dimension:"affiliate"|"offer"|"source_platform"|"connector";value:string;metric:"attribution_established"|"commerce_linked"|"deterministic_identity_bridge"|"evidence_limited";cohort:{count:number;denominator:number;rate:number};baseline:{count:number;denominator:number;rate:number};difference:number;minimumSampleMet:boolean;supportingJourneyIds:string[]}>;comparisons:{byAffiliate:Array<CohortComparison>;byOffer:Array<CohortComparison>;bySourcePlatform:Array<CohortComparison>;byConnector:Array<CohortComparison>};cohorts:{attributionUnresolved:string[];deterministicIdentityBridgeMissing:string[];commerceUnlinked:string[]};samples:Array<{customerId:string;journeyId:string|null;attributionStatus:string;commerceLinked:boolean;deterministicIdentityBridge:boolean}>;
};

export type DeviationBaseline={attribution_established:{count:number;denominator:number};commerce_linked:{count:number;denominator:number};deterministic_identity_bridge:{count:number;denominator:number};evidence_limited:{count:number;denominator:number}};
export function buildObservedDeviations(comparisons:CrossJourneyAnalysis["comparisons"],baseline:DeviationBaseline,minimumSample=3):CrossJourneyAnalysis["deviations"]{
 const rate=(count:number,denominator:number)=>denominator?count/denominator:0;const deviations:CrossJourneyAnalysis["deviations"]=[];const dims:[CrossJourneyAnalysis["deviations"][number]["dimension"],CohortComparison[]][]=[["affiliate",comparisons.byAffiliate],["offer",comparisons.byOffer],["source_platform",comparisons.bySourcePlatform],["connector",comparisons.byConnector]];
 for(const[dimension,groups]of dims)for(const g of groups){const metrics=[["attribution_established",g.attributionEstablished],["commerce_linked",g.commerceLinked],["deterministic_identity_bridge",g.deterministicIdentityBridge],["evidence_limited",g.evidenceLimited]] as const;for(const[metric,v]of metrics){const b=baseline[metric],cr=rate(v.count,v.denominator),br=rate(b.count,b.denominator),difference=cr-br;if(g.journeys>=minimumSample&&Math.abs(difference)>0)deviations.push({dimension,value:g.value,metric,cohort:{count:v.count,denominator:v.denominator,rate:cr},baseline:{count:b.count,denominator:b.denominator,rate:br},difference,minimumSampleMet:true,supportingJourneyIds:g.sampleJourneyIds});}}return deviations;
}
function add(map:Map<string,{count:number;ids:string[]}>,values:string[],journeyId:string){for(const v of Array.from(new Set(values.filter(Boolean)))){const x=map.get(v)||{count:0,ids:[]};x.count++;if(x.ids.length<10&&!x.ids.includes(journeyId))x.ids.push(journeyId);map.set(v,x);}}
export const mcpJourneyRepository={
 async recommend(s:ProductionCustomerScope,customerId:string,journeyId?:string):Promise<RecommendationIntelligence|null>{const i=await this.investigate(s,customerId,journeyId);return i?buildRecommendations(i):null;},
  async investigateDeviation(s:ProductionCustomerScope,deviation:CrossJourneyAnalysis["deviations"][number],customerLimit=50,journeyLimit=100):Promise<DeviationInvestigation>{
  const analysis=await this.analyze(s,customerLimit,journeyLimit);const live=analysis.deviations.find(d=>d.dimension===deviation.dimension&&d.value===deviation.value&&d.metric===deviation.metric);if(!live)throw new Error("mcp_deviation_not_observed");
  const wanted=live.supportingJourneyIds.slice(0,10),investigations:TrackingInvestigation[]=[],journeysUnavailable:string[]=[];
  const list=await get(`/v1/customers?${qs(s,{limit:customerLimit})}`);const rows=Array.isArray(list.customers)?list.customers.slice(0,customerLimit):[];
  for(const row of rows){if(investigations.length>=wanted.length)break;const customerId=String(row?.customer?.id||"");if(!customerId)continue;try{const detail=await get(`/v1/customers/${encodeURIComponent(customerId)}?${qs(s)}`);for(const j of Array.isArray(detail.journeys)?detail.journeys:[]){const jid=String(j?.id||"");if(!wanted.includes(jid)||investigations.some(i=>i.scope.journeyId===jid))continue;const raw=await get(`/v1/customers/${encodeURIComponent(customerId)}/journeys/${encodeURIComponent(jid)}?${qs(s,{limit:100})}`);investigations.push(buildTrackingInvestigation(buildJourneyIntelligence(detail,raw,customerId,j)));}}catch{}}
  return buildDeviationInvestigation(live,investigations,wanted);
 },
  async investigate(s:ProductionCustomerScope,customerId:string,journeyId?:string):Promise<TrackingInvestigation|null>{const x=await this.explain(s,customerId,journeyId);return x?buildTrackingInvestigation(x):null;},
  async analyze(s:ProductionCustomerScope,customerLimit=25,journeyLimit=50):Promise<CrossJourneyAnalysis>{
  const empty=(population:CrossJourneyAnalysis["population"]):CrossJourneyAnalysis=>({population,conclusions:{attributionEstablished:{count:0,denominator:0},attributionUnresolved:{count:0,denominator:0},commerceLinked:{count:0,denominator:0},deterministicIdentityBridge:{count:0,denominator:0},deterministicIdentityBridgeMissing:{count:0,denominator:0}},bySourcePlatform:[],byConnector:[],byAffiliate:[],byOffer:[],evidenceLimits:[],deviations:[],comparisons:{byAffiliate:[],byOffer:[],bySourcePlatform:[],byConnector:[]},cohorts:{attributionUnresolved:[],deterministicIdentityBridgeMissing:[],commerceUnlinked:[]},samples:[]});
  if(!s.authenticated)return empty({customersRequested:customerLimit,customersScanned:0,journeysDiscovered:0,journeysAnalyzed:0,journeysSkippedByLimit:0,journeysFailed:0});
  const list=await get(`/v1/customers?${qs(s,{limit:customerLimit})}`);const rows=Array.isArray(list.customers)?list.customers.slice(0,customerLimit):[];
  const discovered:Array<{customerId:string;detail:any;journey:any}>=[];let failed=0;
  for(const row of rows){const customerId=String(row?.customer?.id||"");if(!customerId)continue;try{const detail=await get(`/v1/customers/${encodeURIComponent(customerId)}?${qs(s)}`);for(const journey of Array.isArray(detail.journeys)?detail.journeys:[])if(journey?.id)discovered.push({customerId,detail,journey});}catch{failed++;}}
  const selected=discovered.slice(0,journeyLimit);const xs:JourneyIntelligence[]=[];
  for(const item of selected){try{const j=await get(`/v1/customers/${encodeURIComponent(item.customerId)}/journeys/${encodeURIComponent(String(item.journey.id))}?${qs(s,{limit:100})}`);xs.push(buildJourneyIntelligence(item.detail,j,item.customerId,item.journey));}catch{failed++;}}
  const n=xs.length;const source=new Map<string,{count:number;ids:string[]}>(),connector=new Map<string,{count:number;ids:string[]}>(),affiliate=new Map<string,{count:number;ids:string[]}>(),offer=new Map<string,{count:number;ids:string[]}>(),limits=new Map<string,{count:number;ids:string[]}>();
  for(const x of xs){const id=x.journeyId||"";add(source,x.chronology.map(e=>e.sourcePlatform),id);add(connector,x.chronology.map(e=>e.provenance.sourceConnector||""),id);add(affiliate,x.attribution.affiliateId?[x.attribution.affiliateId]:[],id);add(offer,x.attribution.offerId?[x.attribution.offerId]:[],id);add(limits,x.evidenceLimits,id);}
  const established=(x:JourneyIntelligence,t:string)=>x.conclusions.find(c=>c.type===t)?.status==="established";
  const compare=(values:(x:JourneyIntelligence)=>string[]):CohortComparison[]=>{const buckets=new Map<string,JourneyIntelligence[]>();for(const x of xs)for(const v of Array.from(new Set(values(x).filter(Boolean)))){const a=buckets.get(v)||[];a.push(x);buckets.set(v,a);}return Array.from(buckets.entries()).map(([value,a])=>({value,journeys:a.length,attributionEstablished:{count:a.filter(x=>established(x,"attribution_established")).length,denominator:a.length},commerceLinked:{count:a.filter(x=>established(x,"commerce_linked")).length,denominator:a.length},deterministicIdentityBridge:{count:a.filter(x=>established(x,"deterministic_identity_bridge")).length,denominator:a.length},evidenceLimited:{count:a.filter(x=>x.evidenceLimits.length>0).length,denominator:a.length},sampleJourneyIds:a.map(x=>x.journeyId||"").filter(Boolean).slice(0,10)})).sort((a,b)=>b.journeys-a.journeys||a.value.localeCompare(b.value));};
  const comparisons={byAffiliate:compare(x=>x.attribution.affiliateId?[x.attribution.affiliateId]:[]),byOffer:compare(x=>x.attribution.offerId?[x.attribution.offerId]:[]),bySourcePlatform:compare(x=>x.chronology.map(e=>e.sourcePlatform)),byConnector:compare(x=>x.chronology.map(e=>e.provenance.sourceConnector||""))};
  const baseline={attribution_established:{count:xs.filter(x=>established(x,"attribution_established")).length,denominator:n},commerce_linked:{count:xs.filter(x=>established(x,"commerce_linked")).length,denominator:n},deterministic_identity_bridge:{count:xs.filter(x=>established(x,"deterministic_identity_bridge")).length,denominator:n},evidence_limited:{count:xs.filter(x=>x.evidenceLimits.length>0).length,denominator:n}};
  const deviations=buildObservedDeviations(comparisons,baseline);
const arr=(m:Map<string,{count:number;ids:string[]}>)=>Array.from(m.entries()).map(([value,x])=>({value,journeys:x.count,sampleJourneyIds:x.ids})).sort((a,b)=>b.journeys-a.journeys||a.value.localeCompare(b.value));
  return{population:{customersRequested:customerLimit,customersScanned:rows.length,journeysDiscovered:discovered.length,journeysAnalyzed:n,journeysSkippedByLimit:Math.max(0,discovered.length-selected.length),journeysFailed:failed},conclusions:{attributionEstablished:{count:xs.filter(x=>established(x,"attribution_established")).length,denominator:n},attributionUnresolved:{count:xs.filter(x=>!established(x,"attribution_established")).length,denominator:n},commerceLinked:{count:xs.filter(x=>established(x,"commerce_linked")).length,denominator:n},deterministicIdentityBridge:{count:xs.filter(x=>established(x,"deterministic_identity_bridge")).length,denominator:n},deterministicIdentityBridgeMissing:{count:xs.filter(x=>!established(x,"deterministic_identity_bridge")).length,denominator:n}},bySourcePlatform:arr(source),byConnector:arr(connector),byAffiliate:arr(affiliate),byOffer:arr(offer),evidenceLimits:arr(limits),deviations,comparisons,cohorts:{attributionUnresolved:xs.filter(x=>!established(x,"attribution_established")).map(x=>x.journeyId||"").filter(Boolean).slice(0,10),deterministicIdentityBridgeMissing:xs.filter(x=>!established(x,"deterministic_identity_bridge")).map(x=>x.journeyId||"").filter(Boolean).slice(0,10),commerceUnlinked:xs.filter(x=>!established(x,"commerce_linked")).map(x=>x.journeyId||"").filter(Boolean).slice(0,10)},samples:xs.slice(0,10).map(x=>({customerId:x.customerId,journeyId:x.journeyId,attributionStatus:x.attribution.status,commerceLinked:established(x,"commerce_linked"),deterministicIdentityBridge:established(x,"deterministic_identity_bridge")}))};
 },
 async explain(s:ProductionCustomerScope,customerId:string,journeyId?:string):Promise<JourneyIntelligence|null>{
  if(!s.authenticated||!customerId)return null;
  const d=await get(`/v1/customers/${encodeURIComponent(customerId)}?${qs(s)}`);
  const journeys=Array.isArray(d.journeys)?d.journeys:[];const selected=journeyId?journeys.find((x:any)=>String(x?.id||"")===journeyId):journeys[0];if(!selected?.id)return{customerId,journeyId:null,chronology:[],attribution:{status:"unresolved",affiliateId:null,offerId:null,source:null,primaryEvidenceEventIds:[],corroboratingEventIds:[],supportingEventIds:[]},relationships:[],evidenceGroups:[],conclusions:[{type:"attribution_established",status:"unresolved",summary:"No canonical Journey is available to support an attribution conclusion.",evidenceEventIds:[],relationshipTypes:[],evidenceGroupIndexes:[]}],commerce:(d.orders||[]).map((o:any)=>({orderId:String(o?.order_id||o?.platform_order_id||""),amount:Number.isFinite(Number(o?.amount))?Number(o.amount):null,status:String(o?.status||"Unknown"),createdAt:o?.created_at?String(o.created_at):null})),evidenceLimits:["No canonical Journey was returned for this customer."]};
  const j=await get(`/v1/customers/${encodeURIComponent(customerId)}/journeys/${encodeURIComponent(selected.id)}?${qs(s,{limit:100})}`);
  return buildJourneyIntelligence(d,j,customerId,selected);
 }
};
