import{createHash,randomUUID}from"node:crypto";import type{TraceKitSessionContext}from"@/lib/identity/persistent-types";import{createTraceKitShopifyWebhookSubscription,deleteTraceKitShopifyWebhookSubscription,listTraceKitShopifyWebhookSubscriptions,SHOPIFY_PROOF_ONLY_TOPIC,type ShopifyWebhookSubscription}from"@/lib/commerce/shopify-webhook-registration";import type{StoredShopifyCredential}from"@/lib/commerce/shopify-verifier";import{findMcpActionAuthorization,issueMcpActionAuthorization,consumeMcpActionAuthorization}from"./action-authorization-repository";import{persistMcpExecutionResult,readMcpExecutionResult}from"./action-execution-result-repository";import{markShopifyMutationCreated,markShopifyRollbackVerified,readShopifyMutationRecovery}from"./m15-shopify-recovery-repository";import type{ShopifyControlledProofPlan}from"./m15-shopify-intent-repository";
export function buildShopifyProofEnvelope(input:{organizationId:string;plan:ShopifyControlledProofPlan;idempotencyKey:string;auditCorrelationId:string;createdAt:string;expiresAt:string}){const canonical=JSON.stringify({organizationId:input.organizationId,operation:input.plan.operation,connectionId:input.plan.connectionId,shopDomain:input.plan.shopDomain,callbackUrl:input.plan.callbackUrl,topic:input.plan.topic,idempotencyKey:input.idempotencyKey,auditCorrelationId:input.auditCorrelationId,createdAt:input.createdAt}),envelopeIdentity="shopify-exec-v1-"+createHash("sha256").update(canonical).digest("hex").slice(0,12);return{state:"authorized",organizationId:input.organizationId,envelopeIdentity,idempotencyKey:input.idempotencyKey,auditCorrelationId:input.auditCorrelationId,createdAt:input.createdAt,expiresAt:input.expiresAt};}
export async function orchestrateShopifyControlledProof(session:TraceKitSessionContext,input:{intentId:string;plan:ShopifyControlledProofPlan;credential:StoredShopifyCredential;idempotencyKey:string;auditCorrelationId:string;requestedAt:string;expiresAt:string;consumptionId:string;executionEnabled:boolean;fetchImpl?:typeof fetch}){
 const envelope=buildShopifyProofEnvelope({organizationId:session.activeOrganization!.id,plan:input.plan,idempotencyKey:input.idempotencyKey,auditCorrelationId:input.auditCorrelationId,createdAt:input.requestedAt,expiresAt:input.expiresAt});
 if(!input.executionEnabled||!session.effectivePermissions.includes("actions.execute"))return{status:"rejected" as const,reason:"capability_execution_disabled",envelope,execution:null,executionAvailable:false,netProviderConfigurationMutation:false};
 const recovery=await readShopifyMutationRecovery({organizationId:envelope.organizationId,intentId:input.intentId});if(!recovery||recovery.plan_identity==null||recovery.shop_domain!==input.plan.shopDomain||recovery.callback_url!==input.plan.callbackUrl||recovery.topic!==input.plan.topic)return{status:"rejected" as const,reason:"recovery_binding_invalid",envelope,execution:null,executionAvailable:false,netProviderConfigurationMutation:false};
 const authorization=(await findMcpActionAuthorization(envelope))||await issueMcpActionAuthorization(envelope),durable=await consumeMcpActionAuthorization({authorizationId:authorization.authorizationId,envelope,requestedAt:input.requestedAt,consumptionId:input.consumptionId});
 if(durable.decision==="replay_same_result"){const prior=await readMcpExecutionResult<any>({envelope});return prior?{status:"completed" as const,reason:"replay_same_result",envelope,execution:prior,executionAvailable:true,netProviderConfigurationMutation:false}:{status:"rejected" as const,reason:"replay_result_unavailable",envelope,execution:null,executionAvailable:false,netProviderConfigurationMutation:false};}
 if(durable.decision!=="consume"||!durable.consumptionId)return{status:"rejected" as const,reason:"authorization_rejected",envelope,execution:null,executionAvailable:false,netProviderConfigurationMutation:false};
 let subscription:ShopifyWebhookSubscription;
 if(recovery.state==="created"&&recovery.created_external_id){subscription={id:String(recovery.created_external_id),topic:SHOPIFY_PROOF_ONLY_TOPIC,uri:input.plan.callbackUrl};}
 else if(recovery.state==="prepared"){const existing=await listTraceKitShopifyWebhookSubscriptions({credential:input.credential,callbackUrl:input.plan.callbackUrl,fetchImpl:input.fetchImpl}),proof=existing.filter(s=>s.topic===SHOPIFY_PROOF_ONLY_TOPIC);if(proof.length===1){subscription=proof[0];await markShopifyMutationCreated({organizationId:envelope.organizationId,intentId:input.intentId,externalId:subscription.id});}else if(proof.length>1)return{status:"rejected" as const,reason:"ambiguous_proof_topic_state",envelope,execution:null,executionAvailable:false,netProviderConfigurationMutation:true};else{const created=await createTraceKitShopifyWebhookSubscription({credential:input.credential,callbackUrl:input.plan.callbackUrl,topic:SHOPIFY_PROOF_ONLY_TOPIC,fetchImpl:input.fetchImpl});if(created.decision!=="created")return{status:"rejected" as const,reason:"proof_topic_not_disposable",envelope,execution:null,executionAvailable:false,netProviderConfigurationMutation:false};subscription=created.subscription;await markShopifyMutationCreated({organizationId:envelope.organizationId,intentId:input.intentId,externalId:subscription.id});}}
 else return{status:"rejected" as const,reason:"recovery_state_invalid",envelope,execution:null,executionAvailable:false,netProviderConfigurationMutation:false};
 const rollback=await deleteTraceKitShopifyWebhookSubscription({credential:input.credential,subscription,callbackUrl:input.plan.callbackUrl,fetchImpl:input.fetchImpl});if(!rollback.verifiedAbsent)return{status:"recovery_required" as const,reason:"rollback_not_verified",envelope,execution:{createdExternalId:subscription.id},executionAvailable:false,netProviderConfigurationMutation:true};
 await markShopifyRollbackVerified({organizationId:envelope.organizationId,intentId:input.intentId,externalId:subscription.id});
 const execution={status:"completed" as const,provider:"shopify" as const,operation:"controlled_webhook_create_delete_proof" as const,consumptionId:durable.consumptionId,createdExternalId:subscription.id,createVerified:true,rollbackExternalId:rollback.deletedSubscriptionId,rollbackVerified:true,netProviderConfigurationMutation:false,audit:{idempotencyKey:input.idempotencyKey,auditCorrelationId:input.auditCorrelationId,executionId:randomUUID()}};
 await persistMcpExecutionResult({envelope,consumptionId:durable.consumptionId,result:execution});return{status:"completed" as const,reason:"completed",envelope,execution,executionAvailable:true,netProviderConfigurationMutation:false};
}
