import type { OrderListFilter, OrderSearchResult, OrderSummary, OrderWorkspaceSnapshot } from "@/lib/orders/types";
type Scope={authenticated:boolean;workspaceId:string;organizationId:string|null;businessContextId:string|null;session:any};
function base(){return String(process.env.TRACEKIT_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE||"http://127.0.0.1:8787").replace(/\/+$/,"");}
function secret(){return String(process.env.TK_SECRET_KEY||process.env.TRACEKIT_TK_SECRET||"").trim();}
async function get(path:string){const s=secret();if(!s)throw new Error("mcp_order_repository_unavailable");const r=await fetch(`${base()}${path}`,{cache:"no-store",headers:{accept:"application/json","x-tk-secret":s}});const t=await r.text();let b:any={};try{b=t?JSON.parse(t):{};}catch{}if(!r.ok)throw new Error("mcp_order_repository_failed");return b;}
function qs(scope:Scope,x:Record<string,unknown>={}){const p=new URLSearchParams({workspace_id:scope.workspaceId});for(const[k,v]of Object.entries(x))if(v!==null&&v!==undefined&&v!=="")p.set(k,String(v));return p.toString();}
const n=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
function status(v:any):OrderSummary["status"]{const s=String(v||"").toLowerCase();if(/chargeback|dispute/.test(s))return"Chargeback";if(/refund|return|void|cancel/.test(s))return"Refunded";if(/pending|open/.test(s))return"Pending";return"Paid";}
function oid(r:any){return String(r?.order_id||r?.platform_order_id||r?.id||"");}
function sum(r:any,c:any,s:Scope):OrderSummary{return{id:oid(r),organizationId:s.organizationId||"",offerId:String(r?.everflow_offer_id||r?.offer_id||""),customerId:String(c?.id||""),number:String(r?.order_id||r?.platform_order_id||oid(r)),customerName:String(c?.display_name||c?.primary_email||c?.id||"Customer"),customerEmail:String(c?.primary_email||""),customerPhone:String(c?.primary_phone||""),sensitiveMasked:false,scenario:"Production order",date:String(r?.created_at||r?.order_ts||"Not observed"),status:status(r?.status),profitStatus:"Estimated",profit:null,revenue:n(r?.amount??r?.gross_amount),trackingHealth:"Unknown",shippingLoss:false,highFee:false,highAffiliate:false};}
async function detail(s:Scope,id:string){return get(`/v1/customers/${encodeURIComponent(id)}?${qs(s)}`);}
export const mcpOrderRepository={
 async listOrders(s:Scope,f:OrderListFilter={}):Promise<OrderSummary[]>{if(!s.authenticated||!s.workspaceId)return[];if(f.customerId){const d=await detail(s,f.customerId);let rows=(d.orders||[]).map((r:any)=>sum(r,d.customer,s));if(f.offerId)rows=rows.filter((r:OrderSummary)=>!r.offerId||r.offerId===f.offerId);if(f.query){const q=f.query.toLowerCase();rows=rows.filter((r:OrderSummary)=>`${r.number} ${r.customerName} ${r.customerEmail}`.toLowerCase().includes(q));}return rows;}const l=await get(`/v1/customers?${qs(s,{limit:25})}`);const ds=await Promise.all((l.customers||[]).slice(0,25).map((r:any)=>detail(s,String(r?.customer?.id||"")).catch(()=>null)));let rows=ds.filter(Boolean).flatMap((d:any)=>(d.orders||[]).map((r:any)=>sum(r,d.customer,s)));if(f.offerId)rows=rows.filter((r:OrderSummary)=>r.offerId===f.offerId);if(f.query){const q=f.query.toLowerCase();rows=rows.filter((r:OrderSummary)=>`${r.number} ${r.customerName} ${r.customerEmail}`.toLowerCase().includes(q));}return rows;},
 async loadWorkspace(s:Scope,id:string):Promise<OrderWorkspaceSnapshot|null>{const rows=await this.listOrders(s,{});const o=rows.find((x:OrderSummary)=>x.id===id||x.number===id);if(!o)return null;return{order:o,commercial:{mainProduct:"Not available from current Order read model",orderBumps:[],upsells:[],shippingCharged:0,taxCollected:0,discounts:0,quantity:0},ledger:[],shipping:{charged:0,actual:0,packaging:0,margin:0},processorFee:{processor:"Not available",pricingRule:"Not available",percentageRate:0,fixedFee:0,currency:"USD",captures:[],expectedFee:0,observedFee:0,variance:0,settlementStatus:"Not available"},attribution:{trafficSource:"Not observed",affiliate:"Not observed",campaign:"Not observed",creative:"Not observed",offerUrl:"Not observed",landingPage:"Not observed",clickPurchaseDelta:"Not calculated"},timeline:[],identifiers:[],relatedCustomer:{id:o.customerId,name:o.customerName},relatedOffer:{id:o.offerId,name:o.offerId?`Offer ${o.offerId}`:"Not observed"},trackingExplanation:"Order commerce evidence loaded through the server-native MCP repository.",waitingOn:[],intelligence:[]};},
 async search(s:Scope,q:string):Promise<OrderSearchResult[]>{const rows=await this.listOrders(s,{query:q});return rows.slice(0,12).map((r:OrderSummary)=>({id:`order:${r.id}`,type:"Order",title:r.number,subtitle:r.customerName,value:r.id,href:`/orders?order_id=${encodeURIComponent(r.id)}`}));}
};
