export type ProviderOperationCandidate={
 provider:"commas"|"shopify"|"everflow";operation:string;mutation:boolean;boundedTarget:boolean;idempotency:"proven"|"partial"|"unknown";readBack:"proven"|"partial"|"unknown";recovery:"reversible"|"compensatable"|"irreversible"|"unknown";credentialGoverned:boolean;controlledObjectTestable:boolean;blockers:string[];
};
export const M11_PROVIDER_OPERATION_CANDIDATES:ProviderOperationCandidate[]=[
 {provider:"commas",operation:"webhook_test_delivery",mutation:false,boundedTarget:true,idempotency:"proven",readBack:"proven",recovery:"reversible",credentialGoverned:true,controlledObjectTestable:true,blockers:["Test delivery is an external side effect but not a provider configuration mutation; use it as transport/readiness proof, not the first mutation."]},
 {provider:"commas",operation:"create_webhook_subscription",mutation:true,boundedTarget:true,idempotency:"partial",readBack:"proven",recovery:"unknown",credentialGoverned:true,controlledObjectTestable:false,blockers:["Existing implementation prevents duplicate exact target but no delete/rollback adapter is present.","Creation returns a secret that must be propagated to Cloudflare, creating a second-system side effect.","No controlled non-customer subscription target is established."]},
 {provider:"shopify",operation:"admin_graphql_mutation",mutation:true,boundedTarget:false,idempotency:"unknown",readBack:"partial",recovery:"unknown",credentialGoverned:true,controlledObjectTestable:false,blockers:["Current Shopify client is generic GraphQL transport and does not expose a bounded mutation operation.","No provider-specific idempotency/recovery contract is implemented."]},
 {provider:"everflow",operation:"provider_mutation",mutation:true,boundedTarget:false,idempotency:"unknown",readBack:"unknown",recovery:"unknown",credentialGoverned:true,controlledObjectTestable:false,blockers:["Current repository surfaces are ingestion/sync/read oriented; no bounded provider mutation adapter with read-back and recovery is established."]}
];
export function assessM11ProviderReadiness(candidates=M11_PROVIDER_OPERATION_CANDIDATES){return{externalMutationEnabled:false,transportProofCandidate:candidates.find(c=>c.provider==="commas"&&c.operation==="webhook_test_delivery")||null,mutationCandidates:candidates.filter(c=>c.mutation).map(c=>({...c,ready:c.blockers.length===0&&c.idempotency==="proven"&&c.readBack==="proven"&&c.recovery!=="unknown"&&c.controlledObjectTestable})),evidenceLimits:["Repository capability mapping establishes implementation readiness only; provider behavior must be proven against a controlled provider object before mutation enablement."]};}
