"use client";
import * as React from "react";
import type{GovernedActionHistory,LifecycleEvidence}from"@/lib/mcp/governed-action-history";

const badge=(e:LifecycleEvidence)=><span className={`rounded-full px-2 py-1 text-xs ${e.availability==="available"?"bg-emerald-100 text-emerald-800":e.availability==="certification_artifact_only"?"bg-violet-100 text-violet-800":e.availability==="partial"?"bg-amber-100 text-amber-800":"bg-slate-100 text-slate-600"}`}>{e.availability.replaceAll("_"," ")}</span>;
export function GovernedActionHistoryPanel(){
 const[intentId,setIntentId]=React.useState("");const[data,setData]=React.useState<GovernedActionHistory|null>(null);const[error,setError]=React.useState<string|null>(null);const[confirming,setConfirming]=React.useState(false);const[confirmationNotice,setConfirmationNotice]=React.useState<string|null>(null);
 const loadIntent=React.useCallback(async(id:string)=>{const normalized=id.trim();if(!normalized)return;setError(null);setData(null);const response=await fetch(`/api/intelligence/action-history/${encodeURIComponent(normalized)}`,{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok){setError("Governed action history is unavailable.");return;}setData(body.history);},[]);
 React.useEffect(()=>{const linked=new URLSearchParams(window.location.search).get("intent_id")||"";if(linked){setIntentId(linked);void loadIntent(linked);}},[loadIntent]);
 async function load(event:React.FormEvent){event.preventDefault();await loadIntent(intentId);}
 async function confirm(){if(!data||confirming)return;setConfirming(true);setConfirmationNotice(null);try{const response=await fetch("/api/actions/provider-confirm",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({operation:data.intent.operation,intentId:data.intent.id})}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error("confirmation_failed");setConfirmationNotice(`Confirmed — ${body.confirmationId}`);await loadIntent(data.intent.id);}catch{setConfirmationNotice("Confirmation was not accepted. Reload the current lifecycle before retrying.");}finally{setConfirming(false);}}
 const confirmationAvailable=Boolean(data&&!data.confirmation&&data.intent.operation==="shopify.controlled_webhook_create_delete_proof"&&new Date(data.intent.expiresAt).getTime()>Date.now());
 return <section className="space-y-4 rounded-xl border p-4"><header><h2 className="text-lg font-semibold">Governed action history</h2><p className="text-sm text-slate-500">Inspect durable lifecycle evidence by intent ID. Missing and certification-only evidence is labeled explicitly.</p></header>
 <form onSubmit={load} className="flex gap-2"><label className="sr-only" htmlFor="governed-intent">Intent ID</label><input id="governed-intent" required value={intentId} onChange={e=>setIntentId(e.target.value)} placeholder="Intent ID" className="min-w-0 flex-1 rounded-md border px-3 py-2 text-sm"/><button className="rounded-md bg-slate-900 px-4 py-2 text-sm text-white">View history</button></form>{error?<p className="text-sm text-rose-700">{error}</p>:null}
 {data?<div className="space-y-4 text-sm"><div className="grid gap-2 md:grid-cols-2"><p><b>Operation:</b> {data.intent.operation}</p><p><b>Status:</b> {data.finalStatus}</p><p><b>Actor:</b> {data.intent.actor.name||data.intent.actor.id}</p><p><b>Target:</b> {data.intent.target.shopDomain||data.intent.targetKind||"Unavailable"}</p><p><b>Plan:</b> {data.intent.planIdentity}</p><p><b>Prepared:</b> {new Date(data.intent.issuedAt).toLocaleString()}</p><p><b>Expires:</b> {new Date(data.intent.expiresAt).toLocaleString()}</p><p><b>Net provider state changed:</b> {data.execution?.netProviderConfigurationMutation==null?"Unavailable":data.execution.netProviderConfigurationMutation?"Yes":"No"}</p></div>
 {confirmationAvailable?<div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-amber-950"><p className="font-medium">Explicit confirmation required</p><p className="mt-1 text-xs">Confirmation does not execute the action. Execution remains separately governed.</p><button type="button" disabled={confirming} onClick={confirm} className="mt-3 rounded-md bg-slate-900 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{confirming?"Confirming…":"Confirm exact prepared action"}</button></div>:!data.confirmation?<p className="rounded-md border p-3 text-slate-500">This intent is expired or otherwise non-actionable.</p>:null}{confirmationNotice?<p className="text-xs">{confirmationNotice}</p>:null}
 <p><b>Confirmed by:</b> {data.confirmation?.actor.name||data.confirmation?.actor.id||"Unavailable"}</p><ol className="space-y-2">{Object.entries(data.stages).map(([name,e])=><li key={name} className="rounded-md border p-3"><div className="flex items-center justify-between gap-3"><span className="font-medium capitalize">{name.replaceAll("_"," ")}</span>{badge(e)}</div><p className="mt-1 text-xs text-slate-500">{e.sourceType}{e.sourceIds.length?` · ${e.sourceIds.join(", ")}`:""}</p></li>)}</ol>
 <div className="grid gap-2 md:grid-cols-2"><div className="rounded-md border p-3"><b>Independent provider read-back</b><div className="mt-2">{badge(data.independentProviderReadBack)}</div></div><div className="rounded-md border p-3"><b>Observed replay</b><div className="mt-2">{badge(data.replay.observedReplay)}</div><p className="mt-2 text-xs">Durable result reusable: {data.replay.durableResultReusable?"Yes":"No"}; execution count remains one.</p></div></div></div>:null}</section>;
}
