import "server-only";
import { marketingPersistenceRequest } from "./marketing-provider-repository";
type Row=Record<string,any>;export type GoogleSyncControlTransport=(path:string,init?:RequestInit)=>Promise<Row[]>;

export async function createGoogleSyncRun(input:{organizationId:string;connectionId:string;providerAccountId:string;requestedByUserId:string;mode:"incremental"|"historical_backfill";transport?:GoogleSyncControlTransport;now?:string}){
 const t=input.transport||marketingPersistenceRequest,now=input.now||new Date().toISOString();const rows=await t("marketing_sync_runs",{method:"POST",body:JSON.stringify({organization_id:input.organizationId,connection_id:input.connectionId,provider_account_id:input.providerAccountId,sync_type:"google_ads_daily",mode:input.mode,status:"running",started_at:now,requested_by_user_id:input.requestedByUserId,metadata:{provider:"google_ads",manual:true},created_at:now,updated_at:now})});if(!rows[0])throw new Error("Google Ads sync run could not be created.");return rows[0];
}
export async function completeGoogleSyncWindow(input:{organizationId:string;connectionId:string;providerAccountId:string;runId:string;since:string;until:string;seen:number;persisted:number;failed:number;requestIds:string[];transport?:GoogleSyncControlTransport;now?:string}){
 const t=input.transport||marketingPersistenceRequest,now=input.now||new Date().toISOString();const rows=await t("marketing_sync_checkpoints",{method:"POST",body:JSON.stringify({sync_run_id:input.runId,organization_id:input.organizationId,connection_id:input.connectionId,provider_account_id:input.providerAccountId,resource:"ad_daily",checkpoint_kind:"time_window",report_date_start:input.since,report_date_end:input.until,records_seen:input.seen,records_persisted:input.persisted,records_failed:input.failed,state:input.failed?"failed":"completed",completed_at:now,metadata:{provider:"google_ads",google:{requestIds:input.requestIds}},created_at:now,updated_at:now})});if(!rows[0])throw new Error("Google Ads checkpoint could not be created.");return rows[0];
}
export async function finishGoogleSyncRun(input:{organizationId:string;runId:string;status:"completed"|"completed_with_warnings"|"failed";seen:number;created:number;updated:number;unchanged:number;failed:number;errorCode?:string;transport?:GoogleSyncControlTransport;now?:string}){
 const t=input.transport||marketingPersistenceRequest,now=input.now||new Date().toISOString();const rows=await t(`marketing_sync_runs?id=eq.${encodeURIComponent(input.runId)}&organization_id=eq.${encodeURIComponent(input.organizationId)}`,{method:"PATCH",body:JSON.stringify({status:input.status,completed_at:now,records_seen:input.seen,records_created:input.created,records_updated:input.updated,records_unchanged:input.unchanged,records_failed:input.failed,last_error_code:input.errorCode||null,last_error_summary:input.errorCode?"Google Ads sync failed safely.":null,updated_at:now})});if(!rows[0])throw new Error("Google Ads sync run could not be finalized.");return rows[0];
}
export async function ensureGoogleSyncScheduleDisabled(input:{organizationId:string;connectionId:string;providerAccountId:string;overlapDays:number;transport?:GoogleSyncControlTransport;now?:string}){
 const t=input.transport||marketingPersistenceRequest,now=input.now||new Date().toISOString();const existing=await t(`marketing_sync_schedules?organization_id=eq.${encodeURIComponent(input.organizationId)}&connection_id=eq.${encodeURIComponent(input.connectionId)}&provider_account_id=eq.${encodeURIComponent(input.providerAccountId)}&resource=eq.ad_daily&limit=1`);if(existing[0])return existing[0];
 const rows=await t("marketing_sync_schedules",{method:"POST",body:JSON.stringify({organization_id:input.organizationId,connection_id:input.connectionId,provider_account_id:input.providerAccountId,resource:"ad_daily",enabled:false,activation_state:"disabled",sync_frequency:"manual",overlap_days:input.overlapDays,metadata:{provider:"google_ads",activation:"explicit_only"},created_at:now,updated_at:now})});if(!rows[0])throw new Error("Google Ads schedule could not be initialized.");return rows[0];
}
