export type TkidPrivacyMode="essential"|"analytics_allowed";
export const TRACEKIT_JOURNEY_SDK_VERSION="1.1.0";
export type TraceKitJourneyErrorCode="invalid_configuration"|"network_unavailable"|"bootstrap_failed"|"event_ingest_failed"|"proof_not_started"|"proof_expired"|"journey_budget_exhausted"|"event_budget_exhausted"|"ingestion_stopped"|"unsupported_abuse_adapter"|"source_disabled"|"rate_limited"|"abuse_control_unavailable";
export type TraceKitJourneyError={code:TraceKitJourneyErrorCode;phase:"configuration"|"bootstrap"|"events"};
export type TraceKitJourneyConfig={endpoint:string;publicSourceId:string;privacyMode?:TkidPrivacyMode;autoPageView?:boolean;onError?:(error:TraceKitJourneyError)=>void};
export type TkidOffer={offerId:string;versionId:string;funnelStepId:string;price:{amount:string;currency:string;recurring:boolean;billingCadence?:string;trialState?:string};termsVersion?:string;disclosureVersion?:string;displayedDescriptor?:string;descriptorVersion?:string};
type Identity={journeyId:string;browserSessionId:string;journeyExpiresAt:string;browserSessionExpiresAt:string};
const STORAGE_KEY="tracekit.tkid.v1",BOOTSTRAP_KEY="tracekit.tkid.bootstrap.v1",MAX_QUEUE=20;
const TERMINAL_CODES=new Set<TraceKitJourneyErrorCode>(["proof_not_started","proof_expired","journey_budget_exhausted","event_budget_exhausted","ingestion_stopped","unsupported_abuse_adapter","source_disabled","rate_limited","abuse_control_unavailable"]);
const clients=new Map<string,TraceKitJourneyClient>();
export class TraceKitJourneyClient{
  readonly version=TRACEKIT_JOURNEY_SDK_VERSION;
  private identity:Identity|null=null;private queue:Array<{event:Record<string,unknown>;attempts:number}>=[];private flushing:Promise<void>|null=null;private starting:Promise<Identity|null>|null=null;private terminal:TraceKitJourneyErrorCode|null=null;
  constructor(private config:TraceKitJourneyConfig){this.config=validateConfig(config)}
  async startJourney(){if(this.terminal)return null;const cached=this.readIdentity();if(cached){this.identity=cached;return cached}if(this.starting)return this.starting;this.starting=this.bootstrap();try{return await this.starting}finally{this.starting=null}}
  async trackPageView(input:{pageId:string;funnelStepId?:string;durationBucket?:string}){return this.track("page_viewed",{page_id:input.pageId,funnel_step_id:input.funnelStepId,duration_bucket:input.durationBucket})}
  async trackFunnelStep(input:{funnelStepId:string}){return this.track("funnel_step_viewed",{funnel_step_id:input.funnelStepId})}
  async viewOffer(input:TkidOffer,upsell=false){return this.track(upsell?"upsell_viewed":"offer_viewed",this.offer(input))}
  async trackCta(input:{ctaId:string;ctaVersion:string;funnelStepId:string;actionType:string}){return this.track("cta_clicked",{cta_id:input.ctaId,cta_version:input.ctaVersion,funnel_step_id:input.funnelStepId,action_type:input.actionType})}
  async decideOffer(input:TkidOffer,accepted:boolean){return this.track(accepted?"offer_accepted":"offer_declined",this.offer(input))}
  async startCheckout(input:{checkoutSessionId:string;funnelStepId:string}){return this.track("checkout_started",{checkout_session_id:input.checkoutSessionId,funnel_step_id:input.funnelStepId})}
  async submitCheckout(input:{checkoutSessionId:string;funnelStepId:string}){return this.track("checkout_submitted",{checkout_session_id:input.checkoutSessionId,funnel_step_id:input.funnelStepId})}
  async confirmPurchase(input:{checkoutSessionId:string;funnelStepId:string}){return this.track("purchase_confirmed",{checkout_session_id:input.checkoutSessionId,funnel_step_id:input.funnelStepId})}
  async confirmationViewed(input:{checkoutSessionId:string;pageId:string}){return this.track("confirmation_viewed",{checkout_session_id:input.checkoutSessionId,page_id:input.pageId})}
  async receiptObserved(input:{checkoutSessionId:string;state:"requested"|"sent"|"delivered"}){return this.track("receipt_observed",{checkout_session_id:input.checkoutSessionId,action_type:input.state})}
  async vslMilestone(input:{funnelStepId:string;milestone:"25%"|"50%"|"75%"|"90%"|"completed"}){if(this.mode()!=="analytics_allowed")return false;return this.track("vsl_milestone",{funnel_step_id:input.funnelStepId,milestone:input.milestone})}
  async clientError(input:{code:string;category:string;funnelStepId?:string;appVersion:string;pageId:string}){return this.track("client_error",{error:{code:input.code,category:input.category},funnel_step_id:input.funnelStepId,app_version:input.appVersion,page_id:input.pageId})}
  async handoffJourney(targetOrigin:string){if(!this.identity)return null;try{const response=await fetch(`${this.config.endpoint}/v1/tkid/handoff`,{method:"POST",headers:{"content-type":"application/json","x-tracekit-source":this.config.publicSourceId},body:JSON.stringify({action:"issue",target_origin:new URL(targetOrigin).origin,journey_id:this.identity.journeyId,browser_session_id:this.identity.browserSessionId})});return response.ok?(await response.json() as any).token:null}catch{return null}}
  async consumeHandoff(token:string){try{const response=await fetch(`${this.config.endpoint}/v1/tkid/handoff`,{method:"POST",headers:{"content-type":"application/json","x-tracekit-source":this.config.publicSourceId},body:JSON.stringify({action:"consume",token})});if(!response.ok)return false;const value=await response.json() as any;this.identity={journeyId:value.journey_id,browserSessionId:value.browser_session_id,journeyExpiresAt:new Date(Date.now()+2*60*60*1000).toISOString(),browserSessionExpiresAt:new Date(Date.now()+30*60*1000).toISOString()};this.writeIdentity(this.identity);await this.track("cross_domain_handoff",{action_type:"consumed",page_id:location.pathname});return true}catch{return false}}
  async flush(){if(this.terminal||!this.queue.length)return;if(this.flushing)return this.flushing;this.flushing=this.drain();try{await this.flushing}finally{this.flushing=null;if(!this.terminal&&this.queue.length)await this.flush()}}
  private async drain(){while(!this.terminal&&this.queue.length){const items=this.queue.splice(0,MAX_QUEUE),body=JSON.stringify({events:items.map(item=>item.event)});try{const response=await fetch(`${this.config.endpoint}/v1/tkid/events`,{method:"POST",headers:{"content-type":"application/json","x-tracekit-source":this.config.publicSourceId},body,keepalive:true});if(response.ok)continue;const code=await safeCode(response,"event_ingest_failed");this.fail(code,"events");if(!TERMINAL_CODES.has(code))this.requeue(items)}catch{this.fail("network_unavailable","events");this.requeue(items)}if(this.queue.length)await new Promise(resolve=>setTimeout(resolve,100))}}
  private async track(event_name:string,fields:Record<string,unknown>){if(!this.identity&&!(await this.startJourney()))return false;if(!this.identity)return false;this.queue.push({event:{event_id:crypto.randomUUID(),event_name,schema_version:1,occurred_at:new Date().toISOString(),journey_id:this.identity.journeyId,browser_session_id:this.identity.browserSessionId,privacy_mode:this.mode(),...fields},attempts:0});this.queue=this.queue.slice(-MAX_QUEUE);await this.flush();return !this.terminal}
  private offer(input:TkidOffer){return{offer_id:input.offerId,offer_version_id:input.versionId,funnel_step_id:input.funnelStepId,price:{amount:input.price.amount,currency:input.price.currency,recurring:input.price.recurring,billing_cadence:input.price.billingCadence,trial_state:input.price.trialState},terms_version:input.termsVersion,disclosure_version:input.disclosureVersion,displayed_descriptor:input.displayedDescriptor,descriptor_version:input.descriptorVersion}}
  private async bootstrap(){try{const bootstrapKey=this.readBootstrapKey();const response=await fetch(`${this.config.endpoint}/v1/tkid/bootstrap`,{method:"POST",headers:{"x-tracekit-source":this.config.publicSourceId,"x-tracekit-bootstrap-key":bootstrapKey}});if(!response.ok){this.fail(await safeCode(response,"bootstrap_failed"),"bootstrap");return null}const value=await response.json() as any;this.identity={journeyId:value.journey_id,browserSessionId:value.browser_session_id,journeyExpiresAt:value.journey_expires_at,browserSessionExpiresAt:value.browser_session_expires_at};this.writeIdentity(this.identity);sessionStorage.removeItem(BOOTSTRAP_KEY);await this.track("journey_started",{});if(this.config.autoPageView)await this.trackPageView({pageId:location.pathname});return this.identity}catch{this.fail("network_unavailable","bootstrap");return null}}
  private fail(code:TraceKitJourneyErrorCode,phase:TraceKitJourneyError["phase"]){if(TERMINAL_CODES.has(code)){this.terminal=code;this.queue=[]}try{this.config.onError?.({code,phase})}catch{}}
  private requeue(items:Array<{event:Record<string,unknown>;attempts:number}>){const retry=items.filter(item=>item.attempts<2).map(item=>({...item,attempts:item.attempts+1}));this.queue.unshift(...retry);this.queue=this.queue.slice(0,MAX_QUEUE)}
  private mode(){return this.config.privacyMode||"essential"}
  private readBootstrapKey(){try{const prior=sessionStorage.getItem(BOOTSTRAP_KEY);if(prior)return prior;const created=crypto.randomUUID();sessionStorage.setItem(BOOTSTRAP_KEY,created);return created}catch{return crypto.randomUUID()}}
  private readIdentity(){try{const raw=sessionStorage.getItem(STORAGE_KEY);if(!raw)return null;const value=JSON.parse(raw) as Identity;if(Date.parse(value.browserSessionExpiresAt)<=Date.now()||Date.parse(value.journeyExpiresAt)<=Date.now()){sessionStorage.removeItem(STORAGE_KEY);return null}return value}catch{return null}}
  private writeIdentity(value:Identity){try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(value))}catch{}}
}
function validateConfig(config:TraceKitJourneyConfig){try{const endpoint=new URL(config.endpoint);if(endpoint.protocol!=="https:"||endpoint.username||endpoint.password||endpoint.search||endpoint.hash||endpoint.pathname!=="/")throw new Error();if(!/^tksrc_[a-z0-9][a-z0-9_-]{5,95}$/.test(config.publicSourceId)||!([undefined,"essential","analytics_allowed"] as unknown[]).includes(config.privacyMode)||typeof config.autoPageView!=="undefined"&&typeof config.autoPageView!=="boolean")throw new Error();return{...config,endpoint:endpoint.origin}}catch{try{config.onError?.({code:"invalid_configuration",phase:"configuration"})}catch{}throw new TypeError("Invalid TraceKit Journey configuration")}}
async function safeCode(response:Response,fallback:TraceKitJourneyErrorCode){try{const value=await response.json() as {code?:unknown};return typeof value.code==="string"&&TERMINAL_CODES.has(value.code as TraceKitJourneyErrorCode)?value.code as TraceKitJourneyErrorCode:fallback}catch{return fallback}}
export function initTraceKitJourney(config:TraceKitJourneyConfig){const valid=validateConfig(config),key=`${valid.endpoint}|${valid.publicSourceId}|${valid.privacyMode||"essential"}|${Boolean(valid.autoPageView)}`;const prior=clients.get(key);if(prior)return prior;const client=new TraceKitJourneyClient(valid);clients.set(key,client);return client}
