export type TkidPrivacyMode="essential"|"analytics_allowed";
export type TraceKitJourneyConfig={endpoint:string;publicSourceId:string;privacyMode?:TkidPrivacyMode;autoPageView?:boolean};
export type TkidOffer={offerId:string;versionId:string;funnelStepId:string;price:{amount:string;currency:string;recurring:boolean;billingCadence?:string;trialState?:string};termsVersion?:string;disclosureVersion?:string;displayedDescriptor?:string;descriptorVersion?:string};
type Identity={journeyId:string;browserSessionId:string;journeyExpiresAt:string;browserSessionExpiresAt:string};
const STORAGE_KEY="tracekit.tkid.v1",MAX_QUEUE=20;
export class TraceKitJourneyClient{
  private identity:Identity|null=null;private queue:Record<string,unknown>[]=[];private flushing=false;
  constructor(private config:TraceKitJourneyConfig){}
  async startJourney(){const cached=this.readIdentity();if(cached){this.identity=cached;return cached}try{const response=await fetch(`${this.config.endpoint}/v1/tkid/bootstrap`,{method:"POST",headers:{"x-tracekit-source":this.config.publicSourceId}});if(!response.ok)throw new Error("bootstrap failed");const value=await response.json() as any;this.identity={journeyId:value.journey_id,browserSessionId:value.browser_session_id,journeyExpiresAt:value.journey_expires_at,browserSessionExpiresAt:value.browser_session_expires_at};this.writeIdentity(this.identity);await this.track("journey_started",{});if(this.config.autoPageView)await this.trackPageView({pageId:location.pathname});return this.identity}catch{return null}}
  async trackPageView(input:{pageId:string;funnelStepId?:string;durationBucket?:string}){return this.track("page_viewed",{page_id:input.pageId,funnel_step_id:input.funnelStepId,duration_bucket:input.durationBucket})}
  async trackFunnelStep(input:{funnelStepId:string}){return this.track("funnel_step_viewed",{funnel_step_id:input.funnelStepId})}
  async viewOffer(input:TkidOffer,upsell=false){return this.track(upsell?"upsell_viewed":"offer_viewed",this.offer(input))}
  async trackCta(input:{ctaId:string;ctaVersion:string;funnelStepId:string;actionType:string}){return this.track("cta_clicked",{cta_id:input.ctaId,cta_version:input.ctaVersion,funnel_step_id:input.funnelStepId,action_type:input.actionType})}
  async decideOffer(input:TkidOffer,accepted:boolean){return this.track(accepted?"offer_accepted":"offer_declined",this.offer(input))}
  async startCheckout(input:{checkoutSessionId:string;funnelStepId:string}){return this.track("checkout_started",{checkout_session_id:input.checkoutSessionId,funnel_step_id:input.funnelStepId})}
  async submitCheckout(input:{checkoutSessionId:string;funnelStepId:string}){return this.track("checkout_submitted",{checkout_session_id:input.checkoutSessionId,funnel_step_id:input.funnelStepId})}
  async confirmPurchase(input:{checkoutSessionId:string;funnelStepId:string}){return this.track("purchase_confirmed",{checkout_session_id:input.checkoutSessionId,funnel_step_id:input.funnelStepId})}
  async confirmationViewed(input:{checkoutSessionId:string;pageId:string}){return this.track("confirmation_viewed",{checkout_session_id:input.checkoutSessionId,page_id:input.pageId})}
  async receiptObserved(input:{checkoutSessionId:string;state:"requested"|"sent"|"delivered"}){return this.track("receipt_observed",{checkout_session_id:input.checkoutSessionId,action_type:input.state})}
  async vslMilestone(input:{funnelStepId:string;milestone:"25%"|"50%"|"75%"|"90%"|"completed"}){if(this.mode()!=="analytics_allowed")return false;return this.track("vsl_milestone",{funnel_step_id:input.funnelStepId,milestone:input.milestone})}
  async clientError(input:{code:string;category:string;funnelStepId?:string;appVersion:string;pageId:string}){return this.track("client_error",{error:{code:input.code,category:input.category},funnel_step_id:input.funnelStepId,app_version:input.appVersion,page_id:input.pageId})}
  async handoffJourney(targetOrigin:string){if(!this.identity)return null;try{const response=await fetch(`${this.config.endpoint}/v1/tkid/handoff`,{method:"POST",headers:{"content-type":"application/json","x-tracekit-source":this.config.publicSourceId},body:JSON.stringify({action:"issue",target_origin:new URL(targetOrigin).origin,journey_id:this.identity.journeyId,browser_session_id:this.identity.browserSessionId})});return response.ok?(await response.json() as any).token:null}catch{return null}}
  async consumeHandoff(token:string){try{const response=await fetch(`${this.config.endpoint}/v1/tkid/handoff`,{method:"POST",headers:{"content-type":"application/json","x-tracekit-source":this.config.publicSourceId},body:JSON.stringify({action:"consume",token})});if(!response.ok)return false;const value=await response.json() as any;this.identity={journeyId:value.journey_id,browserSessionId:value.browser_session_id,journeyExpiresAt:new Date(Date.now()+2*60*60*1000).toISOString(),browserSessionExpiresAt:new Date(Date.now()+30*60*1000).toISOString()};this.writeIdentity(this.identity);await this.track("cross_domain_handoff",{action_type:"consumed",page_id:location.pathname});return true}catch{return false}}
  async flush(){if(this.flushing||!this.queue.length)return;this.flushing=true;const events=this.queue.splice(0,MAX_QUEUE),body=JSON.stringify({events});try{const response=await fetch(`${this.config.endpoint}/v1/tkid/events`,{method:"POST",headers:{"content-type":"application/json","x-tracekit-source":this.config.publicSourceId},body,keepalive:true});if(!response.ok)throw new Error("ingest failed")}catch{this.queue.unshift(...events);this.queue=this.queue.slice(0,MAX_QUEUE)}finally{this.flushing=false}}
  private async track(event_name:string,fields:Record<string,unknown>){if(!this.identity&&!(await this.startJourney()))return false;if(!this.identity)return false;this.queue.push({event_id:crypto.randomUUID(),event_name,schema_version:1,occurred_at:new Date().toISOString(),journey_id:this.identity.journeyId,browser_session_id:this.identity.browserSessionId,privacy_mode:this.mode(),...fields});this.queue=this.queue.slice(-MAX_QUEUE);await this.flush();return true}
  private offer(input:TkidOffer){return{offer_id:input.offerId,offer_version_id:input.versionId,funnel_step_id:input.funnelStepId,price:{amount:input.price.amount,currency:input.price.currency,recurring:input.price.recurring,billing_cadence:input.price.billingCadence,trial_state:input.price.trialState},terms_version:input.termsVersion,disclosure_version:input.disclosureVersion,displayed_descriptor:input.displayedDescriptor,descriptor_version:input.descriptorVersion}}
  private mode(){return this.config.privacyMode||"essential"}
  private readIdentity(){try{const raw=sessionStorage.getItem(STORAGE_KEY);if(!raw)return null;const value=JSON.parse(raw) as Identity;if(Date.parse(value.browserSessionExpiresAt)<=Date.now()||Date.parse(value.journeyExpiresAt)<=Date.now()){sessionStorage.removeItem(STORAGE_KEY);return null}return value}catch{return null}}
  private writeIdentity(value:Identity){try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(value))}catch{}}
}
export function initTraceKitJourney(config:TraceKitJourneyConfig){return new TraceKitJourneyClient(config)}
