import { resolveApplicationSession } from "@/lib/identity/application-session";
import { requirePermission } from "@/lib/identity/authorization-gateway";
import { readCommasAttributionQuality } from "@/lib/commerce/attribution-quality-repository";
import { AttributionQualityLatencySection } from "@/lib/commerce/attribution-quality-latency";

export const dynamic = "force-dynamic";

function Metric({ title, value, detail }: { title: string; value: string | number; detail?: string }) {
  return <div className="rounded-xl border border-slate-200 bg-white p-5"><div className="text-sm text-slate-500">{title}</div><div className="mt-2 text-2xl font-semibold text-slate-900">{value}</div>{detail && <div className="mt-1 text-xs text-slate-500">{detail}</div>}</div>;
}

export default async function CommasAttributionQualityPage() {
  const resolution = await resolveApplicationSession();
  if (resolution.kind !== "authenticated" || !resolution.session.activeOrganization) return <p className="p-8">Report unavailable.</p>;
  try { requirePermission(resolution.session, "connectors.view"); } catch { return <p className="p-8">Report unavailable.</p>; }
  let result: Awaited<ReturnType<typeof readCommasAttributionQuality>>;
  try { result = await readCommasAttributionQuality(resolution.session.activeOrganization.id); }
  catch { return <p className="p-8">Commas attribution quality is temporarily unavailable.</p>; }
  if (result.kind !== "available") return <p className="p-8">No active Commas connection is available for this organization.</p>;
  const r = result.report;
  const coverage = r.parameters as Record<string, { count: number; percentage: number } | number>;
  const entries = ["affid", "sub1", "sub4", "_ef_transaction_id", "transactionId", "tid", "c1"];
  return <main className="space-y-8 p-6 text-slate-900">
    <header><div className="text-xs font-semibold uppercase tracking-wide text-blue-700">Shadow Measurement · No Attribution Credit Impact</div><h1 className="mt-2 text-3xl font-semibold">Commas Attribution Quality</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Provider-observed checkout evidence, exact ORD identity, and Everflow comparison. This report makes no attribution decision.</p></header>
    <section className="grid gap-4 md:grid-cols-4" aria-label="Quality scorecards">
      <Metric title="Verified accepted purchases" value={r.total} detail="Normalized provider-observed purchase cohort" />
      <Metric title="Exact ORD identity" value={`${r.ord.matchRate}%`} detail={`${r.ord.exact} of ${r.total} purchases`} />
      <Metric title="Everflow exact" value={r.everflow.exact_match.count} detail={`${r.everflow.conflict.count} conflicts`} />
      <Metric title="Journey shadow" value={r.funnel.journeyShadow} detail="No attribution credit impact" />
    </section>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Quality funnel</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3 lg:grid-cols-8">{Object.entries({ "Accepted delivery": r.funnel.receivedDeliveries, Evidence: r.funnel.evidence, Observation: r.funnel.observation, "Payment ORD": r.funnel.validOrd, "Exact ORD": r.funnel.exactOrd, "Canonical order": r.funnel.canonicalOrder, "Everflow comparable": r.funnel.everflowComparable, "Journey shadow": r.funnel.journeyShadow }).map(([label, value]) => <div key={label}><div className="font-semibold">{value ?? "—"}</div><div className="text-slate-500">{label}</div></div>)}</div><p className="mt-3 text-xs text-slate-500">Unsigned or malformed rejected requests are not durably counted and are excluded from this verified-purchase cohort.</p></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Unmatched ORD identity</h2><p className="mt-2 text-sm">{r.ord.unmatched} unmatched · {r.ord.ambiguous} ambiguous · {r.ord.malformed} malformed.</p><div className="mt-2 grid gap-2 text-xs text-slate-600 sm:grid-cols-3">{Object.entries(r.ord.unmatchedReasons).map(([reason, value]) => <div key={reason}>{reason}: {value}</div>)}</div><p className="mt-2 text-xs text-slate-500">A purchase observed after the latest completed transaction sync is pending ingestion; this is separate from a mapping still absent after a completed sync.</p></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Provider-observed parameter coverage</h2><div className="mt-3 space-y-2 text-sm">{entries.map(key => { const v = coverage[key] as { count: number; percentage: number }; return <div className="flex justify-between border-b py-1" key={key}><span>{key}</span><span>{v.count} · {v.percentage}%</span></div>; })}</div></div><div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Independent source quality</h2><div className="mt-3 space-y-2 text-sm">{Object.entries(r.aliases).map(([key, value]) => <div className="flex justify-between border-b py-1" key={key}><span>Alias: {key}</span><span>{value.count} · {value.percentage}%</span></div>)}{Object.entries(r.everflow).map(([key, value]) => <div className="flex justify-between border-b py-1" key={key}><span>Stored Everflow: {key}</span><span>{value.count} · {value.percentage}%</span></div>)}{Object.entries(r.currentEverflow).map(([key, value]) => <div className="flex justify-between border-b py-1" key={`current-${key}`}><span>Current Everflow: {key}</span><span>{value}</span></div>)}</div><p className="mt-2 text-xs text-slate-500">{r.comparisonFreshness.storedNoRecordNowLinked} stored “no record” cases now have an exact current Everflow transaction identity; source observations were not changed.</p></div></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Daily quality · UTC</h2><div className="overflow-x-auto"><table className="mt-3 w-full text-left text-sm"><thead><tr className="border-b text-slate-500">{["Date", "Purchases", "Exact ORD", "TID coverage", "Affiliate coverage", "Alias conflicts", "Everflow exact", "Everflow conflicts"].map(h => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{r.daily.map(day => <tr className="border-b" key={day.date}><td className="p-2">{day.date}</td><td className="p-2">{day.purchases}</td><td className="p-2">{day.ordExactRate}%</td><td className="p-2">{day.transactionIdCoverage}%</td><td className="p-2">{day.affiliateCoverage}%</td><td className="p-2">{day.aliasConflictRate}%</td><td className="p-2">{day.everflowExactRate}%</td><td className="p-2">{day.everflowConflictRate}%</td></tr>)}</tbody></table></div></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Field-level agreement</h2><p className="text-xs text-slate-500">Current Everflow source values are compared by exact observed transaction ID. Stored comparison states above reflect the earlier observation or reconciliation; later Everflow ingestion can change current availability without changing source observations. Missing values are separate from disagreements.</p><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500">{["Field", "Comparable", "Agree", "Disagree", "Commas missing", "Everflow missing", "Both missing"].map(h => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{Object.entries(r.fieldAgreement).map(([field, result]) => <tr className="border-b" key={field}><td className="p-2">{field}</td><td className="p-2">{result.comparable}</td><td className="p-2">{result.agree}</td><td className="p-2">{result.disagree}</td><td className="p-2">{result.commasMissing}</td><td className="p-2">{result.everflowMissing}</td><td className="p-2">{result.bothMissing}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">No Commas transaction ID</h2><p className="mt-2 text-sm">{r.noTid.purchases} purchases; {r.noTid.exactOrd} exact ORD identities. Affiliate ID present: {r.noTid.affiliatePresent}; sub1: {r.noTid.sub1Present}; sub4: {r.noTid.sub4Present}.</p><p className="mt-2 text-sm font-medium">Commerce identity: known for exact ORD matches. Marketing attribution evidence: absent when all provider fields are missing.</p></div><div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Payment path</h2><p className="mt-2 text-sm">Unavailable. The normalized order payment type is not a trustworthy processor identifier.</p></div></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Conflict review</h2><p className="mt-1 text-xs text-slate-500">Field names and agreement states only. Source values remain restricted.</p><div className="mt-3 space-y-2 text-sm">{r.conflicts.length ? r.conflicts.map(conflict => <div className="rounded-lg border p-3" key={conflict.eventReference}><div className="font-mono text-xs">{conflict.eventReference}</div><div className="mt-1">{conflict.eventAt} · {conflict.ordMatchState} ORD · {conflict.derivationMode} · {conflict.classification}</div><div className="text-slate-600">Everflow {conflict.comparisonState}: {conflict.conflictingFields.join(", ") || "no field detail"}; Commas aliases: {conflict.conflictingAliases.join(", ") || "agree"}</div><div className="text-slate-600">Transaction identity {conflict.fieldDiagnostics.transactionIdentity}; affiliate ID {conflict.fieldDiagnostics.affiliateId}; sub1 {conflict.fieldDiagnostics.sub1}; sub4 {conflict.fieldDiagnostics.sub4}.</div></div>) : <p>No conflicts in the current cohort.</p>}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Derivation provenance</h2><p className="mt-2 text-sm">Evidence originally recorded by pre-fix normalizer: {r.provenance.evidenceReconciled}. Evidence recorded by live v2 normalizer: {r.provenance.liveNormalizer}. Observations subsequently reconciled: {r.provenance.laterReconciled}.</p><p className="mt-1 text-xs text-slate-500">The immutable Evidence normalizer version identifies the original path; later reconciliation may update derived observations.</p></div><div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Transaction ingestion health</h2><p className="mt-2 text-sm">Latest run: {result.ingestion.latestRun?.status || "none"} · completed {result.ingestion.latestRun?.completedAt || "pending"}. Latest represented order: {result.ingestion.latestOrderAt || "unknown"}.</p><p className="mt-1 text-sm">Numeric mappings: {result.ingestion.numericMappings}; ORD mappings: {result.ingestion.ordMappings}; projection gap: {result.ingestion.ordProjectionGap}.</p></div></section>
    <AttributionQualityLatencySection latency={r.latency} />
    <section className="rounded-xl border bg-blue-50 p-5"><h2 className="text-lg font-semibold">Sample maturity</h2><p className="mt-1 text-sm">{r.maturity.status} · {r.maturity.sample} total observations · {r.maturity.postCutover ?? 0} post-epoch live observations · {r.maturity.healthyDays ?? 0} certified full healthy days.</p><p className="mt-1 text-xs text-slate-600">Measurement epoch: {r.maturity.measurementEpochAt || "not configured"}. Target: 500 clean purchases or 7 certified days. Historical days without complete health evidence are not certified. No attribution credits are enabled by this report.</p></section>
  </main>;
}
