import { randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { resolveApplicationSession } from "@/lib/identity/application-session";
import { setTikTokAccountSelection } from "@/lib/integrations/tiktok-ads-connection";
import { listMarketingConnections, listMarketingProviderAccounts } from "@/lib/integrations/marketing-provider-repository";
import { TikTokOAuthError } from "@/lib/integrations/tiktok-ads-oauth";
export const dynamic = "force-dynamic";
function sameOrigin(request: Request) { const origin=request.headers.get("origin"), site=request.headers.get("sec-fetch-site"); return (!origin || origin===new URL(request.url).origin)&&(!site||site==="same-origin"); }
function failure(requestId:string,error:unknown){const p=error instanceof TikTokOAuthError?error:null;return NextResponse.json({ok:false,code:p?.code||"tiktok_accounts_failed",message:p?.message||"TraceKit could not update TikTok advertising accounts.",requestId},{status:p?.httpStatus||500,headers:{"cache-control":"no-store","x-tracekit-request-id":requestId}});}
export async function GET(request:NextRequest){const requestId=randomUUID();try{const resolution=await resolveApplicationSession();if(resolution.kind!=="authenticated"||!resolution.session.activeOrganization)throw new TikTokOAuthError("resource_unavailable","The requested resource is unavailable.",404);const connectionId=request.nextUrl.searchParams.get("connectionId")||"";const connections=await listMarketingConnections(resolution.session.activeOrganization.id,"tiktok_ads");if(!connections.some(c=>c.id===connectionId))throw new TikTokOAuthError("resource_unavailable","The requested resource is unavailable.",404);const accounts=await listMarketingProviderAccounts(resolution.session.activeOrganization.id,connectionId);return NextResponse.json({ok:true,provider:"tiktok_ads",connectionId,accounts,schedulesActivated:false,requestId},{headers:{"cache-control":"no-store","x-tracekit-request-id":requestId}});}catch(error){return failure(requestId,error);}}
export async function POST(request:NextRequest){const requestId=randomUUID();try{if(!sameOrigin(request))throw new TikTokOAuthError("request_verification_failed","Request verification failed.",403);if(Number(request.headers.get("content-length")||0)>65536)throw new TikTokOAuthError("payload_too_large","The TikTok account selection is too large.",413);const resolution=await resolveApplicationSession();if(resolution.kind!=="authenticated")throw new TikTokOAuthError("resource_unavailable","The requested resource is unavailable.",404);const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const connectionId=typeof body?.connectionId==="string"?body.connectionId.trim():"";const raw=Array.isArray(body?.accountIds)?body.accountIds:null;const accountIds=raw?raw.filter((v):v is string=>typeof v==="string"):[];if(!body||!raw||accountIds.length!==raw.length)throw new TikTokOAuthError("invalid_request","TikTok account selection is invalid.");const accounts=await setTikTokAccountSelection({session:resolution.session,connectionId,accountIds});return NextResponse.json({ok:true,provider:"tiktok_ads",connectionId,accounts,selectedAccountCount:accounts.filter((a:any)=>Boolean(a.selected_for_sync??a.selectedForSync)).length,schedulesActivated:false,requestId},{headers:{"cache-control":"no-store","x-tracekit-request-id":requestId}});}catch(error){return failure(requestId,error);}}
