import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { resolveApplicationSession } from "@/lib/identity/application-session";
import { commercePersistenceRequest } from "@/lib/commerce/supabase-control-repository";
import { authorizeInvestigationAccess } from "@/lib/investigations/authorization";
import { AuthorizationDeniedError } from "@/lib/identity/authorization-gateway";
import { enqueueInvestigationRun } from "@/lib/investigations/runtime";

type Row=Record<string,unknown>;
const json=(body:Record<string,unknown>,status=200)=>NextResponse.json(body,{status});
function sameOrigin(request:Request){const origin=request.headers.get("origin"),site=request.headers.get("sec-fetch-site");return(!origin||origin===new URL(request.url).origin)&&(!site||site==="same-origin");}
async function scope(){const resolution=await resolveApplicationSession();if(resolution.kind!=="authenticated"||!resolution.session.activeOrganization)throw new Error("unavailable");return{session:resolution.session,scope:authorizeInvestigationAccess(resolution.session,resolution.session.activeOrganization.id)};}
async function investigation(organizationId:string,id:string){const rows=await commercePersistenceRequest(`tracekit_investigations?organization_id=eq.${encodeURIComponent(organizationId)}&id=eq.${encodeURIComponent(id)}&limit=1`)as Row[];return rows[0]||null;}

export async function GET(_request:Request,context:{params:Promise<{investigationPath:string[]}>}){try{const{scope:authorized}=await scope(),path=(await context.params).investigationPath,id=path[0];if(path[1]!=="runs"||!id||!await investigation(authorized.organizationId,id))return json({ok:false,code:"resource_unavailable",message:"The requested resource is unavailable."},404);const rows=await commercePersistenceRequest(`tracekit_investigation_runs?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&investigation_id=eq.${encodeURIComponent(id)}&select=id,status,started_at,completed_at,heartbeat_at,attempt,records_evaluated,findings_produced,warnings,sanitized_failure_code,sanitized_failure_summary&order=created_at.desc&limit=20`)as Row[];return json({ok:true,runs:rows});}catch{return json({ok:false,code:"resource_unavailable",message:"The requested resource is unavailable."},404);}}

export async function POST(request:Request,context:{params:Promise<{investigationPath:string[]}>}){const requestId=randomUUID();try{if(!sameOrigin(request))return json({ok:false,code:"request_verification_failed",message:"Request verification failed.",requestId},403);const{session,scope:authorized}=await scope(),path=(await context.params).investigationPath,id=path[0];if(path[1]!=="runs"||!id||!await investigation(authorized.organizationId,id))return json({ok:false,code:"resource_unavailable",message:"The requested resource is unavailable.",requestId},404);const prior=await commercePersistenceRequest(`tracekit_investigation_runs?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&investigation_id=eq.${encodeURIComponent(id)}&order=created_at.desc&limit=1`)as Row[];if(!prior[0])return json({ok:false,code:"source_snapshot_unavailable",message:"A versioned source snapshot is required before this Investigation can run.",requestId},409);const p=prior[0],result=await enqueueInvestigationRun({accountId:authorized.accountId,organizationId:authorized.organizationId,investigationId:id,requestedByUserId:session.user.id,algorithmVersion:String(p.algorithm_version),commerceVersion:String(p.commerce_reconciliation_version),journeyVersion:String(p.journey_linkage_version),disputeVersion:String(p.dispute_reconciliation_version),reasonVersion:String(p.reason_normalization_version),cohortVersion:String(p.cohort_definition_version),sourceSnapshot:(p.source_snapshot||{})as Record<string,unknown>,evidenceCutoffAt:String(p.evidence_cutoff_at)});await commercePersistenceRequest("tracekit_audit_events",{method:"POST",body:JSON.stringify({actor_user_id:session.user.id,account_id:authorized.accountId,organization_id:authorized.organizationId,action:"investigation.created",target_type:"tracekit_investigation_run",target_id:result.id,result:"success",correlation_id:requestId,metadata:{reused:result.reused,status:result.status}})});return json({ok:true,runId:result.id,status:result.status,reused:result.reused,requestId},result.reused?200:202);}catch(error){if(error instanceof AuthorizationDeniedError)return json({ok:false,code:"resource_unavailable",message:"The requested resource is unavailable.",requestId},404);return json({ok:false,code:"internal_error",message:"TraceKit could not queue this Investigation.",requestId},500);}}
