import { randomBytes, randomUUID, createHash } from "node:crypto";
import { resolveTxt } from "node:dns/promises";
import { NextResponse } from "next/server";
import { resolveApplicationSession } from "@/lib/identity/application-session";
import { commercePersistenceRequest } from "@/lib/commerce/supabase-control-repository";
import { requireTkidOriginManagement } from "@/lib/tkid/origin-authorization";

type Row=Record<string,unknown>;
const json=(body:Record<string,unknown>,status=200)=>NextResponse.json(body,{status});
function sameOrigin(request:Request){const origin=request.headers.get("origin"),site=request.headers.get("sec-fetch-site");return(!origin||origin===new URL(request.url).origin)&&(!site||site==="same-origin")}
function canonicalize(input:unknown){if(typeof input!=="string"||input.length>255||input.includes("*"))throw new Error("invalid_origin");const u=new URL(input);if(u.protocol!=="https:"||u.username||u.password||u.pathname!=="/"||u.search||u.hash||!u.hostname||u.hostname.includes("_")||u.hostname.startsWith(".")||u.hostname.endsWith("."))throw new Error("invalid_origin");return u.origin.toLowerCase()}
async function scope(){const resolution=await resolveApplicationSession();if(resolution.kind!=="authenticated"||!resolution.session.activeOrganization)throw new Error("unavailable");requireTkidOriginManagement(resolution.session);return{session:resolution.session,organizationId:resolution.session.activeOrganization.id,accountId:resolution.session.activeOrganization.accountId}}
async function source(organizationId:string,sourceId:string){const rows=await commercePersistenceRequest(`tkid_sources?organization_id=eq.${encodeURIComponent(organizationId)}&id=eq.${encodeURIComponent(sourceId)}&limit=1`)as Row[];return rows[0]||null}
async function origin(organizationId:string,originId:string){const rows=await commercePersistenceRequest(`tkid_source_origins?organization_id=eq.${encodeURIComponent(organizationId)}&id=eq.${encodeURIComponent(originId)}&limit=1`)as Row[];return rows[0]||null}
async function audit(input:{session:any;organizationId:string;accountId:string;action:string;targetId:string;metadata:Record<string,unknown>}){await commercePersistenceRequest("tracekit_audit_events",{method:"POST",body:JSON.stringify({actor_user_id:input.session.user.id,account_id:input.accountId,organization_id:input.organizationId,action:input.action,target_type:"tkid_source_origin",target_id:input.targetId,result:"success",permission_evaluated:"admin.manage_feature_access",correlation_id:randomUUID(),metadata:input.metadata})})}
function safe(row:Row){return{id:String(row.id),sourceId:String(row.source_id),origin:String(row.canonical_origin),role:String(row.role),status:String(row.lifecycle_status),verificationState:String(row.verification_state),verifiedAt:row.verified_at?String(row.verified_at):null,retiredAt:row.retired_at?String(row.retired_at):null}}

export async function POST(request:Request,context:{params:Promise<{originPath:string[]}>}){
  try{
    if(!sameOrigin(request))return json({ok:false,code:"request_verification_failed",message:"Request verification failed."},403);
    const authorized=await scope(),path=(await context.params).originPath,body=await request.json().catch(()=>({}))as Record<string,unknown>;
    if(path[0]==="create"){
      const sourceId=String(body.sourceId||"");const ownedSource=await source(authorized.organizationId,sourceId);if(!ownedSource)return json({ok:false,code:"resource_unavailable",message:"The requested resource is unavailable."},404);
      const canonical=canonicalize(body.origin),role=String(body.role||"multi_purpose");if(!["frontend","checkout_return","oto","confirmation","multi_purpose"].includes(role))return json({ok:false,code:"invalid_role",message:"Choose an approved origin role."},400);
      const rows=await commercePersistenceRequest("tkid_source_origins",{method:"POST",body:JSON.stringify({account_id:ownedSource.account_id,organization_id:authorized.organizationId,business_context_id:ownedSource.business_context_id,source_id:sourceId,canonical_origin:canonical,role,lifecycle_status:"pending",verification_state:"unissued"})})as Row[];const created=rows[0];await audit({...authorized,action:"tkid.origin_added",targetId:String(created.id),metadata:{origin:canonical,role,status:"pending",sourceId}});return json({ok:true,origin:safe(created),message:"Origin added as Pending."},201);
    }
    const originId=path[0],action=path[1],existing=originId?await origin(authorized.organizationId,originId):null;if(!existing||!await source(authorized.organizationId,String(existing.source_id)))return json({ok:false,code:"resource_unavailable",message:"The requested resource is unavailable."},404);
    const metadata={origin:String(existing.canonical_origin),role:String(existing.role),sourceId:String(existing.source_id)};
    if(action==="issue-verification"){
      await commercePersistenceRequest(`tkid_origin_verifications?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&origin_id=eq.${encodeURIComponent(originId)}&state=eq.issued`,{method:"PATCH",body:JSON.stringify({state:"superseded",superseded_at:new Date().toISOString()})});
      const token=randomBytes(24).toString("base64url"),digest=createHash("sha256").update(token).digest("hex"),host=new URL(String(existing.canonical_origin)).hostname,recordName=`_tracekit.${host}`,expiresAt=new Date(Date.now()+24*60*60_000).toISOString();
      await commercePersistenceRequest("tkid_origin_verifications",{method:"POST",body:JSON.stringify({organization_id:authorized.organizationId,source_id:existing.source_id,origin_id:originId,record_name:recordName,token_digest:digest,token_hint:token.slice(-8),expires_at:expiresAt,executor_context:"product_admin"})});await commercePersistenceRequest(`tkid_source_origins?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&id=eq.${encodeURIComponent(originId)}`,{method:"PATCH",body:JSON.stringify({verification_state:"issued",updated_at:new Date().toISOString()})});await audit({...authorized,action:"tkid.origin_verification_issued",targetId:originId,metadata:{...metadata,method:"dns_txt",expiresAt}});return json({ok:true,verification:{method:"DNS_TXT",recordName,recordValue:`tracekit-origin-verification=${token}`,expiresAt},message:"DNS verification challenge issued. The value is shown only now."});
    }
    if(action==="verify"){
      if(process.env.TKID_ORIGIN_DNS_VERIFICATION_ENABLED!=="true")return json({ok:false,code:"verification_probe_disabled",message:"External DNS verification is disabled in this environment."},409);
      const challenges=await commercePersistenceRequest(`tkid_origin_verifications?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&origin_id=eq.${encodeURIComponent(originId)}&state=eq.issued&order=issued_at.desc&limit=1`)as Row[],challenge=challenges[0];if(!challenge||Date.parse(String(challenge.expires_at))<=Date.now())return json({ok:false,code:"verification_challenge_expired",message:"Issue a new verification challenge."},409);
      const values=(await resolveTxt(String(challenge.record_name))).flat();let matched=false;for(const value of values){const prefix="tracekit-origin-verification=";if(value.startsWith(prefix)&&createHash("sha256").update(value.slice(prefix.length)).digest("hex")===challenge.token_digest){matched=true;break}}
      if(!matched){await commercePersistenceRequest(`tkid_source_origins?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&id=eq.${encodeURIComponent(originId)}`,{method:"PATCH",body:JSON.stringify({verification_state:"failed",updated_at:new Date().toISOString()})});return json({ok:false,code:"origin_verification_failed",message:"The DNS TXT challenge was not found."},409)}
      const now=new Date().toISOString();await commercePersistenceRequest(`tkid_origin_verifications?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&id=eq.${encodeURIComponent(String(challenge.id))}`,{method:"PATCH",body:JSON.stringify({state:"verified",verified_at:now})});const rows=await commercePersistenceRequest(`tkid_source_origins?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&id=eq.${encodeURIComponent(originId)}`,{method:"PATCH",body:JSON.stringify({lifecycle_status:"verified",verification_state:"verified",verified_at:now,verified_by_context:"dns_verification_worker",updated_at:now})})as Row[];await audit({...authorized,action:"tkid.origin_verified",targetId:originId,metadata:{...metadata,method:"dns_txt"}});return json({ok:true,origin:safe(rows[0]),message:"Origin control verified. Activation remains separate."});
    }
    const now=new Date().toISOString(),status=String(existing.lifecycle_status),verified=existing.verification_state==="verified"&&Boolean(existing.verified_at);let patch:Row,verb:string;
    if(action==="activate"&&status==="verified"&&verified){patch={lifecycle_status:"active",updated_at:now};verb="activated"}
    else if(action==="retire"&&status==="active"){patch={lifecycle_status:"retired",retired_at:now,updated_at:now};verb="retired"}
    else if(action==="reactivate"&&status==="retired"&&verified){patch={lifecycle_status:"active",retired_at:null,reactivated_at:now,updated_at:now};verb="reactivated"}
    else return json({ok:false,code:verified?"invalid_origin_transition":"origin_verification_required",message:verified?"This lifecycle transition is not allowed.":"Verify origin control before activation."},409);
    const rows=await commercePersistenceRequest(`tkid_source_origins?organization_id=eq.${encodeURIComponent(authorized.organizationId)}&id=eq.${encodeURIComponent(originId)}`,{method:"PATCH",body:JSON.stringify(patch)})as Row[];await audit({...authorized,action:`tkid.origin_${verb}`,targetId:originId,metadata:{...metadata,status:patch.lifecycle_status}});return json({ok:true,origin:safe(rows[0]),message:`Origin ${verb}.`});
  }catch(error){const code=error instanceof Error&&error.message==="invalid_origin"?"invalid_origin":"resource_unavailable";return json({ok:false,code,message:code==="invalid_origin"?"Enter an exact HTTPS origin without a path, query, fragment, or wildcard.":"The requested resource is unavailable."},code==="invalid_origin"?400:404)}
}
