import "server-only";
import type { Activation, CommerceConnection, CommerceControlRepository, CredentialVersion, ProviderAccount, SourceMapping, SyncCheckpoint, SyncRun } from "./control-plane";

type Row = Record<string, unknown>;

function configuration() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "");
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("Commerce persistence is unavailable.");
  return { url, key };
}

export async function commercePersistenceRequest(path: string, init: RequestInit = {}) {
  const { url, key } = configuration();
  const response = await fetch(`${url}/rest/v1/${path}`, { ...init, cache: "no-store", headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json", Prefer: "return=representation", ...init.headers } });
  if (!response.ok) throw new Error(`Commerce persistence failed (${response.status}).`);
  if (response.status === 204) return [];
  const json = await response.json() as unknown;
  return (Array.isArray(json) ? json : [json]) as Row[];
}

/** Read an exact tenant-scoped count without materializing the matching rows. */
export async function commercePersistenceCount(path: string) {
  const { url, key } = configuration();
  const response = await fetch(`${url}/rest/v1/${path}`, {
    method: "GET",
    cache: "no-store",
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
      Accept: "application/json",
      Prefer: "count=exact",
    },
  });
  if (!response.ok) throw new Error(`Commerce persistence count failed (${response.status}).`);
  const range = response.headers.get("content-range") || "";
  const total = Number(range.slice(range.lastIndexOf("/") + 1));
  if (!Number.isFinite(total)) throw new Error("Commerce persistence count unavailable.");
  return total;
}

const request = commercePersistenceRequest;

const connection = (row: Row): CommerceConnection => ({ id: String(row.id), accountId: String(row.account_id), organizationId: String(row.organization_id), provider: String(row.provider), displayName: String(row.display_name), environment: String(row.environment), status: row.status as CommerceConnection["status"], lastSuccessAt: row.last_success_at ? String(row.last_success_at) : null, lastErrorAt: row.last_error_at ? String(row.last_error_at) : null, lastErrorCode: row.last_error_code ? String(row.last_error_code) : null, capabilities: (row.capabilities as Record<string, unknown>) || {}, setupRequestId: row.setup_request_id ? String(row.setup_request_id) : null });
const providerAccount = (row: Row): ProviderAccount => ({ id: String(row.id), organizationId: String(row.organization_id), connectionId: String(row.connection_id), externalId: String(row.provider_account_external_id), status: String(row.status), provisional: String(row.provider_account_external_id).startsWith("provisional:") });
const bytes = (value: unknown) => Uint8Array.from(Buffer.from(String(value).replace(/^\\x/, ""), "hex"));
const bytea = (value: Uint8Array) => `\\x${Buffer.from(value).toString("hex")}`;
const credential = (row: Row): CredentialVersion => ({ id: String(row.id), organizationId: String(row.organization_id), connectionId: String(row.connection_id), revokedAt: row.revoked_at ? String(row.revoked_at) : null, secretReference: row.secret_reference ? String(row.secret_reference) : undefined, encrypted: row.secret_ciphertext ? { keyId: String(row.encryption_key_id), encryptionVersion: Number(row.encryption_version), iv: bytes(row.secret_iv), ciphertext: bytes(row.secret_ciphertext) } : undefined });
const syncRun = (row: Row): SyncRun => ({ id: String(row.id), organizationId: String(row.organization_id), connectionId: String(row.connection_id), providerAccountId: String(row.provider_account_id), syncType: String(row.sync_type), mode: String(row.mode), status: String(row.status), leaseOwner: row.lease_owner ? String(row.lease_owner) : null, leaseExpiresAt: row.lease_expires_at ? String(row.lease_expires_at) : null });
const checkpoint = (row: Row): SyncCheckpoint => ({ id: String(row.id), syncRunId: String(row.sync_run_id), organizationId: String(row.organization_id), connectionId: String(row.connection_id), providerAccountId: String(row.provider_account_id), resource: String(row.resource), page: Number(row.page), perPage: Number(row.per_page), state: row.state as SyncCheckpoint["state"], retryCount: Number(row.retry_count), pageFingerprint: row.page_fingerprint ? String(row.page_fingerprint) : null });
const mapping = (row: Row): SourceMapping => ({ id: String(row.id), organizationId: String(row.organization_id), connectionId: String(row.connection_id), providerAccountId: String(row.provider_account_id), sourceObjectType: String(row.source_object_type), sourceObjectId: String(row.source_object_id), canonicalObjectType: String(row.canonical_object_type), canonicalObjectId: String(row.canonical_object_id), payloadHash: String(row.payload_hash), lastSeenAt: String(row.last_seen_at) });

export class SupabaseCommerceControlRepository implements CommerceControlRepository {
  async createConnection(input: Omit<CommerceConnection, "id" | "status">) { const rows = await request("commerce_provider_connections", { method: "POST", body: JSON.stringify({ account_id: input.accountId, organization_id: input.organizationId, provider: input.provider, display_name: input.displayName, environment: input.environment, setup_request_id: input.setupRequestId || null }) }); return connection(rows[0]); }
  async connectionById(id: string) { const rows = await request(`commerce_provider_connections?id=eq.${encodeURIComponent(id)}&limit=1`); return rows[0] ? connection(rows[0]) : null; }
  async connectionBySetupRequest(organizationId: string, setupRequestId: string) { const rows = await request(`commerce_provider_connections?organization_id=eq.${encodeURIComponent(organizationId)}&setup_request_id=eq.${encodeURIComponent(setupRequestId)}&limit=1`); return rows[0] ? connection(rows[0]) : null; }
  async listConnections(organizationId: string) { return (await request(`commerce_provider_connections?organization_id=eq.${encodeURIComponent(organizationId)}&order=created_at.asc`)).map(connection); }
  async updateConnection(id: string, organizationId: string, patch: Partial<Pick<CommerceConnection, "displayName" | "status" | "lastSuccessAt" | "lastErrorAt" | "lastErrorCode" | "capabilities">>) { const body: Row = { updated_at: new Date().toISOString() }; if (patch.displayName !== undefined) body.display_name = patch.displayName; if (patch.status !== undefined) body.status = patch.status; if (patch.lastSuccessAt !== undefined) body.last_success_at = patch.lastSuccessAt; if (patch.lastErrorAt !== undefined) body.last_error_at = patch.lastErrorAt; if (patch.lastErrorCode !== undefined) body.last_error_code = patch.lastErrorCode; if (patch.capabilities !== undefined) body.capabilities = patch.capabilities; const rows = await request(`commerce_provider_connections?id=eq.${encodeURIComponent(id)}&organization_id=eq.${encodeURIComponent(organizationId)}`, { method: "PATCH", body: JSON.stringify(body) }); if (!rows[0]) throw new Error("Commerce resource unavailable."); return connection(rows[0]); }
  async upsertProviderAccount(input: Omit<ProviderAccount, "id">) { const rows = await request("commerce_provider_accounts?on_conflict=connection_id,provider_account_external_id", { method: "POST", headers: { Prefer: "resolution=merge-duplicates,return=representation" }, body: JSON.stringify({ organization_id: input.organizationId, connection_id: input.connectionId, provider_account_external_id: input.externalId, status: input.status, metadata: { provisional: input.provisional } }) }); return providerAccount(rows[0]); }
  async listProviderAccounts(connectionId: string, organizationId: string) { return (await request(`commerce_provider_accounts?connection_id=eq.${encodeURIComponent(connectionId)}&organization_id=eq.${encodeURIComponent(organizationId)}`)).map(providerAccount); }
  async disableProviderAccount(id: string, connectionId: string, organizationId: string) { const rows = await request(`commerce_provider_accounts?id=eq.${encodeURIComponent(id)}&connection_id=eq.${encodeURIComponent(connectionId)}&organization_id=eq.${encodeURIComponent(organizationId)}`, { method: "PATCH", body: JSON.stringify({ status: "disabled", updated_at: new Date().toISOString() }) }); if (!rows[0]) throw new Error("Commerce resource unavailable."); return providerAccount(rows[0]); }
  async activeCredential(connectionId: string, organizationId: string) { const rows = await request(`commerce_provider_credentials?connection_id=eq.${encodeURIComponent(connectionId)}&organization_id=eq.${encodeURIComponent(organizationId)}&revoked_at=is.null&limit=1`); return rows[0] ? credential(rows[0]) : null; }
  async insertCredential(input: Omit<CredentialVersion, "id">) { if (!input.encrypted) throw new Error("Encrypted credential material is required."); const rows = await request("commerce_provider_credentials", { method: "POST", body: JSON.stringify({ organization_id: input.organizationId, connection_id: input.connectionId, credential_type: "api_key", storage_backend: "database_encrypted", encryption_key_id: input.encrypted.keyId, encryption_version: input.encrypted.encryptionVersion, secret_iv: bytea(input.encrypted.iv), secret_ciphertext: bytea(input.encrypted.ciphertext) }) }); return credential(rows[0]); }
  async rotateCredential(input: { connectionId: string; organizationId: string; previousId: string; replacement: Omit<CredentialVersion, "id"> }) { const encrypted = input.replacement.encrypted; if (!encrypted) throw new Error("Encrypted credential material is required."); const rows = await request("rpc/rotate_commerce_provider_credential", { method: "POST", body: JSON.stringify({ p_organization_id: input.organizationId, p_connection_id: input.connectionId, p_previous_id: input.previousId, p_credential_type: "api_key", p_key_id: encrypted.keyId, p_encryption_version: encrypted.encryptionVersion, p_secret_iv: bytea(encrypted.iv), p_secret_ciphertext: bytea(encrypted.ciphertext) }) }); if (!rows[0]) throw new Error("Commerce resource unavailable."); return credential(rows[0]); }
  async revokeCredential(id: string, connectionId: string, organizationId: string) { const now = new Date().toISOString(); const rows = await request(`commerce_provider_credentials?id=eq.${encodeURIComponent(id)}&connection_id=eq.${encodeURIComponent(connectionId)}&organization_id=eq.${encodeURIComponent(organizationId)}&revoked_at=is.null`, { method: "PATCH", body: JSON.stringify({ revoked_at: now, rotated_at: now, updated_at: now }) }); if (!rows[0]) throw new Error("Commerce resource unavailable."); }
  async createSyncRun(input: Omit<SyncRun, "id" | "status">) { const rows = await request("commerce_sync_runs", { method: "POST", body: JSON.stringify({ organization_id: input.organizationId, connection_id: input.connectionId, provider_account_id: input.providerAccountId, sync_type: input.syncType, mode: input.mode }) }); return syncRun(rows[0]); }
  async claimSyncRun(input: { runId: string; organizationId: string; connectionId: string; owner: string; leaseSeconds: number }) { const rows = await request("rpc/claim_commerce_sync_run", { method: "POST", body: JSON.stringify({ p_run_id: input.runId, p_organization_id: input.organizationId, p_connection_id: input.connectionId, p_lease_owner: input.owner, p_lease_seconds: input.leaseSeconds }) }); return rows[0] ? syncRun(rows[0]) : null; }
  async heartbeatSyncRun(input: { runId: string; organizationId: string; connectionId: string; owner: string; leaseSeconds: number }) { const rows = await request("rpc/heartbeat_commerce_sync_run", { method: "POST", body: JSON.stringify({ p_run_id: input.runId, p_organization_id: input.organizationId, p_connection_id: input.connectionId, p_lease_owner: input.owner, p_lease_seconds: input.leaseSeconds }) }); return Boolean(rows[0]); }
  async transitionSyncRun(input: { runId: string; organizationId: string; connectionId: string; owner: string; transition: "completed" | "completed_with_warnings" | "failed"; errorCode?: string; errorSummary?: string }) { const rows = await request("rpc/transition_commerce_sync_run", { method: "POST", body: JSON.stringify({ p_run_id: input.runId, p_organization_id: input.organizationId, p_connection_id: input.connectionId, p_lease_owner: input.owner, p_transition: input.transition, p_error_code: input.errorCode || null, p_error_summary: input.errorSummary || null }) }); return Boolean(rows[0]); }
  async cancelSyncRun(runId: string, organizationId: string, connectionId: string) { const rows = await request("rpc/cancel_commerce_sync_run", { method: "POST", body: JSON.stringify({ p_run_id: runId, p_organization_id: organizationId, p_connection_id: connectionId }) }); return Boolean(rows[0]); }
  async beginCheckpoint(input: Omit<SyncCheckpoint, "id" | "state" | "retryCount">) { const rows = await request("commerce_sync_checkpoints?on_conflict=sync_run_id,resource,page,per_page", { method: "POST", headers: { Prefer: "resolution=ignore-duplicates,return=representation" }, body: JSON.stringify({ sync_run_id: input.syncRunId, organization_id: input.organizationId, connection_id: input.connectionId, provider_account_id: input.providerAccountId, resource: input.resource, page: input.page, per_page: input.perPage }) }); if (rows[0]) return checkpoint(rows[0]); const existing = await this.checkpoints(input.syncRunId, input.organizationId); return existing.find((row) => row.resource === input.resource && row.page === input.page && row.perPage === input.perPage)!; }
  async updateCheckpoint(id: string, organizationId: string, connectionId: string, patch: Partial<Pick<SyncCheckpoint, "state" | "retryCount" | "pageFingerprint">>) { const body: Row = { updated_at: new Date().toISOString() }; if (patch.state !== undefined) body.state = patch.state; if (patch.retryCount !== undefined) body.retry_count = patch.retryCount; if (patch.pageFingerprint !== undefined) body.page_fingerprint = patch.pageFingerprint; if (patch.state === "completed") body.completed_at = new Date().toISOString(); const rows = await request(`commerce_sync_checkpoints?id=eq.${encodeURIComponent(id)}&organization_id=eq.${encodeURIComponent(organizationId)}&connection_id=eq.${encodeURIComponent(connectionId)}`, { method: "PATCH", body: JSON.stringify(body) }); if (!rows[0]) throw new Error("Commerce resource unavailable."); return checkpoint(rows[0]); }
  async checkpoints(syncRunId: string, organizationId: string) { return (await request(`commerce_sync_checkpoints?sync_run_id=eq.${encodeURIComponent(syncRunId)}&organization_id=eq.${encodeURIComponent(organizationId)}&order=page.asc`)).map(checkpoint); }
  async sourceMapping(connectionId: string, providerAccountId: string, sourceObjectType: string, sourceObjectId: string) { const rows = await request(`commerce_source_mappings?connection_id=eq.${encodeURIComponent(connectionId)}&provider_account_id=eq.${encodeURIComponent(providerAccountId)}&source_object_type=eq.${encodeURIComponent(sourceObjectType)}&source_object_id=eq.${encodeURIComponent(sourceObjectId)}&limit=1`); return rows[0] ? mapping(rows[0]) : null; }
  async upsertSourceMapping(input: Omit<SourceMapping, "id">) { const rows = await request("commerce_source_mappings?on_conflict=connection_id,provider_account_id,source_object_type,source_object_id", { method: "POST", headers: { Prefer: "resolution=merge-duplicates,return=representation" }, body: JSON.stringify({ organization_id: input.organizationId, connection_id: input.connectionId, provider_account_id: input.providerAccountId, source_object_type: input.sourceObjectType, source_object_id: input.sourceObjectId, canonical_object_type: input.canonicalObjectType, canonical_object_id: input.canonicalObjectId, first_seen_at: input.lastSeenAt, last_seen_at: input.lastSeenAt, payload_hash: input.payloadHash, mapping_version: "v1" }) }); return mapping(rows[0]); }
  async canonicalTargetExists(organizationId: string, type: string, id: string) { const tables: Record<string, string> = { person: "people", order: "platform_orders", provider_product: "commerce_provider_products", canonical_offer: "canonical_offers", financial_event: "conversions" }; const table = tables[type]; if (!table) return false; const idColumn = type === "order" ? "canonical_order_id" : "id"; return (await request(`${table}?organization_id=eq.${encodeURIComponent(organizationId)}&${idColumn}=eq.${encodeURIComponent(id)}&select=${idColumn}&limit=1`)).length === 1; }
  async decideProductMapping(input: { organizationId: string; connectionId: string; providerAccountId: string; providerProductId: string; resultingState: "approved" | "rejected"; businessContextId?: string; canonicalOfferId?: string; offerStepId?: string; offerVariantId?: string; mappingVersion: string; actorUserId: string; reason: string }) { const rows = await request("rpc/decide_commerce_product_mapping", { method: "POST", body: JSON.stringify({ p_organization_id: input.organizationId, p_connection_id: input.connectionId, p_provider_account_id: input.providerAccountId, p_provider_product_id: input.providerProductId, p_resulting_state: input.resultingState, p_business_context_id: input.businessContextId || null, p_canonical_offer_id: input.canonicalOfferId || null, p_offer_step_id: input.offerStepId || null, p_offer_variant_id: input.offerVariantId || null, p_mapping_version: input.mappingVersion, p_decided_by_user_id: input.actorUserId, p_reason: input.reason }) }); if (!rows[0]) throw new Error("Commerce resource unavailable."); }
  async activation(organizationId: string, workspace: Activation["workspace"]) { const rows = await request(`commerce_repository_activation?organization_id=eq.${encodeURIComponent(organizationId)}&workspace=eq.${encodeURIComponent(workspace)}&limit=1`); return rows[0] ? { organizationId, workspace, mode: rows[0].mode as Activation["mode"], connectionId: rows[0].connection_id ? String(rows[0].connection_id) : null, readinessEvidence: (rows[0].readiness_evidence || {}) as Activation["readinessEvidence"] } : null; }
  async setActivation(input: Activation & { actorUserId: string }) { const live = input.mode === "live_beta" || input.mode === "live"; const rows = await request("commerce_repository_activation?on_conflict=organization_id,workspace", { method: "POST", headers: { Prefer: "resolution=merge-duplicates,return=representation" }, body: JSON.stringify({ organization_id: input.organizationId, workspace: input.workspace, mode: input.mode, connection_id: input.connectionId, activated_by_user_id: input.actorUserId, activated_at: new Date().toISOString(), readiness_evidence: input.readinessEvidence, readiness_verified_at: live ? new Date().toISOString() : null, readiness_verified_by_user_id: live ? input.actorUserId : null, updated_at: new Date().toISOString() }) }); return { ...input, mode: rows[0].mode as Activation["mode"] }; }
  async evidenceByReference(reference: string) { const rows = await request(`commerce_evidence_records?id=eq.${encodeURIComponent(reference)}&deleted_at=is.null&select=organization_id,storage_reference&limit=1`); return rows[0] ? { organizationId: String(rows[0].organization_id), storageReference: String(rows[0].storage_reference) } : null; }
  async recordAudit(input: { scope: { actorUserId: string; accountId: string; organizationId: string; correlationId: string }; action: string; targetType: string; targetId: string; result: "success" | "failure" | "denied"; metadata?: Record<string, unknown> }) { await request("tracekit_audit_events", { method: "POST", body: JSON.stringify({ actor_user_id: input.scope.actorUserId, account_id: input.scope.accountId, organization_id: input.scope.organizationId, action: input.action, target_type: input.targetType, target_id: input.targetId, result: input.result, correlation_id: input.scope.correlationId, metadata: input.metadata || {} }) }); }
}
