"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import type { ConnectionExperience } from "@/lib/commerce/integration-experience";

export function EverflowNetworkSelector({ connections, selectedId }: { connections: ConnectionExperience[]; selectedId?: string }) {
  const everflow = connections.filter((connection) => connection.provider === "everflow");
  if (!everflow.length) return null;
  return <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="tk-label">Everflow networks</p><h2 className="mt-2 text-sm font-semibold">{everflow.length} connected instance{everflow.length === 1 ? "" : "s"}</h2><p className="mt-2 text-xs text-slate-500">Select a network to view and operate only that connection.</p></div><div className="flex flex-wrap gap-2">{everflow.map((connection) => <Link key={connection.id} href={`/connections/commerce/${connection.id}`} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${connection.id === selectedId ? "border-cyan/40 bg-cyan/10 text-cyan-100" : "border-white/10 bg-white/[.03] text-slate-300 hover:border-white/20"}`}>{connection.displayName}{connection.providerAccountLabel ? ` · NID ${connection.providerAccountLabel}` : ""}</Link>)}</div></div></section>;
}

export function EverflowManualSync({ connection }: { connection: ConnectionExperience }) {
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null); const router = useRouter();
  if (connection.provider !== "everflow" || !connection.canManage) return null;
  const label = `${connection.displayName}${connection.providerAccountLabel ? ` · NID ${connection.providerAccountLabel}` : ""}`;
  async function run() { setBusy(true); setNotice(null); try { const response = await fetch(`/api/commerce/connections/${connection.id}/sync-now`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); const result = await response.json().catch(() => ({})) as { message?: string; code?: string }; if (!response.ok) throw new Error(result.message || result.code || "Manual Everflow sync was not started."); setNotice(`Sync started for ${label}. Refreshing run state…`); router.refresh(); window.setTimeout(() => router.refresh(), 2500); } catch (error) { setNotice(error instanceof Error ? error.message : "Manual Everflow sync was not started."); } finally { setBusy(false); } }
  return <section className="mt-4 rounded-2xl border border-cyan-400/30 bg-[#0b111a] p-5 shadow-lg shadow-black/20"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">Manual synchronization</p><h2 className="mt-2 text-base font-semibold text-white">{label}</h2><p className="mt-2 text-xs leading-5 text-slate-400">Runs only this selected Everflow connection through the guarded server sync path.</p></div><button type="button" onClick={run} disabled={busy} className="min-w-32 rounded-lg border border-cyan-300/50 bg-cyan-300 px-5 py-2.5 text-sm font-bold text-slate-950 shadow-md transition hover:bg-cyan-200 disabled:cursor-not-allowed disabled:opacity-50">{busy ? "Starting…" : "Run Sync"}</button></div>{notice ? <p role="status" className="mt-4 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300">{notice}</p> : null}</section>;
}


export function EverflowHistoricalImport({ connection }: { connection: ConnectionExperience }) {
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[runState,setRunState]=useState<any>(null); const router=useRouter();
  async function refreshStatus(){try{const response=await fetch(`/api/commerce/connections/${connection.id}/historical-import`,{cache:"no-store"});const result=await response.json().catch(()=>({}));if(response.ok)setRunState(result.run||null);}catch{}}
  useEffect(()=>{if(connection.provider!=="everflow"||!connection.canManage)return;void refreshStatus();const timer=window.setInterval(()=>void refreshStatus(),5000);return()=>window.clearInterval(timer)},[connection.id,connection.provider,connection.canManage]);
  if(connection.provider!=="everflow"||!connection.canManage)return null;
  async function run(){if(!startDate||!endDate||busy)return;setBusy(true);setNotice(null);try{const response=await fetch(`/api/commerce/connections/${connection.id}/historical-import`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({startDate,endDate})});const result=await response.json().catch(()=>({})) as {message?:string;code?:string;runId?:string};if(!response.ok)throw new Error(result.message||result.code||"Historical Everflow import could not be queued.");setNotice(result.message||"Historical import queued.");await refreshStatus();router.refresh();}catch(error){setNotice(error instanceof Error?error.message:"Historical Everflow import could not be queued.");}finally{setBusy(false)}}
  const state=String(runState?.effective_status||runState?.status||""),running=state==="queued"||state==="running",interrupted=state==="interrupted",failed=state==="failed",completed=state==="completed"||state==="completed_with_warnings",meta=runState?.metadata||{},rangeLabel=meta.from&&meta.to?`${String(meta.from).slice(0,10)} → ${String(meta.to).slice(0,10)}`:null;
  return <section className="mt-4 rounded-2xl border border-white/10 bg-[#0b111a] p-5"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">Historical import</p><h2 className="mt-2 text-base font-semibold text-white">Import a bounded Everflow date range</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-400">Adds historical conversion evidence for this selected network without moving the normal incremental sync cursor. Imported conversions are persisted and run through TraceKit&apos;s existing order-linkage pipeline.</p></div><div className="grid w-full gap-3 sm:w-auto sm:grid-cols-[150px_150px_auto]"><label className="text-[11px] text-slate-400"><span className="mb-1 block">Start date</span><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="w-full rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-sm text-white"/></label><label className="text-[11px] text-slate-400"><span className="mb-1 block">End date</span><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="w-full rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-sm text-white"/></label><button type="button" onClick={run} disabled={busy||running||!startDate||!endDate} className="self-end rounded-lg border border-cyan-300/50 bg-cyan-300 px-5 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-200 disabled:cursor-not-allowed disabled:opacity-50">{busy?"Queuing…":running?"Import Running":"Run Historical Import"}</button></div></div><div className="mt-3 text-[11px] text-slate-500">Conversions · Maximum 31 calendar days per run · Existing live cursor is preserved</div>
  {running?<div className="mt-4 rounded-lg border border-cyan-400/20 bg-cyan-400/5 px-3 py-3 text-xs text-cyan-100"><div className="font-semibold">{state==="queued"?"Import queued":"Import running"}{rangeLabel?` · ${rangeLabel}`:""}</div>{state==="queued"?<p className="mt-1 text-slate-300">Waiting for the Everflow worker to start. You can leave this page; the queued import is persisted.</p>:<><p className="mt-1 text-slate-300">TraceKit is importing Everflow conversion evidence. You can leave this page; status is persisted and will be shown when you return.</p><div className="mt-3 grid gap-2 sm:grid-cols-4"><div className="rounded-md bg-white/[.04] p-2"><div className="text-[10px] uppercase tracking-wide text-slate-400">Pages completed</div><div className="mt-1 text-sm font-semibold text-white">{Number(runState?.pages_completed||0)}</div></div><div className="rounded-md bg-white/[.04] p-2"><div className="text-[10px] uppercase tracking-wide text-slate-400">Records processed</div><div className="mt-1 text-sm font-semibold text-white">{Number(runState?.records_seen||0)}</div></div><div className="rounded-md bg-white/[.04] p-2"><div className="text-[10px] uppercase tracking-wide text-slate-400">Records persisted</div><div className="mt-1 text-sm font-semibold text-white">{Number(runState?.records_created||0)}</div></div><div className="rounded-md bg-white/[.04] p-2"><div className="text-[10px] uppercase tracking-wide text-slate-400">Last activity</div><div className="mt-1 text-xs font-semibold text-white">{runState?.heartbeat_at?new Date(runState.heartbeat_at).toLocaleTimeString():"Starting…"}</div></div></div>{meta.total_count!=null?<p className="mt-2 text-[11px] text-slate-400">Everflow reported {Number(meta.total_count).toLocaleString()} records for this bounded query.</p>:null}</>}</div>:null}
  {completed?<div className={`mt-4 rounded-lg border px-3 py-3 text-xs ${state==="completed_with_warnings"?"border-amber-400/20 bg-amber-400/5 text-amber-100":"border-emerald-400/20 bg-emerald-400/5 text-emerald-100"}`}><div className="font-semibold">{state==="completed_with_warnings"?"Import completed with warnings":"Import completed"}{rangeLabel?` · ${rangeLabel}`:""}</div><p className="mt-1">{Number(runState?.records_seen||meta.result?.seen||0)} records processed · {Number(runState?.records_created||meta.result?.persisted||0)} persisted · {Number(runState?.pages_completed||meta.result?.pages||0)} pages.</p>{state==="completed_with_warnings"&&runState?.last_error_summary?<p className="mt-2 text-amber-200">Attribution reconciliation warning: {runState.last_error_summary}</p>:null}</div>:null}
  {interrupted?<div className="mt-4 rounded-lg border border-amber-400/20 bg-amber-400/5 px-3 py-3 text-xs text-amber-100"><div className="font-semibold">Import interrupted{rangeLabel?` · ${rangeLabel}`:""}</div><p className="mt-1">{runState?.status_message||"The historical import worker stopped before recording completion. TraceKit will attempt to recover this expired run."}</p>{runState?.heartbeat_at?<p className="mt-2 text-[11px] text-amber-200">Last worker heartbeat: {new Date(runState.heartbeat_at).toLocaleString()}</p>:null}</div>:null}
  {failed?<div className="mt-4 rounded-lg border border-rose-400/20 bg-rose-400/5 px-3 py-3 text-xs text-rose-200"><div className="font-semibold">Import failed{rangeLabel?` · ${rangeLabel}`:""}</div><p className="mt-1">{runState?.last_error_summary||"TraceKit could not complete this historical import."}</p>{runState?.last_error_code?<p className="mt-2 text-[11px] text-rose-300">Error code: {runState.last_error_code}</p>:null}</div>:null}
  {notice?<p role="status" className="mt-4 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300">{notice}</p>:null}</section>;
}
