"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { KeyRound, Plug, ShieldCheck } from "lucide-react";
import type { ConnectionExperience } from "@/lib/commerce/integration-experience";

const pill: Record<string,string> = {
  connected:"border-emerald-400/25 bg-emerald-400/10 text-emerald-300",
  active:"border-emerald-400/25 bg-emerald-400/10 text-emerald-300",
  passed:"border-emerald-400/25 bg-emerald-400/10 text-emerald-300",
  pending:"border-slate-400/20 bg-slate-400/10 text-slate-300",
  degraded:"border-amber-400/25 bg-amber-400/10 text-amber-200",
  missing:"border-rose-400/25 bg-rose-400/10 text-rose-200",
};
function Status({value}:{value:string}){return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.12em] ${pill[value]||pill.pending}`}>{value.replaceAll("_"," ")}</span>}
function Rows({rows}:{rows:Array<[string,string]>}){return <div className="space-y-3">{rows.map(([label,value])=><div key={label} className="flex items-start justify-between gap-4 text-xs"><span className="text-slate-500">{label}</span><span className="text-right font-medium text-slate-200">{value}</span></div>)}</div>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="mb-5 flex items-center gap-2 text-sm font-semibold">{icon}{title}</div>{children}</section>}
function fmt(value:string|null){return value?new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Not available"}

export function MarketingConnectionDetail({connection}:{connection:ConnectionExperience}){
 const [accountPickerOpen,setAccountPickerOpen]=useState(false);
 const [proof,setProof]=useState<null|{accountLabel:string;days:number;rowCount:number;totalCostMicros:number;totalImpressions:number;totalClicks:number;rows:Array<{date:string;campaignId:string;campaignName:string;campaignStatus:string;impressions:number;clicks:number;costMicros:number;conversions:number;conversionValue:number}>}>(null),[proofBusy,setProofBusy]=useState(false),[proofError,setProofError]=useState<string|null>(null);
 async function runProof(days=7){setProofBusy(true);setProofError(null);try{const response=await fetch("/v1/integrations/google-ads/reporting-proof",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId:connection.id,days})});const result=await response.json().catch(()=>null) as {ok?:boolean;proof?:typeof proof;message?:string}|null;if(!response.ok||!result?.ok||!result.proof){setProofError(result?.message||"The bounded Google Ads reporting proof could not be completed.");return}setProof(result.proof)}catch{setProofError("The bounded Google Ads reporting proof could not be completed.")}finally{setProofBusy(false)}}
 const providerName=connection.provider==="google_ads"?"Google Ads":connection.provider==="meta_ads"?"Meta Ads":connection.provider==="tiktok_ads"?"TikTok Ads":connection.displayName;
 const selected=connection.readiness.find(g=>g.id==="account_selection");
 return <div className="min-h-full bg-[#080a0f] text-slate-100"><div className="mx-auto max-w-[1360px] px-5 py-8 sm:px-8 lg:px-10">
  <header className="flex flex-col gap-5 border-b border-white/10 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><div className="tk-brand-eyebrow text-[10px] font-semibold uppercase tracking-[.2em]">Paid media · {connection.environment}</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">{providerName}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{connection.organizationName} · OAuth identity, advertising-account selection, and provider access readiness.</p></div><Link href="/connections" className="tk-brand-link text-xs font-semibold">Back to Connections</Link></header>
  <div className="mt-6 grid gap-4 lg:grid-cols-3">
   <Panel title="Identity" icon={<Plug className="h-4 w-4"/>}><Rows rows={[["Provider",providerName],["Environment",connection.environment],["Organization",connection.organizationName],["Selected ad account",connection.providerAccountLabel||"None selected"],["Status",connection.status]]}/></Panel>
   <Panel title="OAuth credential" icon={<KeyRound className="h-4 w-4"/>}><div className="flex items-center justify-between"><Status value={connection.credential.status}/><span className="text-xs text-slate-500">Version {connection.credential.version||"—"}</span></div><p className="mt-4 text-xs leading-5 text-slate-500">Credential material is encrypted server-side and is never returned to this page.</p><p className="mt-4 text-[11px] text-slate-500">Created · {fmt(connection.credential.createdAt)}</p>{connection.provider==="google_ads"&&connection.canManage?<button type="button" onClick={()=>setAccountPickerOpen(true)} className="mt-5 text-xs font-semibold text-blue-300">Change selected accounts</button>:null}</Panel>
   <Panel title="Provider verification" icon={<ShieldCheck className="h-4 w-4"/>}><Rows rows={[["Connection",connection.status],["Last verified",fmt(connection.lastVerifiedAt)],["Account selection",selected?.status||"pending"]]}/></Panel>
  </div>
  <section className="mt-4 rounded-2xl border border-white/10 bg-white/[.035]"><div className="border-b border-white/10 px-5 py-4"><h2 className="font-semibold">Connection readiness</h2><p className="mt-1 text-xs text-slate-500">Paid-media provider state only. Commerce synchronization gates do not apply to this connection.</p></div><div className="divide-y divide-white/10">{connection.readiness.map(g=><div key={g.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[220px_130px_1fr] sm:items-center"><strong className="text-sm">{g.label}</strong><Status value={g.status}/><p className="text-xs leading-5 text-slate-400">{g.explanation}</p></div>)}</div></section>
  {connection.provider==="google_ads"?<section className="mt-4 rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="tk-label">Read-only provider proof</p><h2 className="mt-2 text-sm font-semibold">7-day campaign reporting</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-400">Runs a bounded Google Ads reporting read against the selected account. Results are displayed only and are not persisted.</p></div><button type="button" onClick={()=>runProof(7)} disabled={proofBusy} className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-950 disabled:opacity-50">{proofBusy?"Running…":"Run 7-day proof"}</button>{proof?.rowCount===0&&!proofBusy?<button type="button" onClick={()=>runProof(30)} className="ml-2 rounded-lg border border-white/15 px-3 py-2 text-xs font-semibold text-slate-200">Try 30 days</button>:null}</div>{proofError?<p role="alert" className="mt-4 rounded-xl border border-rose-400/20 bg-rose-400/5 px-3 py-2 text-xs text-rose-300">{proofError}</p>:null}{proof?<><div className="mt-5 grid gap-3 sm:grid-cols-4"><Rows rows={[["Account",proof.accountLabel],["Rows",String(proof.rowCount)]]}/><Rows rows={[["Spend",(proof.totalCostMicros/1_000_000).toFixed(2)],["Days",String(proof.days)]]}/><Rows rows={[["Impressions",proof.totalImpressions.toLocaleString()],["Clicks",proof.totalClicks.toLocaleString()]]}/><Rows rows={[["Persistence","None"],["Mutation","None"]]}/></div><div className="mt-5 max-h-80 overflow-auto rounded-xl border border-white/10"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-white/[.05] text-slate-400"><tr><th className="p-3">Date</th><th className="p-3">Campaign</th><th className="p-3">Status</th><th className="p-3 text-right">Spend</th><th className="p-3 text-right">Impr.</th><th className="p-3 text-right">Clicks</th></tr></thead><tbody className="divide-y divide-white/10">{proof.rows.map((row,i)=><tr key={row.date+"-"+row.campaignId+"-"+i}><td className="p-3">{row.date}</td><td className="p-3">{row.campaignName||row.campaignId}</td><td className="p-3">{row.campaignStatus}</td><td className="p-3 text-right">{(row.costMicros/1_000_000).toFixed(2)}</td><td className="p-3 text-right">{row.impressions.toLocaleString()}</td><td className="p-3 text-right">{row.clicks.toLocaleString()}</td></tr>)}</tbody></table></div></>:null}</section>:null}
  <section className="mt-4 rounded-2xl border border-blue-400/15 bg-blue-400/[.035] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="tk-label text-blue-200">Paid-media ingestion</p><h2 className="mt-2 text-sm font-semibold">Not enabled</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-400">This connection currently proves OAuth access and explicit advertising-account selection. Campaign, spend, reporting, scheduling, and production ingestion remain separate milestones.</p></div><Status value="pending"/></div></section>
 </div></div>
}

function GoogleAccountSelectionDialog({connectionId,close}:{connectionId:string;close:()=>void}){const [accounts,setAccounts]=useState<Array<{id:string;label:string|null;externalId:string;selectedForSync:boolean}>>([]),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);useEffect(()=>{fetch(`/v1/integrations/google-ads/accounts?connectionId=${encodeURIComponent(connectionId)}`,{cache:"no-store"}).then(r=>r.json()).then((r:{ok?:boolean;accounts?:Array<{id:string;label:string|null;externalId:string;selectedForSync:boolean}>})=>{if(!r.ok)return;const rows=r.accounts||[];setAccounts(rows);setSelected(rows.filter(a=>a.selectedForSync).map(a=>a.id))}).catch(()=>setMessage("TraceKit could not load Google Ads accounts."));},[connectionId]);async function save(){if(!selected.length){setMessage("Select at least one Google Ads account.");return}setBusy(true);setMessage(null);try{const response=await fetch("/v1/integrations/google-ads/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId,accountIds:selected})});const r=await response.json().catch(()=>null)as{ok?:boolean;message?:string}|null;if(!response.ok||!r?.ok){setMessage(r?.message||"TraceKit could not save the Google Ads account selection.");return}location.reload()}catch{setMessage("TraceKit could not save the Google Ads account selection.")}finally{setBusy(false)}}return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-lg rounded-2xl border border-white/15 bg-[#10131a] p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Change Google Ads accounts</h2><button type="button" onClick={close} className="text-sm text-slate-400">Close</button></div><p className="mt-3 text-xs leading-5 text-slate-400">Choose the advertiser account(s) TraceKit should use. This changes selection only and does not reauthorize Google.</p><div className="mt-5 max-h-72 space-y-2 overflow-y-auto">{accounts.map(a=><label key={a.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 bg-white/[.035] px-3 py-3"><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,a.id]:v.filter(id=>id!==a.id))}/><span><span className="block text-sm font-medium">{a.label||"Google Ads account"}</span><span className="block text-[11px] text-slate-500">Customer · {a.externalId}</span></span></label>)}</div>{message?<p role="alert" className="mt-4 text-xs text-rose-300">{message}</p>:null}<button type="button" disabled={busy||!accounts.length} onClick={save} className="mt-5 w-full rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50">{busy?"Saving…":"Save account selection"}</button></div></div>}
