import { NextResponse } from "next/server";
import { resolveApplicationSession } from "@/lib/identity/application-session";
import { requirePermission, AuthorizationDeniedError } from "@/lib/identity/authorization-gateway";
function apiBaseUrl(){return String(process.env.TRACEKIT_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_BASE||"http://127.0.0.1:8787").replace(/\/+$/,"");}
function adminSecret(){return String(process.env.TK_SECRET_KEY||process.env.TRACEKIT_TK_SECRET||"").trim();}
async function readJsonSafe(res:Response){const text=await res.text().catch(()=>"");try{return text?JSON.parse(text):{};}catch{return{ok:false,error:"invalid_json",message:text.slice(0,400)};}}
async function authorizedScope(permission:"organizations.view"|"actions.execute"){const resolution=await resolveApplicationSession();if(resolution.kind!=="authenticated"||!resolution.session.activeOrganization)throw new AuthorizationDeniedError();requirePermission(resolution.session,permission);return{workspaceId:resolution.session.activeOrganization.id,actorId:resolution.session.user.id};}
async function workItemPathFromContext(context:any){const params=await context?.params,parts=Array.isArray(params?.workItemPath)?params.workItemPath:[];return parts.map((part:string)=>encodeURIComponent(part)).join("/");}
async function workItemFetch(pathAndQuery:string,init:RequestInit={}){const secret=adminSecret();if(!secret)return{status:500,body:{ok:false,error:"admin_auth_not_configured"}};const res=await fetch(`${apiBaseUrl()}${pathAndQuery}`,{...init,cache:"no-store",headers:{accept:"application/json","content-type":"application/json","x-tk-secret":secret,...(init.headers||{})}});return{status:res.status,body:await readJsonSafe(res)};}
function denied(){return NextResponse.json({ok:false,error:"resource_unavailable"},{status:404});}
export async function GET(req:Request,context:any){try{const scope=await authorizedScope("organizations.view"),path=await workItemPathFromContext(context);if(!path)return NextResponse.json({ok:false,error:"bad_request"},{status:400});const url=new URL(req.url);url.searchParams.set("workspace_id",scope.workspaceId);const result=await workItemFetch(`/v1/work-items/${path}?${url.searchParams.toString()}`,{method:"GET"});return NextResponse.json(result.body,{status:result.status});}catch(error){return error instanceof AuthorizationDeniedError?denied():denied();}}
export async function POST(req:Request,context:any){try{const scope=await authorizedScope("actions.execute"),path=await workItemPathFromContext(context);if(!path)return NextResponse.json({ok:false,error:"bad_request"},{status:400});const body=await req.json().catch(()=>({}));const safeBody={...body,workspace_id:scope.workspaceId,actor_id:scope.actorId};delete safeBody.workspaceId;delete safeBody.actorId;delete safeBody.user_id;delete safeBody.userId;const result=await workItemFetch(`/v1/work-items/${path}`,{method:"POST",body:JSON.stringify(safeBody)});return NextResponse.json(result.body,{status:result.status});}catch(error){return error instanceof AuthorizationDeniedError?denied():denied();}}
