name = "tracekit-api"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[vars]
  SUPABASE_URL = "https://uoeosoiegatlqtzemsfv.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZW9zb2llZ2F0bHF0emVtc2Z2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzIzMzk0OSwiZXhwIjoyMDc4ODA5OTQ5fQ.-Jnu-883DR5zaJQOROjr87ywqwZildXhs309asX6kDM"
  TRACEKIT_ROOT_DOMAIN = "buyecowatt.com"
  TRACEKIT_AUTO_LINK_OUTBOUND = "true"
  INTEGRATIONS_ENC_KEY = "UwMDAuV9ILnMdLOhBCfA1YcU8xOKHOEzi8XChHZc0Z8="
  

[triggers]
crons = ["0 * * * *"] # every hour

# Required Cloudflare Worker secrets:
# - SUPABASE_SERVICE_ROLE_KEY
# - KONNEKTIVE_INGEST_TOKEN
# - EVERFLOW_INGEST_TOKEN
# - INTEGRATIONS_ENC_KEY
# - TK_SECRET_KEY
#
# Set each with:
# npx wrangler secret put SECRET_NAME
