import{randomUUID}from"node:crypto";import{NextResponse}from"next/server";import{resolveApplicationSession}from"@/lib/identity/application-session";import{AuthorizationDeniedError,requirePermission}from"@/lib/identity/authorization-gateway";import{decodeCommerceCredentialKey,decryptCommerceCredential}from"@/lib/commerce/credential-crypto";import{supabaseAuthHeaders}from"@/lib/commerce/supabase-auth";import{listCommasWebhookSubscriptions,TARGET_URL}from"@/scripts/inspect-commas-webhooks";import{executeGovernedCommasTestDelivery}from"@/lib/commerce/commas-webhook-test-delivery";
import{assessIntelligenceAction}from"@/lib/mcp/production-v1-policy";
type Row=Record<string,unknown>;const EVENT="dispute.created";
function sameOrigin(r:Request){const o=r.headers.get("origin"),s=r.headers.get("sec-fetch-site");return(!o||o===new URL(r.url).origin)&&(!s||s==="same-origin");}
function res(id:string,b:Record<string,unknown>,status:number){return NextResponse.json({...b,requestId:id},{status,headers:{"x-tracekit-request-id":id}});}
function cfg(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,""),key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Persistence unavailable.");return{url,key};}
async function db(path:string){const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/${path}`,{headers:supabaseAuthHeaders(key),cache:"no-store"});if(!r.ok)throw new Error("Persistence read failed.");const v=await r.json();return(Array.isArray(v)?v:[v])as Row[];}
const bytes=(v:unknown)=>Uint8Array.from(Buffer.from(String(v).replace(/^\\x/,""),"hex"));
export async function POST(request:Request){const id=randomUUID();try{
 if(!sameOrigin(request))return res(id,{ok:false,code:"request_verification_failed"},403);
 const resolution=await resolveApplicationSession();if(resolution.kind!=="authenticated"||!resolution.session.activeOrganization)return res(id,{ok:false,code:"resource_unavailable"},404);requirePermission(resolution.session,"actions.execute");
 if(!assessIntelligenceAction("commas.webhook_test_delivery").allowed)return res(id,{ok:false,code:"action_not_available"},404);
 const body=await request.json().catch(()=>({}))as Row;if(body.confirm!==true)return res(id,{ok:false,code:"explicit_confirmation_required"},400);
 const org=resolution.session.activeOrganization.id,connections=await db(`commerce_provider_connections?provider=eq.commas&status=eq.connected&organization_id=eq.${encodeURIComponent(org)}&select=id,organization_id&limit=2`);if(connections.length!==1)return res(id,{ok:false,code:"commas_connection_unavailable"},409);
 const cid=String(connections[0].id),credentials=await db(`commerce_provider_credentials?connection_id=eq.${cid}&organization_id=eq.${encodeURIComponent(org)}&revoked_at=is.null&select=encryption_key_id,encryption_version,secret_iv,secret_ciphertext&limit=2`);if(credentials.length!==1)return res(id,{ok:false,code:"commas_credential_unavailable"},409);
 const row=credentials[0],keyId=process.env.COMMERCE_CREDENTIALS_KEY_ID,version=Number(process.env.COMMERCE_CREDENTIALS_ENCRYPTION_VERSION||"1");if(!keyId||String(row.encryption_key_id)!==keyId||Number(row.encryption_version)!==version)return res(id,{ok:false,code:"credential_envelope_mismatch"},503);
 const apiKey=await decryptCommerceCredential({keyId,encryptionVersion:version,iv:bytes(row.secret_iv),ciphertext:bytes(row.secret_ciphertext)},decodeCommerceCredentialKey(process.env.COMMERCE_CREDENTIALS_ENC_KEY));
 const subs=await listCommasWebhookSubscriptions(apiKey),matches=subs.filter(s=>s.webhookUrl===TARGET_URL&&s.eventTypes.includes(EVENT));if(matches.length!==1)return res(id,{ok:false,code:"exact_webhook_subscription_unavailable",matches:matches.length},409);
 const subscriptionId=matches[0].id;if(!subscriptionId)return res(id,{ok:false,code:"subscription_id_unavailable"},409);
 const result=await executeGovernedCommasTestDelivery({authorization:{decision:"consume",consumptionId:id},envelope:{state:"authorized",provider:"commas",operation:"webhook_test_delivery",subscriptionId,eventType:EVENT,idempotencyKey:id,auditCorrelationId:resolution.session.correlationId},apiKey});
 const executionId=randomUUID();const{url,key}=cfg();const audit=await fetch(`${url}/rest/v1/rpc/record_mcp_external_action_audit`,{method:"POST",headers:{...supabaseAuthHeaders(key),"Content-Type":"application/json"},body:JSON.stringify({p_execution_id:executionId,p_organization_id:org,p_provider:"commas",p_operation:"webhook_test_delivery",p_event_type:EVENT,p_request_id:id,p_subscription_id:subscriptionId,p_verification_status:result.verification.status,p_provider_http_status:result.providerResponse?.httpStatus??null,p_provider_api_status:result.providerResponse?.apiStatus??null,p_provider_event_sent:result.providerResponse?.eventSent??null,p_target_response_status:result.providerResponse?.responseStatus??null,p_provider_configuration_mutation:false,p_executed_by:resolution.session.user.id,p_executed_at:new Date().toISOString(),p_evidence:{verificationReason:result.verification.reason}})});if(!audit.ok)throw new Error("Execution audit persistence failed.");
 return res(id,{ok:result.status==="completed",executionId,provider:result.provider,operation:result.operation,eventType:EVENT,subscriptionMatched:true,verification:result.verification,providerResponse:result.providerResponse,providerConfigurationMutation:false},result.status==="completed"?200:409);
}catch(e){if(e instanceof AuthorizationDeniedError)return res(id,{ok:false,code:"resource_unavailable"},404);return res(id,{ok:false,code:"commas_test_delivery_failed"},500);}}
